// @generated by scripts/verification/rectangular_interface_catalog.py; DO NOT EDIT.
#![allow(non_snake_case)]
use vstd::prelude::*;
use crate::{boundary::scalar::{Scalar}, proof::tensor::types::{Tensor1D, Tensor2D, IntTensor1D}};
use crate::proof::tensor::shape as TS;
#[cfg(verus_only)]
use crate::boundary::backend_certificates::support::generated_kernel_allocation_cell;

pub mod geometry_D_1024 {
use super::*;
verus! {
// Abstract interface for ONE fixed, separately qualified deployment.
// Alternative implementations prove this same theory; their outputs
// are not equated. See the separate implementation proof records.
// Raw ContractIR lowering for embedding_kernel

pub open spec fn raw_batch_invariance_cdiv(numerator: int, denominator: int) -> int {
    (numerator + denominator - 1) / denominator
}

pub struct RawSide {
    pub ids: Seq<int>,
    pub weight: Seq<Seq<Scalar>>,
    pub o: Seq<Seq<Scalar>>,
    pub M: int,
    pub V: int,
}

pub struct RawBatchInvarianceFree {
    pub x: int,
}


pub uninterp spec fn raw_o_cell(before: RawSide, _i0: int, _i1: int) -> Scalar;

pub open spec fn raw_o_after(before: RawSide)
    -> Seq<Seq<Scalar>>
{
    Seq::new(before.o.len(), |_i0: int| Seq::new(before.o[_i0].len(), |_i1: int| raw_o_cell(before, _i0, _i1)))
}

pub open spec fn raw_execute(before: RawSide) -> RawSide {
    RawSide {
        ids: before.ids,
        weight: before.weight,
        o: raw_o_after(before),
        M: before.M,
        V: before.V,
    }
}

pub open spec fn raw_batch_invariance_raw_pre(
    left: RawSide,
    right: RawSide,
    free: RawBatchInvarianceFree,
) -> bool {
    &&& 0 <= left.M
    &&& left.ids.len() as int == left.M
    &&& 0 <= left.V
    &&& 0 <= 1024
    &&& left.weight.len() as int == left.V
    &&& forall|_s0: int| 0 <= _s0 < left.weight.len() as int ==> (#[trigger] left.weight[_s0]).len() as int == 1024
    &&& left.o.len() as int == left.M
    &&& forall|_s0: int| 0 <= _s0 < left.o.len() as int ==> (#[trigger] left.o[_s0]).len() as int == 1024
    &&& 0 <= right.M
    &&& right.ids.len() as int == right.M
    &&& 0 <= right.V
    &&& right.weight.len() as int == right.V
    &&& forall|_s0: int| 0 <= _s0 < right.weight.len() as int ==> (#[trigger] right.weight[_s0]).len() as int == 1024
    &&& right.o.len() as int == right.M
    &&& forall|_s0: int| 0 <= _s0 < right.o.len() as int ==> (#[trigger] right.o[_s0]).len() as int == 1024
    &&& left.V == right.V
    &&& left.weight == right.weight
    &&& right.M == 1
    &&& free.x >= 0
    &&& free.x < left.M
    &&& (0 <= free.x && free.x <= (free.x + 1) && (free.x + 1) <= left.M && 0 <= 0 && 0 <= 1 && 1 <= right.M && ((free.x + 1) - free.x) == (1 - 0) && forall|_r0: int| 0 <= _r0 < ((free.x + 1) - free.x) ==> #[trigger] left.ids[free.x + _r0] == right.ids[0 + _r0])
    &&& left.ids[free.x] == right.ids[0]
}

pub open spec fn raw_batch_invariance_raw_post(
    left: RawSide,
    right: RawSide,
    free: RawBatchInvarianceFree,
) -> bool {
    &&& (0 <= free.x && free.x <= (free.x + 1) && (free.x + 1) <= left.M && 0 <= 0 && 0 <= 1 && 1 <= right.M && ((free.x + 1) - free.x) == (1 - 0) && 0 <= 0 && 0 <= 1024 && 1024 <= 1024 && 0 <= 0 && 0 <= 1024 && 1024 <= 1024 && (1024 - 0) == (1024 - 0) && forall|_r0: int, _r1: int| 0 <= _r0 < ((free.x + 1) - free.x) && 0 <= _r1 < (1024 - 0) ==> #[trigger] left.o[free.x + _r0][0 + _r1] == right.o[0 + _r0][0 + _r1])
}

// Trusted import of the relational theorem proved for the source and
// specialization named above.  The generated execute function preserves
// launch metadata and allocation shape; only written output cells are opaque.
#[verifier::external_body]
pub proof fn raw_batch_invariance_certificate(
    left: RawSide,
    right: RawSide,
    free: RawBatchInvarianceFree,
)
    requires raw_batch_invariance_raw_pre(left, right, free),
    ensures raw_batch_invariance_raw_post(
        raw_execute(left), raw_execute(right), free,
    ),
{
    unreachable!()
}

// BEGIN CHECKED RECTANGULAR ADAPTER

// Canonical framework values for the raw launch semantics.  Each pre-launch
// output is a generated rectangular allocation with the exact declared shape;
// the generated execute function replaces every logical output cell.
pub open spec fn row_projection_o_allocation(
    rows: nat,
    cols: nat,
) -> Tensor2D {
    Seq::new(rows, |_row: int| Seq::new(cols, |_col: int|
        generated_kernel_allocation_cell()))
}

pub open spec fn row_projection_repr(
    input_ids: IntTensor1D,
    input_weight: Tensor2D,
    V: nat,
) -> Tensor2D {
    raw_o_after(RawSide {
        ids: input_ids,
        weight: input_weight,
        o: row_projection_o_allocation(input_ids.len(), 1024),
        M: input_ids.len() as int,
        V: V as int,
    })
}

pub open spec fn row_projection_mapped_repr(
    input_ids: IntTensor1D,
    input_weight: Tensor2D,
    V: nat,
) -> Tensor2D {
    Seq::new(input_ids.len(), |_row: int|
        row_projection_repr(seq![input_ids[_row]], input_weight, V)[0])
}

// Exact source-annotation domain at the chosen projection. No domain
// policy table weakens or interprets the source predicate.
pub open spec fn row_projection_domain(
    input_ids: IntTensor1D,
    input_weight: Tensor2D,
    rows: nat,
    V: nat,
    i: nat,
) -> bool {
    let left = RawSide { ids: input_ids,
        weight: input_weight,
        o: row_projection_o_allocation(rows, 1024),
        M: rows as int,
        V: V as int };
    let right = RawSide { ids: seq![input_ids[i as int]],
        weight: input_weight,
        o: row_projection_o_allocation(1, 1024),
        M: 1,
        V: V as int };
    let free = RawBatchInvarianceFree { x: i as int };
    raw_batch_invariance_raw_pre(left, right, free)
}


// Checked rectangular instantiation of the generated raw ContractIR theorem.
pub proof fn row_projection_certificate(
    input_ids: IntTensor1D,
    input_weight: Tensor2D,
    rows: nat,
    V: nat,
    i: nat,
)
    requires
        input_ids.len() == rows,
        TS::tensor2d_shape(input_weight, V, 1024),
        row_projection_domain(input_ids, input_weight, rows, V, i),
        i < rows,
    ensures
        row_projection_repr(seq![input_ids[i as int]], input_weight, V)
            == seq![row_projection_repr(input_ids, input_weight, V)[i as int]],
{
    reveal(row_projection_domain);

    let left = RawSide {
        ids: input_ids,
        weight: input_weight,
        o: row_projection_o_allocation(rows, 1024),
        M: rows as int,
        V: V as int,
    };
    let right = RawSide {
        ids: seq![input_ids[i as int]],
        weight: input_weight,
        o: row_projection_o_allocation(1, 1024),
        M: 1,
        V: V as int,
    };
    let free = RawBatchInvarianceFree { x: i as int };
    assert(raw_batch_invariance_raw_pre(left, right, free)) by {
        reveal(row_projection_o_allocation);

        assert forall|r0: int| 0 <= r0 < 1 implies
            #[trigger] left.ids[i as int + r0]
                == right.ids[r0] by {
            assert(r0 == 0);
        };
    }
    raw_batch_invariance_certificate(left, right, free);
    let left_after = raw_execute(left);
    let right_after = raw_execute(right);
    assert(raw_batch_invariance_raw_post(left_after, right_after, free));
    reveal(raw_batch_invariance_raw_post);
    reveal(raw_execute);
    assert(left_after.M == rows as int);
    assert(right_after.M == 1);
    assert(left_after.V == V as int);
    assert(right_after.V == V as int);
    assert(0 <= i as int && i as int + 1 <= left_after.M);
    assert forall|c: int| 0 <= c < 1024 implies
        (#[trigger] left_after.o[i as int][c])
            == right_after.o[0][c] by {
        assert(0 <= 0 < ((free.x + 1) - free.x));
        assert(0 <= c < 1024);
        assert(left_after.o[free.x + 0][0 + c]
            == right_after.o[0 as int][0 + c]);
    };
    assert(left_after.o[i as int]
        =~= right_after.o[0]);
    reveal(row_projection_repr);
    assert(row_projection_repr(input_ids, input_weight, V)[i as int]
        == left_after.o[i as int]);
    assert(row_projection_repr(seq![input_ids[i as int]], input_weight, V)[0]
        == right_after.o[0]);
    assert(row_projection_repr(seq![input_ids[i as int]], input_weight, V)
        =~= seq![row_projection_repr(input_ids, input_weight, V)[i as int]]);
}

// The engine may use the mapped representation as its total row-local
// semantics.  For every valid rectangular launch, this checked theorem shows
// that it is exactly the generated raw whole-launch representation.
pub proof fn row_projection_launch_equivalence(
    input_ids: IntTensor1D,
    input_weight: Tensor2D,
    rows: nat,
    V: nat,
)
    requires
        input_ids.len() == rows,
        TS::tensor2d_shape(input_weight, V, 1024),
        forall|row: nat| row < rows ==>
            #[trigger] row_projection_domain(input_ids, input_weight, rows, V, row),
    ensures
        row_projection_repr(input_ids, input_weight, V)
            == row_projection_mapped_repr(input_ids, input_weight, V),
{
    assert forall|_row: int| 0 <= _row < rows implies
        (#[trigger] row_projection_repr(input_ids, input_weight, V)[_row])
            == row_projection_mapped_repr(input_ids, input_weight, V)[_row] by {
        row_projection_certificate(input_ids, input_weight, rows, V, _row as nat);
        reveal(row_projection_mapped_repr);
        assert(row_projection_repr(seq![input_ids[_row]], input_weight, V)[0]
            == row_projection_repr(input_ids, input_weight, V)[_row]);
    };
    assert(row_projection_repr(input_ids, input_weight, V)
        =~= row_projection_mapped_repr(input_ids, input_weight, V));
}

} // verus!
}

pub mod geometry_D_3072 {
use super::*;
verus! {
// Abstract interface for ONE fixed, separately qualified deployment.
// Alternative implementations prove this same theory; their outputs
// are not equated. See the separate implementation proof records.
// Raw ContractIR lowering for embedding_kernel

pub open spec fn raw_batch_invariance_cdiv(numerator: int, denominator: int) -> int {
    (numerator + denominator - 1) / denominator
}

pub struct RawSide {
    pub ids: Seq<int>,
    pub weight: Seq<Seq<Scalar>>,
    pub o: Seq<Seq<Scalar>>,
    pub M: int,
    pub V: int,
}

pub struct RawBatchInvarianceFree {
    pub x: int,
}


pub uninterp spec fn raw_o_cell(before: RawSide, _i0: int, _i1: int) -> Scalar;

pub open spec fn raw_o_after(before: RawSide)
    -> Seq<Seq<Scalar>>
{
    Seq::new(before.o.len(), |_i0: int| Seq::new(before.o[_i0].len(), |_i1: int| raw_o_cell(before, _i0, _i1)))
}

pub open spec fn raw_execute(before: RawSide) -> RawSide {
    RawSide {
        ids: before.ids,
        weight: before.weight,
        o: raw_o_after(before),
        M: before.M,
        V: before.V,
    }
}

pub open spec fn raw_batch_invariance_raw_pre(
    left: RawSide,
    right: RawSide,
    free: RawBatchInvarianceFree,
) -> bool {
    &&& 0 <= left.M
    &&& left.ids.len() as int == left.M
    &&& 0 <= left.V
    &&& 0 <= 3072
    &&& left.weight.len() as int == left.V
    &&& forall|_s0: int| 0 <= _s0 < left.weight.len() as int ==> (#[trigger] left.weight[_s0]).len() as int == 3072
    &&& left.o.len() as int == left.M
    &&& forall|_s0: int| 0 <= _s0 < left.o.len() as int ==> (#[trigger] left.o[_s0]).len() as int == 3072
    &&& 0 <= right.M
    &&& right.ids.len() as int == right.M
    &&& 0 <= right.V
    &&& right.weight.len() as int == right.V
    &&& forall|_s0: int| 0 <= _s0 < right.weight.len() as int ==> (#[trigger] right.weight[_s0]).len() as int == 3072
    &&& right.o.len() as int == right.M
    &&& forall|_s0: int| 0 <= _s0 < right.o.len() as int ==> (#[trigger] right.o[_s0]).len() as int == 3072
    &&& left.V == right.V
    &&& left.weight == right.weight
    &&& right.M == 1
    &&& free.x >= 0
    &&& free.x < left.M
    &&& (0 <= free.x && free.x <= (free.x + 1) && (free.x + 1) <= left.M && 0 <= 0 && 0 <= 1 && 1 <= right.M && ((free.x + 1) - free.x) == (1 - 0) && forall|_r0: int| 0 <= _r0 < ((free.x + 1) - free.x) ==> #[trigger] left.ids[free.x + _r0] == right.ids[0 + _r0])
    &&& left.ids[free.x] == right.ids[0]
}

pub open spec fn raw_batch_invariance_raw_post(
    left: RawSide,
    right: RawSide,
    free: RawBatchInvarianceFree,
) -> bool {
    &&& (0 <= free.x && free.x <= (free.x + 1) && (free.x + 1) <= left.M && 0 <= 0 && 0 <= 1 && 1 <= right.M && ((free.x + 1) - free.x) == (1 - 0) && 0 <= 0 && 0 <= 3072 && 3072 <= 3072 && 0 <= 0 && 0 <= 3072 && 3072 <= 3072 && (3072 - 0) == (3072 - 0) && forall|_r0: int, _r1: int| 0 <= _r0 < ((free.x + 1) - free.x) && 0 <= _r1 < (3072 - 0) ==> #[trigger] left.o[free.x + _r0][0 + _r1] == right.o[0 + _r0][0 + _r1])
}

// Trusted import of the relational theorem proved for the source and
// specialization named above.  The generated execute function preserves
// launch metadata and allocation shape; only written output cells are opaque.
#[verifier::external_body]
pub proof fn raw_batch_invariance_certificate(
    left: RawSide,
    right: RawSide,
    free: RawBatchInvarianceFree,
)
    requires raw_batch_invariance_raw_pre(left, right, free),
    ensures raw_batch_invariance_raw_post(
        raw_execute(left), raw_execute(right), free,
    ),
{
    unreachable!()
}

// BEGIN CHECKED RECTANGULAR ADAPTER

// Canonical framework values for the raw launch semantics.  Each pre-launch
// output is a generated rectangular allocation with the exact declared shape;
// the generated execute function replaces every logical output cell.
pub open spec fn row_projection_o_allocation(
    rows: nat,
    cols: nat,
) -> Tensor2D {
    Seq::new(rows, |_row: int| Seq::new(cols, |_col: int|
        generated_kernel_allocation_cell()))
}

pub open spec fn row_projection_repr(
    input_ids: IntTensor1D,
    input_weight: Tensor2D,
    V: nat,
) -> Tensor2D {
    raw_o_after(RawSide {
        ids: input_ids,
        weight: input_weight,
        o: row_projection_o_allocation(input_ids.len(), 3072),
        M: input_ids.len() as int,
        V: V as int,
    })
}

pub open spec fn row_projection_mapped_repr(
    input_ids: IntTensor1D,
    input_weight: Tensor2D,
    V: nat,
) -> Tensor2D {
    Seq::new(input_ids.len(), |_row: int|
        row_projection_repr(seq![input_ids[_row]], input_weight, V)[0])
}

// Exact source-annotation domain at the chosen projection. No domain
// policy table weakens or interprets the source predicate.
pub open spec fn row_projection_domain(
    input_ids: IntTensor1D,
    input_weight: Tensor2D,
    rows: nat,
    V: nat,
    i: nat,
) -> bool {
    let left = RawSide { ids: input_ids,
        weight: input_weight,
        o: row_projection_o_allocation(rows, 3072),
        M: rows as int,
        V: V as int };
    let right = RawSide { ids: seq![input_ids[i as int]],
        weight: input_weight,
        o: row_projection_o_allocation(1, 3072),
        M: 1,
        V: V as int };
    let free = RawBatchInvarianceFree { x: i as int };
    raw_batch_invariance_raw_pre(left, right, free)
}


// Checked rectangular instantiation of the generated raw ContractIR theorem.
pub proof fn row_projection_certificate(
    input_ids: IntTensor1D,
    input_weight: Tensor2D,
    rows: nat,
    V: nat,
    i: nat,
)
    requires
        input_ids.len() == rows,
        TS::tensor2d_shape(input_weight, V, 3072),
        row_projection_domain(input_ids, input_weight, rows, V, i),
        i < rows,
    ensures
        row_projection_repr(seq![input_ids[i as int]], input_weight, V)
            == seq![row_projection_repr(input_ids, input_weight, V)[i as int]],
{
    reveal(row_projection_domain);

    let left = RawSide {
        ids: input_ids,
        weight: input_weight,
        o: row_projection_o_allocation(rows, 3072),
        M: rows as int,
        V: V as int,
    };
    let right = RawSide {
        ids: seq![input_ids[i as int]],
        weight: input_weight,
        o: row_projection_o_allocation(1, 3072),
        M: 1,
        V: V as int,
    };
    let free = RawBatchInvarianceFree { x: i as int };
    assert(raw_batch_invariance_raw_pre(left, right, free)) by {
        reveal(row_projection_o_allocation);

        assert forall|r0: int| 0 <= r0 < 1 implies
            #[trigger] left.ids[i as int + r0]
                == right.ids[r0] by {
            assert(r0 == 0);
        };
    }
    raw_batch_invariance_certificate(left, right, free);
    let left_after = raw_execute(left);
    let right_after = raw_execute(right);
    assert(raw_batch_invariance_raw_post(left_after, right_after, free));
    reveal(raw_batch_invariance_raw_post);
    reveal(raw_execute);
    assert(left_after.M == rows as int);
    assert(right_after.M == 1);
    assert(left_after.V == V as int);
    assert(right_after.V == V as int);
    assert(0 <= i as int && i as int + 1 <= left_after.M);
    assert forall|c: int| 0 <= c < 3072 implies
        (#[trigger] left_after.o[i as int][c])
            == right_after.o[0][c] by {
        assert(0 <= 0 < ((free.x + 1) - free.x));
        assert(0 <= c < 3072);
        assert(left_after.o[free.x + 0][0 + c]
            == right_after.o[0 as int][0 + c]);
    };
    assert(left_after.o[i as int]
        =~= right_after.o[0]);
    reveal(row_projection_repr);
    assert(row_projection_repr(input_ids, input_weight, V)[i as int]
        == left_after.o[i as int]);
    assert(row_projection_repr(seq![input_ids[i as int]], input_weight, V)[0]
        == right_after.o[0]);
    assert(row_projection_repr(seq![input_ids[i as int]], input_weight, V)
        =~= seq![row_projection_repr(input_ids, input_weight, V)[i as int]]);
}

// The engine may use the mapped representation as its total row-local
// semantics.  For every valid rectangular launch, this checked theorem shows
// that it is exactly the generated raw whole-launch representation.
pub proof fn row_projection_launch_equivalence(
    input_ids: IntTensor1D,
    input_weight: Tensor2D,
    rows: nat,
    V: nat,
)
    requires
        input_ids.len() == rows,
        TS::tensor2d_shape(input_weight, V, 3072),
        forall|row: nat| row < rows ==>
            #[trigger] row_projection_domain(input_ids, input_weight, rows, V, row),
    ensures
        row_projection_repr(input_ids, input_weight, V)
            == row_projection_mapped_repr(input_ids, input_weight, V),
{
    assert forall|_row: int| 0 <= _row < rows implies
        (#[trigger] row_projection_repr(input_ids, input_weight, V)[_row])
            == row_projection_mapped_repr(input_ids, input_weight, V)[_row] by {
        row_projection_certificate(input_ids, input_weight, rows, V, _row as nat);
        reveal(row_projection_mapped_repr);
        assert(row_projection_repr(seq![input_ids[_row]], input_weight, V)[0]
            == row_projection_repr(input_ids, input_weight, V)[_row]);
    };
    assert(row_projection_repr(input_ids, input_weight, V)
        =~= row_projection_mapped_repr(input_ids, input_weight, V));
}

} // verus!
}

pub mod geometry_D_4096 {
use super::*;
verus! {
// Abstract interface for ONE fixed, separately qualified deployment.
// Alternative implementations prove this same theory; their outputs
// are not equated. See the separate implementation proof records.
// Raw ContractIR lowering for embedding_kernel

pub open spec fn raw_batch_invariance_cdiv(numerator: int, denominator: int) -> int {
    (numerator + denominator - 1) / denominator
}

pub struct RawSide {
    pub ids: Seq<int>,
    pub weight: Seq<Seq<Scalar>>,
    pub o: Seq<Seq<Scalar>>,
    pub M: int,
    pub V: int,
}

pub struct RawBatchInvarianceFree {
    pub x: int,
}


pub uninterp spec fn raw_o_cell(before: RawSide, _i0: int, _i1: int) -> Scalar;

pub open spec fn raw_o_after(before: RawSide)
    -> Seq<Seq<Scalar>>
{
    Seq::new(before.o.len(), |_i0: int| Seq::new(before.o[_i0].len(), |_i1: int| raw_o_cell(before, _i0, _i1)))
}

pub open spec fn raw_execute(before: RawSide) -> RawSide {
    RawSide {
        ids: before.ids,
        weight: before.weight,
        o: raw_o_after(before),
        M: before.M,
        V: before.V,
    }
}

pub open spec fn raw_batch_invariance_raw_pre(
    left: RawSide,
    right: RawSide,
    free: RawBatchInvarianceFree,
) -> bool {
    &&& 0 <= left.M
    &&& left.ids.len() as int == left.M
    &&& 0 <= left.V
    &&& 0 <= 4096
    &&& left.weight.len() as int == left.V
    &&& forall|_s0: int| 0 <= _s0 < left.weight.len() as int ==> (#[trigger] left.weight[_s0]).len() as int == 4096
    &&& left.o.len() as int == left.M
    &&& forall|_s0: int| 0 <= _s0 < left.o.len() as int ==> (#[trigger] left.o[_s0]).len() as int == 4096
    &&& 0 <= right.M
    &&& right.ids.len() as int == right.M
    &&& 0 <= right.V
    &&& right.weight.len() as int == right.V
    &&& forall|_s0: int| 0 <= _s0 < right.weight.len() as int ==> (#[trigger] right.weight[_s0]).len() as int == 4096
    &&& right.o.len() as int == right.M
    &&& forall|_s0: int| 0 <= _s0 < right.o.len() as int ==> (#[trigger] right.o[_s0]).len() as int == 4096
    &&& left.V == right.V
    &&& left.weight == right.weight
    &&& right.M == 1
    &&& free.x >= 0
    &&& free.x < left.M
    &&& (0 <= free.x && free.x <= (free.x + 1) && (free.x + 1) <= left.M && 0 <= 0 && 0 <= 1 && 1 <= right.M && ((free.x + 1) - free.x) == (1 - 0) && forall|_r0: int| 0 <= _r0 < ((free.x + 1) - free.x) ==> #[trigger] left.ids[free.x + _r0] == right.ids[0 + _r0])
    &&& left.ids[free.x] == right.ids[0]
}

pub open spec fn raw_batch_invariance_raw_post(
    left: RawSide,
    right: RawSide,
    free: RawBatchInvarianceFree,
) -> bool {
    &&& (0 <= free.x && free.x <= (free.x + 1) && (free.x + 1) <= left.M && 0 <= 0 && 0 <= 1 && 1 <= right.M && ((free.x + 1) - free.x) == (1 - 0) && 0 <= 0 && 0 <= 4096 && 4096 <= 4096 && 0 <= 0 && 0 <= 4096 && 4096 <= 4096 && (4096 - 0) == (4096 - 0) && forall|_r0: int, _r1: int| 0 <= _r0 < ((free.x + 1) - free.x) && 0 <= _r1 < (4096 - 0) ==> #[trigger] left.o[free.x + _r0][0 + _r1] == right.o[0 + _r0][0 + _r1])
}

// Trusted import of the relational theorem proved for the source and
// specialization named above.  The generated execute function preserves
// launch metadata and allocation shape; only written output cells are opaque.
#[verifier::external_body]
pub proof fn raw_batch_invariance_certificate(
    left: RawSide,
    right: RawSide,
    free: RawBatchInvarianceFree,
)
    requires raw_batch_invariance_raw_pre(left, right, free),
    ensures raw_batch_invariance_raw_post(
        raw_execute(left), raw_execute(right), free,
    ),
{
    unreachable!()
}

// BEGIN CHECKED RECTANGULAR ADAPTER

// Canonical framework values for the raw launch semantics.  Each pre-launch
// output is a generated rectangular allocation with the exact declared shape;
// the generated execute function replaces every logical output cell.
pub open spec fn row_projection_o_allocation(
    rows: nat,
    cols: nat,
) -> Tensor2D {
    Seq::new(rows, |_row: int| Seq::new(cols, |_col: int|
        generated_kernel_allocation_cell()))
}

pub open spec fn row_projection_repr(
    input_ids: IntTensor1D,
    input_weight: Tensor2D,
    V: nat,
) -> Tensor2D {
    raw_o_after(RawSide {
        ids: input_ids,
        weight: input_weight,
        o: row_projection_o_allocation(input_ids.len(), 4096),
        M: input_ids.len() as int,
        V: V as int,
    })
}

pub open spec fn row_projection_mapped_repr(
    input_ids: IntTensor1D,
    input_weight: Tensor2D,
    V: nat,
) -> Tensor2D {
    Seq::new(input_ids.len(), |_row: int|
        row_projection_repr(seq![input_ids[_row]], input_weight, V)[0])
}

// Exact source-annotation domain at the chosen projection. No domain
// policy table weakens or interprets the source predicate.
pub open spec fn row_projection_domain(
    input_ids: IntTensor1D,
    input_weight: Tensor2D,
    rows: nat,
    V: nat,
    i: nat,
) -> bool {
    let left = RawSide { ids: input_ids,
        weight: input_weight,
        o: row_projection_o_allocation(rows, 4096),
        M: rows as int,
        V: V as int };
    let right = RawSide { ids: seq![input_ids[i as int]],
        weight: input_weight,
        o: row_projection_o_allocation(1, 4096),
        M: 1,
        V: V as int };
    let free = RawBatchInvarianceFree { x: i as int };
    raw_batch_invariance_raw_pre(left, right, free)
}


// Checked rectangular instantiation of the generated raw ContractIR theorem.
pub proof fn row_projection_certificate(
    input_ids: IntTensor1D,
    input_weight: Tensor2D,
    rows: nat,
    V: nat,
    i: nat,
)
    requires
        input_ids.len() == rows,
        TS::tensor2d_shape(input_weight, V, 4096),
        row_projection_domain(input_ids, input_weight, rows, V, i),
        i < rows,
    ensures
        row_projection_repr(seq![input_ids[i as int]], input_weight, V)
            == seq![row_projection_repr(input_ids, input_weight, V)[i as int]],
{
    reveal(row_projection_domain);

    let left = RawSide {
        ids: input_ids,
        weight: input_weight,
        o: row_projection_o_allocation(rows, 4096),
        M: rows as int,
        V: V as int,
    };
    let right = RawSide {
        ids: seq![input_ids[i as int]],
        weight: input_weight,
        o: row_projection_o_allocation(1, 4096),
        M: 1,
        V: V as int,
    };
    let free = RawBatchInvarianceFree { x: i as int };
    assert(raw_batch_invariance_raw_pre(left, right, free)) by {
        reveal(row_projection_o_allocation);

        assert forall|r0: int| 0 <= r0 < 1 implies
            #[trigger] left.ids[i as int + r0]
                == right.ids[r0] by {
            assert(r0 == 0);
        };
    }
    raw_batch_invariance_certificate(left, right, free);
    let left_after = raw_execute(left);
    let right_after = raw_execute(right);
    assert(raw_batch_invariance_raw_post(left_after, right_after, free));
    reveal(raw_batch_invariance_raw_post);
    reveal(raw_execute);
    assert(left_after.M == rows as int);
    assert(right_after.M == 1);
    assert(left_after.V == V as int);
    assert(right_after.V == V as int);
    assert(0 <= i as int && i as int + 1 <= left_after.M);
    assert forall|c: int| 0 <= c < 4096 implies
        (#[trigger] left_after.o[i as int][c])
            == right_after.o[0][c] by {
        assert(0 <= 0 < ((free.x + 1) - free.x));
        assert(0 <= c < 4096);
        assert(left_after.o[free.x + 0][0 + c]
            == right_after.o[0 as int][0 + c]);
    };
    assert(left_after.o[i as int]
        =~= right_after.o[0]);
    reveal(row_projection_repr);
    assert(row_projection_repr(input_ids, input_weight, V)[i as int]
        == left_after.o[i as int]);
    assert(row_projection_repr(seq![input_ids[i as int]], input_weight, V)[0]
        == right_after.o[0]);
    assert(row_projection_repr(seq![input_ids[i as int]], input_weight, V)
        =~= seq![row_projection_repr(input_ids, input_weight, V)[i as int]]);
}

// The engine may use the mapped representation as its total row-local
// semantics.  For every valid rectangular launch, this checked theorem shows
// that it is exactly the generated raw whole-launch representation.
pub proof fn row_projection_launch_equivalence(
    input_ids: IntTensor1D,
    input_weight: Tensor2D,
    rows: nat,
    V: nat,
)
    requires
        input_ids.len() == rows,
        TS::tensor2d_shape(input_weight, V, 4096),
        forall|row: nat| row < rows ==>
            #[trigger] row_projection_domain(input_ids, input_weight, rows, V, row),
    ensures
        row_projection_repr(input_ids, input_weight, V)
            == row_projection_mapped_repr(input_ids, input_weight, V),
{
    assert forall|_row: int| 0 <= _row < rows implies
        (#[trigger] row_projection_repr(input_ids, input_weight, V)[_row])
            == row_projection_mapped_repr(input_ids, input_weight, V)[_row] by {
        row_projection_certificate(input_ids, input_weight, rows, V, _row as nat);
        reveal(row_projection_mapped_repr);
        assert(row_projection_repr(seq![input_ids[_row]], input_weight, V)[0]
            == row_projection_repr(input_ids, input_weight, V)[_row]);
    };
    assert(row_projection_repr(input_ids, input_weight, V)
        =~= row_projection_mapped_repr(input_ids, input_weight, V));
}

} // verus!
}

pub mod geometry_D_8192 {
use super::*;
verus! {
// Abstract interface for ONE fixed, separately qualified deployment.
// Alternative implementations prove this same theory; their outputs
// are not equated. See the separate implementation proof records.
// Raw ContractIR lowering for embedding_kernel

pub open spec fn raw_batch_invariance_cdiv(numerator: int, denominator: int) -> int {
    (numerator + denominator - 1) / denominator
}

pub struct RawSide {
    pub ids: Seq<int>,
    pub weight: Seq<Seq<Scalar>>,
    pub o: Seq<Seq<Scalar>>,
    pub M: int,
    pub V: int,
}

pub struct RawBatchInvarianceFree {
    pub x: int,
}


pub uninterp spec fn raw_o_cell(before: RawSide, _i0: int, _i1: int) -> Scalar;

pub open spec fn raw_o_after(before: RawSide)
    -> Seq<Seq<Scalar>>
{
    Seq::new(before.o.len(), |_i0: int| Seq::new(before.o[_i0].len(), |_i1: int| raw_o_cell(before, _i0, _i1)))
}

pub open spec fn raw_execute(before: RawSide) -> RawSide {
    RawSide {
        ids: before.ids,
        weight: before.weight,
        o: raw_o_after(before),
        M: before.M,
        V: before.V,
    }
}

pub open spec fn raw_batch_invariance_raw_pre(
    left: RawSide,
    right: RawSide,
    free: RawBatchInvarianceFree,
) -> bool {
    &&& 0 <= left.M
    &&& left.ids.len() as int == left.M
    &&& 0 <= left.V
    &&& 0 <= 8192
    &&& left.weight.len() as int == left.V
    &&& forall|_s0: int| 0 <= _s0 < left.weight.len() as int ==> (#[trigger] left.weight[_s0]).len() as int == 8192
    &&& left.o.len() as int == left.M
    &&& forall|_s0: int| 0 <= _s0 < left.o.len() as int ==> (#[trigger] left.o[_s0]).len() as int == 8192
    &&& 0 <= right.M
    &&& right.ids.len() as int == right.M
    &&& 0 <= right.V
    &&& right.weight.len() as int == right.V
    &&& forall|_s0: int| 0 <= _s0 < right.weight.len() as int ==> (#[trigger] right.weight[_s0]).len() as int == 8192
    &&& right.o.len() as int == right.M
    &&& forall|_s0: int| 0 <= _s0 < right.o.len() as int ==> (#[trigger] right.o[_s0]).len() as int == 8192
    &&& left.V == right.V
    &&& left.weight == right.weight
    &&& right.M == 1
    &&& free.x >= 0
    &&& free.x < left.M
    &&& (0 <= free.x && free.x <= (free.x + 1) && (free.x + 1) <= left.M && 0 <= 0 && 0 <= 1 && 1 <= right.M && ((free.x + 1) - free.x) == (1 - 0) && forall|_r0: int| 0 <= _r0 < ((free.x + 1) - free.x) ==> #[trigger] left.ids[free.x + _r0] == right.ids[0 + _r0])
    &&& left.ids[free.x] == right.ids[0]
}

pub open spec fn raw_batch_invariance_raw_post(
    left: RawSide,
    right: RawSide,
    free: RawBatchInvarianceFree,
) -> bool {
    &&& (0 <= free.x && free.x <= (free.x + 1) && (free.x + 1) <= left.M && 0 <= 0 && 0 <= 1 && 1 <= right.M && ((free.x + 1) - free.x) == (1 - 0) && 0 <= 0 && 0 <= 8192 && 8192 <= 8192 && 0 <= 0 && 0 <= 8192 && 8192 <= 8192 && (8192 - 0) == (8192 - 0) && forall|_r0: int, _r1: int| 0 <= _r0 < ((free.x + 1) - free.x) && 0 <= _r1 < (8192 - 0) ==> #[trigger] left.o[free.x + _r0][0 + _r1] == right.o[0 + _r0][0 + _r1])
}

// Trusted import of the relational theorem proved for the source and
// specialization named above.  The generated execute function preserves
// launch metadata and allocation shape; only written output cells are opaque.
#[verifier::external_body]
pub proof fn raw_batch_invariance_certificate(
    left: RawSide,
    right: RawSide,
    free: RawBatchInvarianceFree,
)
    requires raw_batch_invariance_raw_pre(left, right, free),
    ensures raw_batch_invariance_raw_post(
        raw_execute(left), raw_execute(right), free,
    ),
{
    unreachable!()
}

// BEGIN CHECKED RECTANGULAR ADAPTER

// Canonical framework values for the raw launch semantics.  Each pre-launch
// output is a generated rectangular allocation with the exact declared shape;
// the generated execute function replaces every logical output cell.
pub open spec fn row_projection_o_allocation(
    rows: nat,
    cols: nat,
) -> Tensor2D {
    Seq::new(rows, |_row: int| Seq::new(cols, |_col: int|
        generated_kernel_allocation_cell()))
}

pub open spec fn row_projection_repr(
    input_ids: IntTensor1D,
    input_weight: Tensor2D,
    V: nat,
) -> Tensor2D {
    raw_o_after(RawSide {
        ids: input_ids,
        weight: input_weight,
        o: row_projection_o_allocation(input_ids.len(), 8192),
        M: input_ids.len() as int,
        V: V as int,
    })
}

pub open spec fn row_projection_mapped_repr(
    input_ids: IntTensor1D,
    input_weight: Tensor2D,
    V: nat,
) -> Tensor2D {
    Seq::new(input_ids.len(), |_row: int|
        row_projection_repr(seq![input_ids[_row]], input_weight, V)[0])
}

// Exact source-annotation domain at the chosen projection. No domain
// policy table weakens or interprets the source predicate.
pub open spec fn row_projection_domain(
    input_ids: IntTensor1D,
    input_weight: Tensor2D,
    rows: nat,
    V: nat,
    i: nat,
) -> bool {
    let left = RawSide { ids: input_ids,
        weight: input_weight,
        o: row_projection_o_allocation(rows, 8192),
        M: rows as int,
        V: V as int };
    let right = RawSide { ids: seq![input_ids[i as int]],
        weight: input_weight,
        o: row_projection_o_allocation(1, 8192),
        M: 1,
        V: V as int };
    let free = RawBatchInvarianceFree { x: i as int };
    raw_batch_invariance_raw_pre(left, right, free)
}


// Checked rectangular instantiation of the generated raw ContractIR theorem.
pub proof fn row_projection_certificate(
    input_ids: IntTensor1D,
    input_weight: Tensor2D,
    rows: nat,
    V: nat,
    i: nat,
)
    requires
        input_ids.len() == rows,
        TS::tensor2d_shape(input_weight, V, 8192),
        row_projection_domain(input_ids, input_weight, rows, V, i),
        i < rows,
    ensures
        row_projection_repr(seq![input_ids[i as int]], input_weight, V)
            == seq![row_projection_repr(input_ids, input_weight, V)[i as int]],
{
    reveal(row_projection_domain);

    let left = RawSide {
        ids: input_ids,
        weight: input_weight,
        o: row_projection_o_allocation(rows, 8192),
        M: rows as int,
        V: V as int,
    };
    let right = RawSide {
        ids: seq![input_ids[i as int]],
        weight: input_weight,
        o: row_projection_o_allocation(1, 8192),
        M: 1,
        V: V as int,
    };
    let free = RawBatchInvarianceFree { x: i as int };
    assert(raw_batch_invariance_raw_pre(left, right, free)) by {
        reveal(row_projection_o_allocation);

        assert forall|r0: int| 0 <= r0 < 1 implies
            #[trigger] left.ids[i as int + r0]
                == right.ids[r0] by {
            assert(r0 == 0);
        };
    }
    raw_batch_invariance_certificate(left, right, free);
    let left_after = raw_execute(left);
    let right_after = raw_execute(right);
    assert(raw_batch_invariance_raw_post(left_after, right_after, free));
    reveal(raw_batch_invariance_raw_post);
    reveal(raw_execute);
    assert(left_after.M == rows as int);
    assert(right_after.M == 1);
    assert(left_after.V == V as int);
    assert(right_after.V == V as int);
    assert(0 <= i as int && i as int + 1 <= left_after.M);
    assert forall|c: int| 0 <= c < 8192 implies
        (#[trigger] left_after.o[i as int][c])
            == right_after.o[0][c] by {
        assert(0 <= 0 < ((free.x + 1) - free.x));
        assert(0 <= c < 8192);
        assert(left_after.o[free.x + 0][0 + c]
            == right_after.o[0 as int][0 + c]);
    };
    assert(left_after.o[i as int]
        =~= right_after.o[0]);
    reveal(row_projection_repr);
    assert(row_projection_repr(input_ids, input_weight, V)[i as int]
        == left_after.o[i as int]);
    assert(row_projection_repr(seq![input_ids[i as int]], input_weight, V)[0]
        == right_after.o[0]);
    assert(row_projection_repr(seq![input_ids[i as int]], input_weight, V)
        =~= seq![row_projection_repr(input_ids, input_weight, V)[i as int]]);
}

// The engine may use the mapped representation as its total row-local
// semantics.  For every valid rectangular launch, this checked theorem shows
// that it is exactly the generated raw whole-launch representation.
pub proof fn row_projection_launch_equivalence(
    input_ids: IntTensor1D,
    input_weight: Tensor2D,
    rows: nat,
    V: nat,
)
    requires
        input_ids.len() == rows,
        TS::tensor2d_shape(input_weight, V, 8192),
        forall|row: nat| row < rows ==>
            #[trigger] row_projection_domain(input_ids, input_weight, rows, V, row),
    ensures
        row_projection_repr(input_ids, input_weight, V)
            == row_projection_mapped_repr(input_ids, input_weight, V),
{
    assert forall|_row: int| 0 <= _row < rows implies
        (#[trigger] row_projection_repr(input_ids, input_weight, V)[_row])
            == row_projection_mapped_repr(input_ids, input_weight, V)[_row] by {
        row_projection_certificate(input_ids, input_weight, rows, V, _row as nat);
        reveal(row_projection_mapped_repr);
        assert(row_projection_repr(seq![input_ids[_row]], input_weight, V)[0]
            == row_projection_repr(input_ids, input_weight, V)[_row]);
    };
    assert(row_projection_repr(input_ids, input_weight, V)
        =~= row_projection_mapped_repr(input_ids, input_weight, V));
}

} // verus!
}

// BEGIN CHECKED GEOMETRY DISPATCH
verus! {
pub open spec fn geometry_valid(D: nat, V: nat) -> bool {
    if D == 1024 {
        true
    } else if D == 3072 {
        true
    } else if D == 4096 {
        true
    } else if D == 8192 {
        true
    } else { false }
}

pub open spec fn launch_valid(input_ids: IntTensor1D, input_weight: Tensor2D, D: nat, V: nat) -> bool {
    if D == 1024 {
        (input_ids.len() == input_ids.len())
        && (TS::tensor2d_shape(input_weight, V, 1024))
        && (forall|row: nat| row < input_ids.len() ==>
            #[trigger] geometry_D_1024::row_projection_domain(input_ids, input_weight, input_ids.len(), V, row))
    } else if D == 3072 {
        (input_ids.len() == input_ids.len())
        && (TS::tensor2d_shape(input_weight, V, 3072))
        && (forall|row: nat| row < input_ids.len() ==>
            #[trigger] geometry_D_3072::row_projection_domain(input_ids, input_weight, input_ids.len(), V, row))
    } else if D == 4096 {
        (input_ids.len() == input_ids.len())
        && (TS::tensor2d_shape(input_weight, V, 4096))
        && (forall|row: nat| row < input_ids.len() ==>
            #[trigger] geometry_D_4096::row_projection_domain(input_ids, input_weight, input_ids.len(), V, row))
    } else if D == 8192 {
        (input_ids.len() == input_ids.len())
        && (TS::tensor2d_shape(input_weight, V, 8192))
        && (forall|row: nat| row < input_ids.len() ==>
            #[trigger] geometry_D_8192::row_projection_domain(input_ids, input_weight, input_ids.len(), V, row))
    } else { false }
}

pub open spec fn raw_output(input_ids: IntTensor1D, input_weight: Tensor2D, D: nat, V: nat) -> Option<Tensor2D> {
    if D == 1024 {
        Some(geometry_D_1024::row_projection_repr(input_ids, input_weight, V))
    } else if D == 3072 {
        Some(geometry_D_3072::row_projection_repr(input_ids, input_weight, V))
    } else if D == 4096 {
        Some(geometry_D_4096::row_projection_repr(input_ids, input_weight, V))
    } else if D == 8192 {
        Some(geometry_D_8192::row_projection_repr(input_ids, input_weight, V))
    } else { None }
}

pub open spec fn mapped_output(input_ids: IntTensor1D, input_weight: Tensor2D, D: nat, V: nat) -> Option<Tensor2D> {
    if D == 1024 {
        Some(geometry_D_1024::row_projection_mapped_repr(input_ids, input_weight, V))
    } else if D == 3072 {
        Some(geometry_D_3072::row_projection_mapped_repr(input_ids, input_weight, V))
    } else if D == 4096 {
        Some(geometry_D_4096::row_projection_mapped_repr(input_ids, input_weight, V))
    } else if D == 8192 {
        Some(geometry_D_8192::row_projection_mapped_repr(input_ids, input_weight, V))
    } else { None }
}

// A public row map independent of the generated geometry module names.
pub open spec fn row_mapped_output(input_ids: IntTensor1D, input_weight: Tensor2D, D: nat, V: nat) -> Option<Tensor2D> {
    if geometry_valid(D, V) { Some(Seq::new(input_ids.len(), |row: int| raw_output(seq![input_ids[row]], input_weight, D, V).unwrap()[0])) } else { None }
}

pub proof fn checked_row_map(input_ids: IntTensor1D, input_weight: Tensor2D, D: nat, V: nat)
    ensures mapped_output(input_ids, input_weight, D, V) == row_mapped_output(input_ids, input_weight, D, V),
{
    let mapped = mapped_output(input_ids, input_weight, D, V).unwrap();
    let row_map = row_mapped_output(input_ids, input_weight, D, V).unwrap();
    if D == 1024 {
        assert(mapped =~= row_map);
    } else if D == 3072 {
        assert(mapped =~= row_map);
    } else if D == 4096 {
        assert(mapped =~= row_map);
    } else if D == 8192 {
        assert(mapped =~= row_map);
    } else {  }
}

pub proof fn checked_launch_equivalence(input_ids: IntTensor1D, input_weight: Tensor2D, D: nat, V: nat)
    requires launch_valid(input_ids, input_weight, D, V),
    ensures geometry_valid(D, V),
        raw_output(input_ids, input_weight, D, V).is_some(),
        raw_output(input_ids, input_weight, D, V) == mapped_output(input_ids, input_weight, D, V),
        raw_output(input_ids, input_weight, D, V) == row_mapped_output(input_ids, input_weight, D, V),
{
    checked_row_map(input_ids, input_weight, D, V);
    if D == 1024 {
        geometry_D_1024::row_projection_launch_equivalence(input_ids, input_weight, input_ids.len(), V);
    } else if D == 3072 {
        geometry_D_3072::row_projection_launch_equivalence(input_ids, input_weight, input_ids.len(), V);
    } else if D == 4096 {
        geometry_D_4096::row_projection_launch_equivalence(input_ids, input_weight, input_ids.len(), V);
    } else if D == 8192 {
        geometry_D_8192::row_projection_launch_equivalence(input_ids, input_weight, input_ids.len(), V);
    } else { assert(false); }
}
} // verus!
