// @generated by scripts/verification/verify_mutation_interfaces.py; DO NOT EDIT.
#![allow(non_snake_case)]
use vstd::prelude::*;
use crate::{boundary::scalar::{Scalar}, proof::tensor::types::{Tensor2D, IntTensor1D}};

pub mod geometry_KVD_512 {
use super::*;
verus! {
// Abstract interface for ONE fixed, separately qualified deployment.
// Alternative implementations prove this same theory; their outputs
// are not equated. See the separate implementation proof records.
// Exact temporal ContractIR lowering for store_cache_kernel

pub open spec fn raw_exact_effect_cdiv(numerator: int, denominator: int) -> int {
    (numerator + denominator - 1) / denominator
}

#[verifier::external_body]
#[verifier::ext_equal]
pub struct RawDType {
    _private: (),
}

pub struct RawSide {
    pub x: Seq<Seq<Scalar>>,
    pub slot_mapping: Seq<int>,
    pub cache: Seq<Seq<Scalar>>,
    pub M: int,
    pub NUM_SLOTS: int,
    pub __element_dtype_cache: RawDType,
    pub __element_dtype_slot_mapping: RawDType,
    pub __element_dtype_x: RawDType,
}

pub uninterp spec fn raw_cache_cell(before: RawSide, _i0: int, _i1: int) -> Scalar;

pub open spec fn raw_cache_after(before: RawSide)
    -> Seq<Seq<Scalar>>
{
    Seq::new(before.cache.len(), |_i0: int| Seq::new(before.cache[_i0].len(), |_i1: int| raw_cache_cell(before, _i0, _i1)))
}

pub open spec fn raw_execute(before: RawSide) -> RawSide {
    RawSide {
        x: before.x,
        slot_mapping: before.slot_mapping,
        cache: raw_cache_after(before),
        M: before.M,
        NUM_SLOTS: before.NUM_SLOTS,
        __element_dtype_cache: before.__element_dtype_cache,
        __element_dtype_slot_mapping: before.__element_dtype_slot_mapping,
        __element_dtype_x: before.__element_dtype_x,
    }
}

pub struct RawExactEffectFree {}

pub open spec fn raw_exact_effect_quantified_0(before: RawSide, after: RawSide,
    free: RawExactEffectFree, _q0: int) -> bool {
    (((_q0 >= 0) && (_q0 < before.M)) ==> ((before.slot_mapping[_q0] >= (0 - 1)) && (before.slot_mapping[_q0] < before.NUM_SLOTS)))
}

pub open spec fn raw_exact_effect_quantified_1(before: RawSide, after: RawSide,
    free: RawExactEffectFree, _q0: int, _q1: int) -> bool {
    (((_q0 >= 0) && (_q0 < before.M) && (_q1 >= 0) && (_q1 < before.M) && (before.slot_mapping[_q0] >= 0) && (before.slot_mapping[_q0] == before.slot_mapping[_q1])) ==> (_q0 == _q1))
}

pub open spec fn raw_exact_effect_quantified_2(before: RawSide, after: RawSide,
    free: RawExactEffectFree, _q0: int) -> bool {
    (((_q0 >= 0) && (_q0 < before.M) && (before.slot_mapping[_q0] >= 0)) ==> (0 <= before.slot_mapping[_q0] <= (before.slot_mapping[_q0] + 1) <= before.NUM_SLOTS && 0 <= _q0 <= (_q0 + 1) <= before.M && ((before.slot_mapping[_q0] + 1) - before.slot_mapping[_q0]) == ((_q0 + 1) - _q0) && 0 <= 0 <= 512 <= 512 && 0 <= 0 <= 512 <= 512 && (512 - 0) == (512 - 0) && (forall|_r0: int, _r1: int| #[trigger] raw_exact_effect_region_0(before, after, free, _q0, _r0, _r1))))
}

pub open spec fn raw_exact_effect_quantified_3(before: RawSide, after: RawSide,
    free: RawExactEffectFree, _q0: int, _q1: int) -> bool {
    (((_q1 >= 0) && (_q1 < before.M)) ==> !((before.slot_mapping[_q1] == _q0)))
}

pub open spec fn raw_exact_effect_quantified_4(before: RawSide, after: RawSide,
    free: RawExactEffectFree, _q0: int) -> bool {
    (((_q0 >= 0) && (_q0 < before.NUM_SLOTS) && (forall|_q1: int| #[trigger] raw_exact_effect_quantified_3(before, after, free, _q0, _q1))) ==> (0 <= _q0 <= (_q0 + 1) <= before.NUM_SLOTS && 0 <= _q0 <= (_q0 + 1) <= before.NUM_SLOTS && ((_q0 + 1) - _q0) == ((_q0 + 1) - _q0) && 0 <= 0 <= 512 <= 512 && 0 <= 0 <= 512 <= 512 && (512 - 0) == (512 - 0) && (forall|_r0: int, _r1: int| #[trigger] raw_exact_effect_region_1(before, after, free, _q0, _r0, _r1))))
}


pub open spec fn raw_exact_effect_region_0(before: RawSide, after: RawSide,
    free: RawExactEffectFree, _q0: int, _r0: int, _r1: int) -> bool {
    0 <= _r0 < ((before.slot_mapping[_q0] + 1) - before.slot_mapping[_q0]) && 0 <= _r1 < (512 - 0) ==> after.cache[before.slot_mapping[_q0] + _r0][0 + _r1] == before.x[_q0 + _r0][0 + _r1]
}

pub open spec fn raw_exact_effect_region_1(before: RawSide, after: RawSide,
    free: RawExactEffectFree, _q0: int, _r0: int, _r1: int) -> bool {
    0 <= _r0 < ((_q0 + 1) - _q0) && 0 <= _r1 < (512 - 0) ==> after.cache[_q0 + _r0][0 + _r1] == before.cache[_q0 + _r0][0 + _r1]
}

pub uninterp spec fn raw_exact_effect_external_obligation_0(before: RawSide, free: RawExactEffectFree) -> bool;
pub uninterp spec fn raw_exact_effect_external_obligation_1(before: RawSide, free: RawExactEffectFree) -> bool;
pub uninterp spec fn raw_exact_effect_external_obligation_2(before: RawSide, free: RawExactEffectFree) -> bool;

pub open spec fn raw_exact_effect_raw_pre(before: RawSide, free: RawExactEffectFree) -> bool {
    let after = before;
    &&& 0 <= before.M
    &&& 0 <= 512
    &&& before.x.len() as int == before.M
    &&& forall|_s0: int| 0 <= _s0 < before.x.len() as int ==> (#[trigger] before.x[_s0]).len() as int == 512
    &&& 0 <= before.M
    &&& before.slot_mapping.len() as int == before.M
    &&& 0 <= before.NUM_SLOTS
    &&& 0 <= 512
    &&& before.cache.len() as int == before.NUM_SLOTS
    &&& forall|_s0: int| 0 <= _s0 < before.cache.len() as int ==> (#[trigger] before.cache[_s0]).len() as int == 512
    &&& (before.M >= 0)
    &&& (before.NUM_SLOTS > 0)
    &&& (512 > 0)
    &&& (before.__element_dtype_x == before.__element_dtype_cache)
    &&& (forall|_q0: int| #[trigger] raw_exact_effect_quantified_0(before, after, free, _q0))
    &&& (forall|_q0: int, _q1: int| #[trigger] raw_exact_effect_quantified_1(before, after, free, _q0, _q1))
    &&& raw_exact_effect_external_obligation_0(before, free)
    &&& raw_exact_effect_external_obligation_1(before, free)
    &&& raw_exact_effect_external_obligation_2(before, free)
}

pub open spec fn raw_exact_effect_raw_post(before: RawSide, after: RawSide, free: RawExactEffectFree) -> bool {
    &&& (forall|_q0: int| #[trigger] raw_exact_effect_quantified_2(before, after, free, _q0))
    &&& (forall|_q0: int| #[trigger] raw_exact_effect_quantified_4(before, after, free, _q0))
}

// Trusted import of the proved copy/frame theorem, retaining all premises.
// This is about one execution's before/after states, not batch invariance.
#[verifier::external_body]
pub proof fn raw_exact_effect_certificate(before: RawSide, free: RawExactEffectFree)
    requires raw_exact_effect_raw_pre(before, free),
    ensures raw_exact_effect_raw_post(before, raw_execute(before), free),
{
    unreachable!()
}

// BEGIN CHECKED MUTATION ADAPTER
// Canonical physical dtype identities for a fixed deployed float/int interface.
// Their physical interpretation is required by the raw correspondence premises.
pub uninterp spec fn float_dtype() -> RawDType;
pub uninterp spec fn int_dtype() -> RawDType;

pub open spec fn before(rows: Tensor2D, cache: Tensor2D, slots: IntTensor1D) -> RawSide {
    RawSide {
        x: rows, cache: cache, slot_mapping: slots,
        M: rows.len() as int, NUM_SLOTS: cache.len() as int,
        __element_dtype_x: float_dtype(), __element_dtype_cache: float_dtype(),
        __element_dtype_slot_mapping: int_dtype(),
    }
}

pub open spec fn domain(rows: Tensor2D, cache: Tensor2D, slots: IntTensor1D) -> bool {
    raw_exact_effect_raw_pre(before(rows, cache, slots), RawExactEffectFree {})
}

pub open spec fn output(rows: Tensor2D, cache: Tensor2D, slots: IntTensor1D) -> Tensor2D {
    raw_execute(before(rows, cache, slots)).cache
}

pub proof fn checked_copy(rows: Tensor2D, cache: Tensor2D, slots: IntTensor1D, i: int)
    requires domain(rows, cache, slots), 0 <= i < rows.len(), slots[i] >= 0,
    ensures 0 <= slots[i] < cache.len(), output(rows, cache, slots)[slots[i]] == rows[i],
{
    let launch = before(rows, cache, slots);
    let free = RawExactEffectFree {};
    raw_exact_effect_certificate(launch, free);
    let after = raw_execute(launch);
    assert(raw_exact_effect_quantified_2(launch, after, free, i));
    assert forall|c: int| 0 <= c < 512 implies
        #[trigger] after.cache[slots[i]][c] == rows[i][c] by {
        assert(raw_exact_effect_region_0(launch, after, free, i, 0, c));
    }
    assert(after.cache[slots[i]] =~= rows[i]);
}

pub proof fn checked_frame(rows: Tensor2D, cache: Tensor2D, slots: IntTensor1D, s: int)
    requires domain(rows, cache, slots), 0 <= s < cache.len(),
        forall|i: int| 0 <= i < slots.len() ==> (#[trigger] slots[i]) != s,
    ensures output(rows, cache, slots)[s] == cache[s],
{
    let launch = before(rows, cache, slots);
    let free = RawExactEffectFree {};
    raw_exact_effect_certificate(launch, free);
    let after = raw_execute(launch);
    assert forall|i: int| #[trigger] raw_exact_effect_quantified_3(launch, after, free, s, i) by {}
    assert(raw_exact_effect_quantified_4(launch, after, free, s));
    assert forall|c: int| 0 <= c < 512 implies
        #[trigger] after.cache[s][c] == cache[s][c] by {
        assert(raw_exact_effect_region_1(launch, after, free, s, 0, c));
    }
    assert(after.cache[s] =~= cache[s]);
}
// END CHECKED MUTATION ADAPTER

} // verus!
}

pub mod geometry_KVD_1024 {
use super::*;
verus! {
// Abstract interface for ONE fixed, separately qualified deployment.
// Alternative implementations prove this same theory; their outputs
// are not equated. See the separate implementation proof records.
// Exact temporal ContractIR lowering for store_cache_kernel

pub open spec fn raw_exact_effect_cdiv(numerator: int, denominator: int) -> int {
    (numerator + denominator - 1) / denominator
}

#[verifier::external_body]
#[verifier::ext_equal]
pub struct RawDType {
    _private: (),
}

pub struct RawSide {
    pub x: Seq<Seq<Scalar>>,
    pub slot_mapping: Seq<int>,
    pub cache: Seq<Seq<Scalar>>,
    pub M: int,
    pub NUM_SLOTS: int,
    pub __element_dtype_cache: RawDType,
    pub __element_dtype_slot_mapping: RawDType,
    pub __element_dtype_x: RawDType,
}

pub uninterp spec fn raw_cache_cell(before: RawSide, _i0: int, _i1: int) -> Scalar;

pub open spec fn raw_cache_after(before: RawSide)
    -> Seq<Seq<Scalar>>
{
    Seq::new(before.cache.len(), |_i0: int| Seq::new(before.cache[_i0].len(), |_i1: int| raw_cache_cell(before, _i0, _i1)))
}

pub open spec fn raw_execute(before: RawSide) -> RawSide {
    RawSide {
        x: before.x,
        slot_mapping: before.slot_mapping,
        cache: raw_cache_after(before),
        M: before.M,
        NUM_SLOTS: before.NUM_SLOTS,
        __element_dtype_cache: before.__element_dtype_cache,
        __element_dtype_slot_mapping: before.__element_dtype_slot_mapping,
        __element_dtype_x: before.__element_dtype_x,
    }
}

pub struct RawExactEffectFree {}

pub open spec fn raw_exact_effect_quantified_0(before: RawSide, after: RawSide,
    free: RawExactEffectFree, _q0: int) -> bool {
    (((_q0 >= 0) && (_q0 < before.M)) ==> ((before.slot_mapping[_q0] >= (0 - 1)) && (before.slot_mapping[_q0] < before.NUM_SLOTS)))
}

pub open spec fn raw_exact_effect_quantified_1(before: RawSide, after: RawSide,
    free: RawExactEffectFree, _q0: int, _q1: int) -> bool {
    (((_q0 >= 0) && (_q0 < before.M) && (_q1 >= 0) && (_q1 < before.M) && (before.slot_mapping[_q0] >= 0) && (before.slot_mapping[_q0] == before.slot_mapping[_q1])) ==> (_q0 == _q1))
}

pub open spec fn raw_exact_effect_quantified_2(before: RawSide, after: RawSide,
    free: RawExactEffectFree, _q0: int) -> bool {
    (((_q0 >= 0) && (_q0 < before.M) && (before.slot_mapping[_q0] >= 0)) ==> (0 <= before.slot_mapping[_q0] <= (before.slot_mapping[_q0] + 1) <= before.NUM_SLOTS && 0 <= _q0 <= (_q0 + 1) <= before.M && ((before.slot_mapping[_q0] + 1) - before.slot_mapping[_q0]) == ((_q0 + 1) - _q0) && 0 <= 0 <= 1024 <= 1024 && 0 <= 0 <= 1024 <= 1024 && (1024 - 0) == (1024 - 0) && (forall|_r0: int, _r1: int| #[trigger] raw_exact_effect_region_0(before, after, free, _q0, _r0, _r1))))
}

pub open spec fn raw_exact_effect_quantified_3(before: RawSide, after: RawSide,
    free: RawExactEffectFree, _q0: int, _q1: int) -> bool {
    (((_q1 >= 0) && (_q1 < before.M)) ==> !((before.slot_mapping[_q1] == _q0)))
}

pub open spec fn raw_exact_effect_quantified_4(before: RawSide, after: RawSide,
    free: RawExactEffectFree, _q0: int) -> bool {
    (((_q0 >= 0) && (_q0 < before.NUM_SLOTS) && (forall|_q1: int| #[trigger] raw_exact_effect_quantified_3(before, after, free, _q0, _q1))) ==> (0 <= _q0 <= (_q0 + 1) <= before.NUM_SLOTS && 0 <= _q0 <= (_q0 + 1) <= before.NUM_SLOTS && ((_q0 + 1) - _q0) == ((_q0 + 1) - _q0) && 0 <= 0 <= 1024 <= 1024 && 0 <= 0 <= 1024 <= 1024 && (1024 - 0) == (1024 - 0) && (forall|_r0: int, _r1: int| #[trigger] raw_exact_effect_region_1(before, after, free, _q0, _r0, _r1))))
}


pub open spec fn raw_exact_effect_region_0(before: RawSide, after: RawSide,
    free: RawExactEffectFree, _q0: int, _r0: int, _r1: int) -> bool {
    0 <= _r0 < ((before.slot_mapping[_q0] + 1) - before.slot_mapping[_q0]) && 0 <= _r1 < (1024 - 0) ==> after.cache[before.slot_mapping[_q0] + _r0][0 + _r1] == before.x[_q0 + _r0][0 + _r1]
}

pub open spec fn raw_exact_effect_region_1(before: RawSide, after: RawSide,
    free: RawExactEffectFree, _q0: int, _r0: int, _r1: int) -> bool {
    0 <= _r0 < ((_q0 + 1) - _q0) && 0 <= _r1 < (1024 - 0) ==> after.cache[_q0 + _r0][0 + _r1] == before.cache[_q0 + _r0][0 + _r1]
}

pub uninterp spec fn raw_exact_effect_external_obligation_0(before: RawSide, free: RawExactEffectFree) -> bool;
pub uninterp spec fn raw_exact_effect_external_obligation_1(before: RawSide, free: RawExactEffectFree) -> bool;
pub uninterp spec fn raw_exact_effect_external_obligation_2(before: RawSide, free: RawExactEffectFree) -> bool;

pub open spec fn raw_exact_effect_raw_pre(before: RawSide, free: RawExactEffectFree) -> bool {
    let after = before;
    &&& 0 <= before.M
    &&& 0 <= 1024
    &&& before.x.len() as int == before.M
    &&& forall|_s0: int| 0 <= _s0 < before.x.len() as int ==> (#[trigger] before.x[_s0]).len() as int == 1024
    &&& 0 <= before.M
    &&& before.slot_mapping.len() as int == before.M
    &&& 0 <= before.NUM_SLOTS
    &&& 0 <= 1024
    &&& before.cache.len() as int == before.NUM_SLOTS
    &&& forall|_s0: int| 0 <= _s0 < before.cache.len() as int ==> (#[trigger] before.cache[_s0]).len() as int == 1024
    &&& (before.M >= 0)
    &&& (before.NUM_SLOTS > 0)
    &&& (1024 > 0)
    &&& (before.__element_dtype_x == before.__element_dtype_cache)
    &&& (forall|_q0: int| #[trigger] raw_exact_effect_quantified_0(before, after, free, _q0))
    &&& (forall|_q0: int, _q1: int| #[trigger] raw_exact_effect_quantified_1(before, after, free, _q0, _q1))
    &&& raw_exact_effect_external_obligation_0(before, free)
    &&& raw_exact_effect_external_obligation_1(before, free)
    &&& raw_exact_effect_external_obligation_2(before, free)
}

pub open spec fn raw_exact_effect_raw_post(before: RawSide, after: RawSide, free: RawExactEffectFree) -> bool {
    &&& (forall|_q0: int| #[trigger] raw_exact_effect_quantified_2(before, after, free, _q0))
    &&& (forall|_q0: int| #[trigger] raw_exact_effect_quantified_4(before, after, free, _q0))
}

// Trusted import of the proved copy/frame theorem, retaining all premises.
// This is about one execution's before/after states, not batch invariance.
#[verifier::external_body]
pub proof fn raw_exact_effect_certificate(before: RawSide, free: RawExactEffectFree)
    requires raw_exact_effect_raw_pre(before, free),
    ensures raw_exact_effect_raw_post(before, raw_execute(before), free),
{
    unreachable!()
}

// BEGIN CHECKED MUTATION ADAPTER
// Canonical physical dtype identities for a fixed deployed float/int interface.
// Their physical interpretation is required by the raw correspondence premises.
pub uninterp spec fn float_dtype() -> RawDType;
pub uninterp spec fn int_dtype() -> RawDType;

pub open spec fn before(rows: Tensor2D, cache: Tensor2D, slots: IntTensor1D) -> RawSide {
    RawSide {
        x: rows, cache: cache, slot_mapping: slots,
        M: rows.len() as int, NUM_SLOTS: cache.len() as int,
        __element_dtype_x: float_dtype(), __element_dtype_cache: float_dtype(),
        __element_dtype_slot_mapping: int_dtype(),
    }
}

pub open spec fn domain(rows: Tensor2D, cache: Tensor2D, slots: IntTensor1D) -> bool {
    raw_exact_effect_raw_pre(before(rows, cache, slots), RawExactEffectFree {})
}

pub open spec fn output(rows: Tensor2D, cache: Tensor2D, slots: IntTensor1D) -> Tensor2D {
    raw_execute(before(rows, cache, slots)).cache
}

pub proof fn checked_copy(rows: Tensor2D, cache: Tensor2D, slots: IntTensor1D, i: int)
    requires domain(rows, cache, slots), 0 <= i < rows.len(), slots[i] >= 0,
    ensures 0 <= slots[i] < cache.len(), output(rows, cache, slots)[slots[i]] == rows[i],
{
    let launch = before(rows, cache, slots);
    let free = RawExactEffectFree {};
    raw_exact_effect_certificate(launch, free);
    let after = raw_execute(launch);
    assert(raw_exact_effect_quantified_2(launch, after, free, i));
    assert forall|c: int| 0 <= c < 1024 implies
        #[trigger] after.cache[slots[i]][c] == rows[i][c] by {
        assert(raw_exact_effect_region_0(launch, after, free, i, 0, c));
    }
    assert(after.cache[slots[i]] =~= rows[i]);
}

pub proof fn checked_frame(rows: Tensor2D, cache: Tensor2D, slots: IntTensor1D, s: int)
    requires domain(rows, cache, slots), 0 <= s < cache.len(),
        forall|i: int| 0 <= i < slots.len() ==> (#[trigger] slots[i]) != s,
    ensures output(rows, cache, slots)[s] == cache[s],
{
    let launch = before(rows, cache, slots);
    let free = RawExactEffectFree {};
    raw_exact_effect_certificate(launch, free);
    let after = raw_execute(launch);
    assert forall|i: int| #[trigger] raw_exact_effect_quantified_3(launch, after, free, s, i) by {}
    assert(raw_exact_effect_quantified_4(launch, after, free, s));
    assert forall|c: int| 0 <= c < 1024 implies
        #[trigger] after.cache[s][c] == cache[s][c] by {
        assert(raw_exact_effect_region_1(launch, after, free, s, 0, c));
    }
    assert(after.cache[s] =~= cache[s]);
}
// END CHECKED MUTATION ADAPTER

} // verus!
}

pub mod geometry_KVD_2048 {
use super::*;
verus! {
// Abstract interface for ONE fixed, separately qualified deployment.
// Alternative implementations prove this same theory; their outputs
// are not equated. See the separate implementation proof records.
// Exact temporal ContractIR lowering for store_cache_kernel

pub open spec fn raw_exact_effect_cdiv(numerator: int, denominator: int) -> int {
    (numerator + denominator - 1) / denominator
}

#[verifier::external_body]
#[verifier::ext_equal]
pub struct RawDType {
    _private: (),
}

pub struct RawSide {
    pub x: Seq<Seq<Scalar>>,
    pub slot_mapping: Seq<int>,
    pub cache: Seq<Seq<Scalar>>,
    pub M: int,
    pub NUM_SLOTS: int,
    pub __element_dtype_cache: RawDType,
    pub __element_dtype_slot_mapping: RawDType,
    pub __element_dtype_x: RawDType,
}

pub uninterp spec fn raw_cache_cell(before: RawSide, _i0: int, _i1: int) -> Scalar;

pub open spec fn raw_cache_after(before: RawSide)
    -> Seq<Seq<Scalar>>
{
    Seq::new(before.cache.len(), |_i0: int| Seq::new(before.cache[_i0].len(), |_i1: int| raw_cache_cell(before, _i0, _i1)))
}

pub open spec fn raw_execute(before: RawSide) -> RawSide {
    RawSide {
        x: before.x,
        slot_mapping: before.slot_mapping,
        cache: raw_cache_after(before),
        M: before.M,
        NUM_SLOTS: before.NUM_SLOTS,
        __element_dtype_cache: before.__element_dtype_cache,
        __element_dtype_slot_mapping: before.__element_dtype_slot_mapping,
        __element_dtype_x: before.__element_dtype_x,
    }
}

pub struct RawExactEffectFree {}

pub open spec fn raw_exact_effect_quantified_0(before: RawSide, after: RawSide,
    free: RawExactEffectFree, _q0: int) -> bool {
    (((_q0 >= 0) && (_q0 < before.M)) ==> ((before.slot_mapping[_q0] >= (0 - 1)) && (before.slot_mapping[_q0] < before.NUM_SLOTS)))
}

pub open spec fn raw_exact_effect_quantified_1(before: RawSide, after: RawSide,
    free: RawExactEffectFree, _q0: int, _q1: int) -> bool {
    (((_q0 >= 0) && (_q0 < before.M) && (_q1 >= 0) && (_q1 < before.M) && (before.slot_mapping[_q0] >= 0) && (before.slot_mapping[_q0] == before.slot_mapping[_q1])) ==> (_q0 == _q1))
}

pub open spec fn raw_exact_effect_quantified_2(before: RawSide, after: RawSide,
    free: RawExactEffectFree, _q0: int) -> bool {
    (((_q0 >= 0) && (_q0 < before.M) && (before.slot_mapping[_q0] >= 0)) ==> (0 <= before.slot_mapping[_q0] <= (before.slot_mapping[_q0] + 1) <= before.NUM_SLOTS && 0 <= _q0 <= (_q0 + 1) <= before.M && ((before.slot_mapping[_q0] + 1) - before.slot_mapping[_q0]) == ((_q0 + 1) - _q0) && 0 <= 0 <= 2048 <= 2048 && 0 <= 0 <= 2048 <= 2048 && (2048 - 0) == (2048 - 0) && (forall|_r0: int, _r1: int| #[trigger] raw_exact_effect_region_0(before, after, free, _q0, _r0, _r1))))
}

pub open spec fn raw_exact_effect_quantified_3(before: RawSide, after: RawSide,
    free: RawExactEffectFree, _q0: int, _q1: int) -> bool {
    (((_q1 >= 0) && (_q1 < before.M)) ==> !((before.slot_mapping[_q1] == _q0)))
}

pub open spec fn raw_exact_effect_quantified_4(before: RawSide, after: RawSide,
    free: RawExactEffectFree, _q0: int) -> bool {
    (((_q0 >= 0) && (_q0 < before.NUM_SLOTS) && (forall|_q1: int| #[trigger] raw_exact_effect_quantified_3(before, after, free, _q0, _q1))) ==> (0 <= _q0 <= (_q0 + 1) <= before.NUM_SLOTS && 0 <= _q0 <= (_q0 + 1) <= before.NUM_SLOTS && ((_q0 + 1) - _q0) == ((_q0 + 1) - _q0) && 0 <= 0 <= 2048 <= 2048 && 0 <= 0 <= 2048 <= 2048 && (2048 - 0) == (2048 - 0) && (forall|_r0: int, _r1: int| #[trigger] raw_exact_effect_region_1(before, after, free, _q0, _r0, _r1))))
}


pub open spec fn raw_exact_effect_region_0(before: RawSide, after: RawSide,
    free: RawExactEffectFree, _q0: int, _r0: int, _r1: int) -> bool {
    0 <= _r0 < ((before.slot_mapping[_q0] + 1) - before.slot_mapping[_q0]) && 0 <= _r1 < (2048 - 0) ==> after.cache[before.slot_mapping[_q0] + _r0][0 + _r1] == before.x[_q0 + _r0][0 + _r1]
}

pub open spec fn raw_exact_effect_region_1(before: RawSide, after: RawSide,
    free: RawExactEffectFree, _q0: int, _r0: int, _r1: int) -> bool {
    0 <= _r0 < ((_q0 + 1) - _q0) && 0 <= _r1 < (2048 - 0) ==> after.cache[_q0 + _r0][0 + _r1] == before.cache[_q0 + _r0][0 + _r1]
}

pub uninterp spec fn raw_exact_effect_external_obligation_0(before: RawSide, free: RawExactEffectFree) -> bool;
pub uninterp spec fn raw_exact_effect_external_obligation_1(before: RawSide, free: RawExactEffectFree) -> bool;
pub uninterp spec fn raw_exact_effect_external_obligation_2(before: RawSide, free: RawExactEffectFree) -> bool;

pub open spec fn raw_exact_effect_raw_pre(before: RawSide, free: RawExactEffectFree) -> bool {
    let after = before;
    &&& 0 <= before.M
    &&& 0 <= 2048
    &&& before.x.len() as int == before.M
    &&& forall|_s0: int| 0 <= _s0 < before.x.len() as int ==> (#[trigger] before.x[_s0]).len() as int == 2048
    &&& 0 <= before.M
    &&& before.slot_mapping.len() as int == before.M
    &&& 0 <= before.NUM_SLOTS
    &&& 0 <= 2048
    &&& before.cache.len() as int == before.NUM_SLOTS
    &&& forall|_s0: int| 0 <= _s0 < before.cache.len() as int ==> (#[trigger] before.cache[_s0]).len() as int == 2048
    &&& (before.M >= 0)
    &&& (before.NUM_SLOTS > 0)
    &&& (2048 > 0)
    &&& (before.__element_dtype_x == before.__element_dtype_cache)
    &&& (forall|_q0: int| #[trigger] raw_exact_effect_quantified_0(before, after, free, _q0))
    &&& (forall|_q0: int, _q1: int| #[trigger] raw_exact_effect_quantified_1(before, after, free, _q0, _q1))
    &&& raw_exact_effect_external_obligation_0(before, free)
    &&& raw_exact_effect_external_obligation_1(before, free)
    &&& raw_exact_effect_external_obligation_2(before, free)
}

pub open spec fn raw_exact_effect_raw_post(before: RawSide, after: RawSide, free: RawExactEffectFree) -> bool {
    &&& (forall|_q0: int| #[trigger] raw_exact_effect_quantified_2(before, after, free, _q0))
    &&& (forall|_q0: int| #[trigger] raw_exact_effect_quantified_4(before, after, free, _q0))
}

// Trusted import of the proved copy/frame theorem, retaining all premises.
// This is about one execution's before/after states, not batch invariance.
#[verifier::external_body]
pub proof fn raw_exact_effect_certificate(before: RawSide, free: RawExactEffectFree)
    requires raw_exact_effect_raw_pre(before, free),
    ensures raw_exact_effect_raw_post(before, raw_execute(before), free),
{
    unreachable!()
}

// BEGIN CHECKED MUTATION ADAPTER
// Canonical physical dtype identities for a fixed deployed float/int interface.
// Their physical interpretation is required by the raw correspondence premises.
pub uninterp spec fn float_dtype() -> RawDType;
pub uninterp spec fn int_dtype() -> RawDType;

pub open spec fn before(rows: Tensor2D, cache: Tensor2D, slots: IntTensor1D) -> RawSide {
    RawSide {
        x: rows, cache: cache, slot_mapping: slots,
        M: rows.len() as int, NUM_SLOTS: cache.len() as int,
        __element_dtype_x: float_dtype(), __element_dtype_cache: float_dtype(),
        __element_dtype_slot_mapping: int_dtype(),
    }
}

pub open spec fn domain(rows: Tensor2D, cache: Tensor2D, slots: IntTensor1D) -> bool {
    raw_exact_effect_raw_pre(before(rows, cache, slots), RawExactEffectFree {})
}

pub open spec fn output(rows: Tensor2D, cache: Tensor2D, slots: IntTensor1D) -> Tensor2D {
    raw_execute(before(rows, cache, slots)).cache
}

pub proof fn checked_copy(rows: Tensor2D, cache: Tensor2D, slots: IntTensor1D, i: int)
    requires domain(rows, cache, slots), 0 <= i < rows.len(), slots[i] >= 0,
    ensures 0 <= slots[i] < cache.len(), output(rows, cache, slots)[slots[i]] == rows[i],
{
    let launch = before(rows, cache, slots);
    let free = RawExactEffectFree {};
    raw_exact_effect_certificate(launch, free);
    let after = raw_execute(launch);
    assert(raw_exact_effect_quantified_2(launch, after, free, i));
    assert forall|c: int| 0 <= c < 2048 implies
        #[trigger] after.cache[slots[i]][c] == rows[i][c] by {
        assert(raw_exact_effect_region_0(launch, after, free, i, 0, c));
    }
    assert(after.cache[slots[i]] =~= rows[i]);
}

pub proof fn checked_frame(rows: Tensor2D, cache: Tensor2D, slots: IntTensor1D, s: int)
    requires domain(rows, cache, slots), 0 <= s < cache.len(),
        forall|i: int| 0 <= i < slots.len() ==> (#[trigger] slots[i]) != s,
    ensures output(rows, cache, slots)[s] == cache[s],
{
    let launch = before(rows, cache, slots);
    let free = RawExactEffectFree {};
    raw_exact_effect_certificate(launch, free);
    let after = raw_execute(launch);
    assert forall|i: int| #[trigger] raw_exact_effect_quantified_3(launch, after, free, s, i) by {}
    assert(raw_exact_effect_quantified_4(launch, after, free, s));
    assert forall|c: int| 0 <= c < 2048 implies
        #[trigger] after.cache[s][c] == cache[s][c] by {
        assert(raw_exact_effect_region_1(launch, after, free, s, 0, c));
    }
    assert(after.cache[s] =~= cache[s]);
}
// END CHECKED MUTATION ADAPTER

} // verus!
}

pub mod geometry_KVD_4096 {
use super::*;
verus! {
// Abstract interface for ONE fixed, separately qualified deployment.
// Alternative implementations prove this same theory; their outputs
// are not equated. See the separate implementation proof records.
// Exact temporal ContractIR lowering for store_cache_kernel

pub open spec fn raw_exact_effect_cdiv(numerator: int, denominator: int) -> int {
    (numerator + denominator - 1) / denominator
}

#[verifier::external_body]
#[verifier::ext_equal]
pub struct RawDType {
    _private: (),
}

pub struct RawSide {
    pub x: Seq<Seq<Scalar>>,
    pub slot_mapping: Seq<int>,
    pub cache: Seq<Seq<Scalar>>,
    pub M: int,
    pub NUM_SLOTS: int,
    pub __element_dtype_cache: RawDType,
    pub __element_dtype_slot_mapping: RawDType,
    pub __element_dtype_x: RawDType,
}

pub uninterp spec fn raw_cache_cell(before: RawSide, _i0: int, _i1: int) -> Scalar;

pub open spec fn raw_cache_after(before: RawSide)
    -> Seq<Seq<Scalar>>
{
    Seq::new(before.cache.len(), |_i0: int| Seq::new(before.cache[_i0].len(), |_i1: int| raw_cache_cell(before, _i0, _i1)))
}

pub open spec fn raw_execute(before: RawSide) -> RawSide {
    RawSide {
        x: before.x,
        slot_mapping: before.slot_mapping,
        cache: raw_cache_after(before),
        M: before.M,
        NUM_SLOTS: before.NUM_SLOTS,
        __element_dtype_cache: before.__element_dtype_cache,
        __element_dtype_slot_mapping: before.__element_dtype_slot_mapping,
        __element_dtype_x: before.__element_dtype_x,
    }
}

pub struct RawExactEffectFree {}

pub open spec fn raw_exact_effect_quantified_0(before: RawSide, after: RawSide,
    free: RawExactEffectFree, _q0: int) -> bool {
    (((_q0 >= 0) && (_q0 < before.M)) ==> ((before.slot_mapping[_q0] >= (0 - 1)) && (before.slot_mapping[_q0] < before.NUM_SLOTS)))
}

pub open spec fn raw_exact_effect_quantified_1(before: RawSide, after: RawSide,
    free: RawExactEffectFree, _q0: int, _q1: int) -> bool {
    (((_q0 >= 0) && (_q0 < before.M) && (_q1 >= 0) && (_q1 < before.M) && (before.slot_mapping[_q0] >= 0) && (before.slot_mapping[_q0] == before.slot_mapping[_q1])) ==> (_q0 == _q1))
}

pub open spec fn raw_exact_effect_quantified_2(before: RawSide, after: RawSide,
    free: RawExactEffectFree, _q0: int) -> bool {
    (((_q0 >= 0) && (_q0 < before.M) && (before.slot_mapping[_q0] >= 0)) ==> (0 <= before.slot_mapping[_q0] <= (before.slot_mapping[_q0] + 1) <= before.NUM_SLOTS && 0 <= _q0 <= (_q0 + 1) <= before.M && ((before.slot_mapping[_q0] + 1) - before.slot_mapping[_q0]) == ((_q0 + 1) - _q0) && 0 <= 0 <= 4096 <= 4096 && 0 <= 0 <= 4096 <= 4096 && (4096 - 0) == (4096 - 0) && (forall|_r0: int, _r1: int| #[trigger] raw_exact_effect_region_0(before, after, free, _q0, _r0, _r1))))
}

pub open spec fn raw_exact_effect_quantified_3(before: RawSide, after: RawSide,
    free: RawExactEffectFree, _q0: int, _q1: int) -> bool {
    (((_q1 >= 0) && (_q1 < before.M)) ==> !((before.slot_mapping[_q1] == _q0)))
}

pub open spec fn raw_exact_effect_quantified_4(before: RawSide, after: RawSide,
    free: RawExactEffectFree, _q0: int) -> bool {
    (((_q0 >= 0) && (_q0 < before.NUM_SLOTS) && (forall|_q1: int| #[trigger] raw_exact_effect_quantified_3(before, after, free, _q0, _q1))) ==> (0 <= _q0 <= (_q0 + 1) <= before.NUM_SLOTS && 0 <= _q0 <= (_q0 + 1) <= before.NUM_SLOTS && ((_q0 + 1) - _q0) == ((_q0 + 1) - _q0) && 0 <= 0 <= 4096 <= 4096 && 0 <= 0 <= 4096 <= 4096 && (4096 - 0) == (4096 - 0) && (forall|_r0: int, _r1: int| #[trigger] raw_exact_effect_region_1(before, after, free, _q0, _r0, _r1))))
}


pub open spec fn raw_exact_effect_region_0(before: RawSide, after: RawSide,
    free: RawExactEffectFree, _q0: int, _r0: int, _r1: int) -> bool {
    0 <= _r0 < ((before.slot_mapping[_q0] + 1) - before.slot_mapping[_q0]) && 0 <= _r1 < (4096 - 0) ==> after.cache[before.slot_mapping[_q0] + _r0][0 + _r1] == before.x[_q0 + _r0][0 + _r1]
}

pub open spec fn raw_exact_effect_region_1(before: RawSide, after: RawSide,
    free: RawExactEffectFree, _q0: int, _r0: int, _r1: int) -> bool {
    0 <= _r0 < ((_q0 + 1) - _q0) && 0 <= _r1 < (4096 - 0) ==> after.cache[_q0 + _r0][0 + _r1] == before.cache[_q0 + _r0][0 + _r1]
}

pub uninterp spec fn raw_exact_effect_external_obligation_0(before: RawSide, free: RawExactEffectFree) -> bool;
pub uninterp spec fn raw_exact_effect_external_obligation_1(before: RawSide, free: RawExactEffectFree) -> bool;
pub uninterp spec fn raw_exact_effect_external_obligation_2(before: RawSide, free: RawExactEffectFree) -> bool;

pub open spec fn raw_exact_effect_raw_pre(before: RawSide, free: RawExactEffectFree) -> bool {
    let after = before;
    &&& 0 <= before.M
    &&& 0 <= 4096
    &&& before.x.len() as int == before.M
    &&& forall|_s0: int| 0 <= _s0 < before.x.len() as int ==> (#[trigger] before.x[_s0]).len() as int == 4096
    &&& 0 <= before.M
    &&& before.slot_mapping.len() as int == before.M
    &&& 0 <= before.NUM_SLOTS
    &&& 0 <= 4096
    &&& before.cache.len() as int == before.NUM_SLOTS
    &&& forall|_s0: int| 0 <= _s0 < before.cache.len() as int ==> (#[trigger] before.cache[_s0]).len() as int == 4096
    &&& (before.M >= 0)
    &&& (before.NUM_SLOTS > 0)
    &&& (4096 > 0)
    &&& (before.__element_dtype_x == before.__element_dtype_cache)
    &&& (forall|_q0: int| #[trigger] raw_exact_effect_quantified_0(before, after, free, _q0))
    &&& (forall|_q0: int, _q1: int| #[trigger] raw_exact_effect_quantified_1(before, after, free, _q0, _q1))
    &&& raw_exact_effect_external_obligation_0(before, free)
    &&& raw_exact_effect_external_obligation_1(before, free)
    &&& raw_exact_effect_external_obligation_2(before, free)
}

pub open spec fn raw_exact_effect_raw_post(before: RawSide, after: RawSide, free: RawExactEffectFree) -> bool {
    &&& (forall|_q0: int| #[trigger] raw_exact_effect_quantified_2(before, after, free, _q0))
    &&& (forall|_q0: int| #[trigger] raw_exact_effect_quantified_4(before, after, free, _q0))
}

// Trusted import of the proved copy/frame theorem, retaining all premises.
// This is about one execution's before/after states, not batch invariance.
#[verifier::external_body]
pub proof fn raw_exact_effect_certificate(before: RawSide, free: RawExactEffectFree)
    requires raw_exact_effect_raw_pre(before, free),
    ensures raw_exact_effect_raw_post(before, raw_execute(before), free),
{
    unreachable!()
}

// BEGIN CHECKED MUTATION ADAPTER
// Canonical physical dtype identities for a fixed deployed float/int interface.
// Their physical interpretation is required by the raw correspondence premises.
pub uninterp spec fn float_dtype() -> RawDType;
pub uninterp spec fn int_dtype() -> RawDType;

pub open spec fn before(rows: Tensor2D, cache: Tensor2D, slots: IntTensor1D) -> RawSide {
    RawSide {
        x: rows, cache: cache, slot_mapping: slots,
        M: rows.len() as int, NUM_SLOTS: cache.len() as int,
        __element_dtype_x: float_dtype(), __element_dtype_cache: float_dtype(),
        __element_dtype_slot_mapping: int_dtype(),
    }
}

pub open spec fn domain(rows: Tensor2D, cache: Tensor2D, slots: IntTensor1D) -> bool {
    raw_exact_effect_raw_pre(before(rows, cache, slots), RawExactEffectFree {})
}

pub open spec fn output(rows: Tensor2D, cache: Tensor2D, slots: IntTensor1D) -> Tensor2D {
    raw_execute(before(rows, cache, slots)).cache
}

pub proof fn checked_copy(rows: Tensor2D, cache: Tensor2D, slots: IntTensor1D, i: int)
    requires domain(rows, cache, slots), 0 <= i < rows.len(), slots[i] >= 0,
    ensures 0 <= slots[i] < cache.len(), output(rows, cache, slots)[slots[i]] == rows[i],
{
    let launch = before(rows, cache, slots);
    let free = RawExactEffectFree {};
    raw_exact_effect_certificate(launch, free);
    let after = raw_execute(launch);
    assert(raw_exact_effect_quantified_2(launch, after, free, i));
    assert forall|c: int| 0 <= c < 4096 implies
        #[trigger] after.cache[slots[i]][c] == rows[i][c] by {
        assert(raw_exact_effect_region_0(launch, after, free, i, 0, c));
    }
    assert(after.cache[slots[i]] =~= rows[i]);
}

pub proof fn checked_frame(rows: Tensor2D, cache: Tensor2D, slots: IntTensor1D, s: int)
    requires domain(rows, cache, slots), 0 <= s < cache.len(),
        forall|i: int| 0 <= i < slots.len() ==> (#[trigger] slots[i]) != s,
    ensures output(rows, cache, slots)[s] == cache[s],
{
    let launch = before(rows, cache, slots);
    let free = RawExactEffectFree {};
    raw_exact_effect_certificate(launch, free);
    let after = raw_execute(launch);
    assert forall|i: int| #[trigger] raw_exact_effect_quantified_3(launch, after, free, s, i) by {}
    assert(raw_exact_effect_quantified_4(launch, after, free, s));
    assert forall|c: int| 0 <= c < 4096 implies
        #[trigger] after.cache[s][c] == cache[s][c] by {
        assert(raw_exact_effect_region_1(launch, after, free, s, 0, c));
    }
    assert(after.cache[s] =~= cache[s]);
}
// END CHECKED MUTATION ADAPTER

} // verus!
}

// BEGIN CHECKED GEOMETRY DISPATCH
verus! {
pub open spec fn domain(rows: Tensor2D, cache: Tensor2D, slots: IntTensor1D, width: nat) -> bool {
    if width == 512 { geometry_KVD_512::domain(rows, cache, slots) } else if width == 1024 { geometry_KVD_1024::domain(rows, cache, slots) } else if width == 2048 { geometry_KVD_2048::domain(rows, cache, slots) } else if width == 4096 { geometry_KVD_4096::domain(rows, cache, slots) } else { false }
}
pub open spec fn output(rows: Tensor2D, cache: Tensor2D, slots: IntTensor1D, width: nat) -> Tensor2D {
    if width == 512 { geometry_KVD_512::output(rows, cache, slots) } else if width == 1024 { geometry_KVD_1024::output(rows, cache, slots) } else if width == 2048 { geometry_KVD_2048::output(rows, cache, slots) } else if width == 4096 { geometry_KVD_4096::output(rows, cache, slots) } else { Seq::empty() }
}
pub proof fn checked_copy(rows: Tensor2D, cache: Tensor2D, slots: IntTensor1D, width: nat, i: int)
    requires domain(rows, cache, slots, width), 0 <= i < rows.len(), slots[i] >= 0,
    ensures 0 <= slots[i] < cache.len(), output(rows, cache, slots, width)[slots[i]] == rows[i],
{
    if width == 512 { geometry_KVD_512::checked_copy(rows, cache, slots, i); } else if width == 1024 { geometry_KVD_1024::checked_copy(rows, cache, slots, i); } else if width == 2048 { geometry_KVD_2048::checked_copy(rows, cache, slots, i); } else if width == 4096 { geometry_KVD_4096::checked_copy(rows, cache, slots, i); }
}
pub proof fn checked_frame(rows: Tensor2D, cache: Tensor2D, slots: IntTensor1D, width: nat, s: int)
    requires domain(rows, cache, slots, width), 0 <= s < cache.len(),
        forall|i: int| 0 <= i < slots.len() ==> (#[trigger] slots[i]) != s,
    ensures output(rows, cache, slots, width)[s] == cache[s],
{
    if width == 512 { geometry_KVD_512::checked_frame(rows, cache, slots, s); } else if width == 1024 { geometry_KVD_1024::checked_frame(rows, cache, slots, s); } else if width == 2048 { geometry_KVD_2048::checked_frame(rows, cache, slots, s); } else if width == 4096 { geometry_KVD_4096::checked_frame(rows, cache, slots, s); }
}
pub proof fn checked_shape(rows: Tensor2D, cache: Tensor2D, slots: IntTensor1D, width: nat)
    requires domain(rows, cache, slots, width),
    ensures output(rows, cache, slots, width).len() == cache.len(),
{
    if width == 512 {  } else if width == 1024 {  } else if width == 2048 {  } else if width == 4096 {  }
}
} // verus!
