// @generated by scripts/verification/verify_rectangular_interfaces.py; DO NOT EDIT.
#![allow(non_snake_case)]
use vstd::prelude::*;
use crate::{boundary::scalar::{Scalar}, proof::tensor::types::{Tensor1D, Tensor2D, IntTensor1D}};
use crate::proof::tensor::shape as TS;
#[cfg(verus_only)]
use crate::boundary::backend_certificates::support::generated_kernel_allocation_cell;

verus! {
// Abstract interface for ONE fixed, separately qualified deployment.
// Alternative implementations prove this same theory; their outputs
// are not equated. See the separate implementation proof records.
// Raw ContractIR lowering for matmul_kernel

pub open spec fn raw_batch_invariance_cdiv(numerator: int, denominator: int) -> int {
    (numerator + denominator - 1) / denominator
}

pub struct RawSide {
    pub a: Seq<Seq<Scalar>>,
    pub b: Seq<Seq<Scalar>>,
    pub c: Seq<Seq<Scalar>>,
    pub K: int,
    pub M: int,
    pub N: int,
}

pub struct RawBatchInvarianceFree {
    pub x: int,
}


pub uninterp spec fn raw_c_cell(before: RawSide, _i0: int, _i1: int) -> Scalar;

pub open spec fn raw_c_after(before: RawSide)
    -> Seq<Seq<Scalar>>
{
    Seq::new(before.c.len(), |_i0: int| Seq::new(before.c[_i0].len(), |_i1: int| raw_c_cell(before, _i0, _i1)))
}

pub open spec fn raw_execute(before: RawSide) -> RawSide {
    RawSide {
        a: before.a,
        b: before.b,
        c: raw_c_after(before),
        K: before.K,
        M: before.M,
        N: before.N,
    }
}

pub open spec fn raw_batch_invariance_raw_pre(
    left: RawSide,
    right: RawSide,
    free: RawBatchInvarianceFree,
) -> bool {
    &&& 0 <= left.M
    &&& 0 <= left.K
    &&& left.a.len() as int == left.M
    &&& forall|_s0: int| 0 <= _s0 < left.a.len() as int ==> (#[trigger] left.a[_s0]).len() as int == left.K
    &&& 0 <= left.N
    &&& left.b.len() as int == left.K
    &&& forall|_s0: int| 0 <= _s0 < left.b.len() as int ==> (#[trigger] left.b[_s0]).len() as int == left.N
    &&& left.c.len() as int == left.M
    &&& forall|_s0: int| 0 <= _s0 < left.c.len() as int ==> (#[trigger] left.c[_s0]).len() as int == left.N
    &&& 0 <= right.M
    &&& 0 <= right.K
    &&& right.a.len() as int == right.M
    &&& forall|_s0: int| 0 <= _s0 < right.a.len() as int ==> (#[trigger] right.a[_s0]).len() as int == right.K
    &&& 0 <= right.N
    &&& right.b.len() as int == right.K
    &&& forall|_s0: int| 0 <= _s0 < right.b.len() as int ==> (#[trigger] right.b[_s0]).len() as int == right.N
    &&& right.c.len() as int == right.M
    &&& forall|_s0: int| 0 <= _s0 < right.c.len() as int ==> (#[trigger] right.c[_s0]).len() as int == right.N
    &&& left.K == right.K
    &&& left.N == right.N
    &&& right.M == 1
    &&& free.x >= 0
    &&& free.x < left.M
    &&& (0 <= free.x && free.x <= (free.x + 1) && (free.x + 1) <= left.M && 0 <= 0 && 0 <= 1 && 1 <= right.M && ((free.x + 1) - free.x) == (1 - 0) && 0 <= 0 && 0 <= left.K && left.K <= left.K && 0 <= 0 && 0 <= left.K && left.K <= right.K && (left.K - 0) == (left.K - 0) && forall|_r0: int, _r1: int| 0 <= _r0 < ((free.x + 1) - free.x) && 0 <= _r1 < (left.K - 0) ==> #[trigger] left.a[free.x + _r0][0 + _r1] == right.a[0 + _r0][0 + _r1])
    &&& (0 <= 0 && 0 <= left.K && left.K <= left.K && 0 <= 0 && 0 <= left.K && left.K <= right.K && (left.K - 0) == (left.K - 0) && 0 <= 0 && 0 <= left.N && left.N <= left.N && 0 <= 0 && 0 <= left.N && left.N <= right.N && (left.N - 0) == (left.N - 0) && forall|_r0: int, _r1: int| 0 <= _r0 < (left.K - 0) && 0 <= _r1 < (left.N - 0) ==> #[trigger] left.b[0 + _r0][0 + _r1] == right.b[0 + _r0][0 + _r1])
}

pub open spec fn raw_batch_invariance_raw_post(
    left: RawSide,
    right: RawSide,
    free: RawBatchInvarianceFree,
) -> bool {
    &&& (0 <= free.x && free.x <= (free.x + 1) && (free.x + 1) <= left.M && 0 <= 0 && 0 <= 1 && 1 <= right.M && ((free.x + 1) - free.x) == (1 - 0) && 0 <= 0 && 0 <= left.N && left.N <= left.N && 0 <= 0 && 0 <= left.N && left.N <= right.N && (left.N - 0) == (left.N - 0) && forall|_r0: int, _r1: int| 0 <= _r0 < ((free.x + 1) - free.x) && 0 <= _r1 < (left.N - 0) ==> #[trigger] left.c[free.x + _r0][0 + _r1] == right.c[0 + _r0][0 + _r1])
}

// Trusted import of the relational theorem proved for the source and
// specialization named above.  The generated execute function preserves
// launch metadata and allocation shape; only written output cells are opaque.
#[verifier::external_body]
pub proof fn raw_batch_invariance_certificate(
    left: RawSide,
    right: RawSide,
    free: RawBatchInvarianceFree,
)
    requires raw_batch_invariance_raw_pre(left, right, free),
    ensures raw_batch_invariance_raw_post(
        raw_execute(left), raw_execute(right), free,
    ),
{
    unreachable!()
}

// BEGIN CHECKED RECTANGULAR ADAPTER

// Canonical framework values for the raw launch semantics.  Each pre-launch
// output is a generated rectangular allocation with the exact declared shape;
// the generated execute function replaces every logical output cell.
pub open spec fn row_projection_c_allocation(
    rows: nat,
    cols: nat,
) -> Tensor2D {
    Seq::new(rows, |_row: int| Seq::new(cols, |_col: int|
        generated_kernel_allocation_cell()))
}

pub open spec fn row_projection_repr(
    input_a: Tensor2D,
    input_b: Tensor2D,
    K: nat,
    N: nat,
) -> Tensor2D {
    raw_c_after(RawSide {
        a: input_a,
        b: input_b,
        c: row_projection_c_allocation(input_a.len(), N),
        M: input_a.len() as int,
        K: K as int,
        N: N as int,
    })
}

pub open spec fn row_projection_mapped_repr(
    input_a: Tensor2D,
    input_b: Tensor2D,
    K: nat,
    N: nat,
) -> Tensor2D {
    Seq::new(input_a.len(), |_row: int|
        row_projection_repr(seq![input_a[_row]], input_b, K, N)[0])
}

// Exact source-annotation domain at the chosen projection. No domain
// policy table weakens or interprets the source predicate.
pub open spec fn row_projection_domain(
    input_a: Tensor2D,
    input_b: Tensor2D,
    rows: nat,
    K: nat,
    N: nat,
    i: nat,
) -> bool {
    let left = RawSide { a: input_a,
        b: input_b,
        c: row_projection_c_allocation(rows, N),
        M: rows as int,
        K: K as int,
        N: N as int };
    let right = RawSide { a: seq![input_a[i as int]],
        b: input_b,
        c: row_projection_c_allocation(1, N),
        M: 1,
        K: K as int,
        N: N as int };
    let free = RawBatchInvarianceFree { x: i as int };
    raw_batch_invariance_raw_pre(left, right, free)
}


// Checked rectangular instantiation of the generated raw ContractIR theorem.
pub proof fn row_projection_certificate(
    input_a: Tensor2D,
    input_b: Tensor2D,
    rows: nat,
    K: nat,
    N: nat,
    i: nat,
)
    requires
        TS::tensor2d_shape(input_a, rows, K),
        TS::tensor2d_shape(input_b, K, N),
        row_projection_domain(input_a, input_b, rows, K, N, i),
        i < rows,
    ensures
        row_projection_repr(seq![input_a[i as int]], input_b, K, N)
            == seq![row_projection_repr(input_a, input_b, K, N)[i as int]],
{
    reveal(row_projection_domain);

    let left = RawSide {
        a: input_a,
        b: input_b,
        c: row_projection_c_allocation(rows, N),
        M: rows as int,
        K: K as int,
        N: N as int,
    };
    let right = RawSide {
        a: seq![input_a[i as int]],
        b: input_b,
        c: row_projection_c_allocation(1, N),
        M: 1,
        K: K as int,
        N: N as int,
    };
    let free = RawBatchInvarianceFree { x: i as int };
    assert(raw_batch_invariance_raw_pre(left, right, free)) by {
        reveal(row_projection_c_allocation);
        assert forall|r: int| 0 <= r < rows implies
            (#[trigger] input_a[r]).len() == K by {};
        assert forall|r0: int, r1: int|
            0 <= r0 < 1 && 0 <= r1 < K implies
            #[trigger] left.a[i as int + r0][r1]
                == right.a[r0][r1] by {
            assert(r0 == 0);
        };
    }
    raw_batch_invariance_certificate(left, right, free);
    let left_after = raw_execute(left);
    let right_after = raw_execute(right);
    assert(raw_batch_invariance_raw_post(left_after, right_after, free));
    reveal(raw_batch_invariance_raw_post);
    reveal(raw_execute);
    assert(left_after.M == rows as int);
    assert(right_after.M == 1);
    assert(left_after.K == K as int);
    assert(right_after.K == K as int);
    assert(left_after.N == N as int);
    assert(right_after.N == N as int);
    assert(0 <= i as int && i as int + 1 <= left_after.M);
    assert forall|c: int| 0 <= c < N implies
        (#[trigger] left_after.c[i as int][c])
            == right_after.c[0][c] by {
        assert(0 <= 0 < ((free.x + 1) - free.x));
        assert(0 <= c < N);
        assert(left_after.c[free.x + 0][0 + c]
            == right_after.c[0 as int][0 + c]);
    };
    assert(left_after.c[i as int]
        =~= right_after.c[0]);
    reveal(row_projection_repr);
    assert(row_projection_repr(input_a, input_b, K, N)[i as int]
        == left_after.c[i as int]);
    assert(row_projection_repr(seq![input_a[i as int]], input_b, K, N)[0]
        == right_after.c[0]);
    assert(row_projection_repr(seq![input_a[i as int]], input_b, K, N)
        =~= seq![row_projection_repr(input_a, input_b, K, N)[i as int]]);
}

// The engine may use the mapped representation as its total row-local
// semantics.  For every valid rectangular launch, this checked theorem shows
// that it is exactly the generated raw whole-launch representation.
pub proof fn row_projection_launch_equivalence(
    input_a: Tensor2D,
    input_b: Tensor2D,
    rows: nat,
    K: nat,
    N: nat,
)
    requires
        TS::tensor2d_shape(input_a, rows, K),
        TS::tensor2d_shape(input_b, K, N),
        forall|row: nat| row < rows ==>
            #[trigger] row_projection_domain(input_a, input_b, rows, K, N, row),
    ensures
        row_projection_repr(input_a, input_b, K, N)
            == row_projection_mapped_repr(input_a, input_b, K, N),
{
    assert forall|_row: int| 0 <= _row < rows implies
        (#[trigger] row_projection_repr(input_a, input_b, K, N)[_row])
            == row_projection_mapped_repr(input_a, input_b, K, N)[_row] by {
        row_projection_certificate(input_a, input_b, rows, K, N, _row as nat);
        reveal(row_projection_mapped_repr);
        assert(row_projection_repr(seq![input_a[_row]], input_b, K, N)[0]
            == row_projection_repr(input_a, input_b, K, N)[_row]);
    };
    assert(row_projection_repr(input_a, input_b, K, N)
        =~= row_projection_mapped_repr(input_a, input_b, K, N));
}

} // verus!
