// @generated by scripts/verification/rectangular_interface_catalog.py; DO NOT EDIT.
#![allow(non_snake_case)]
use vstd::prelude::*;
use crate::{boundary::scalar::{Scalar}, proof::tensor::types::{Tensor1D, Tensor2D, IntTensor1D}};
use crate::proof::tensor::shape as TS;
#[cfg(verus_only)]
use crate::boundary::backend_certificates::support::generated_kernel_allocation_cell;

pub mod geometry_D_128_H_16 {
use super::*;
verus! {
// Abstract interface for ONE fixed, separately qualified deployment.
// Alternative implementations prove this same theory; their outputs
// are not equated. See the separate implementation proof records.
// Raw ContractIR lowering for gemma_head_rms_norm_kernel

pub open spec fn raw_batch_invariance_cdiv(numerator: int, denominator: int) -> int {
    (numerator + denominator - 1) / denominator
}

pub struct RawSide {
    pub x: Seq<Seq<Scalar>>,
    pub w: Seq<Scalar>,
    pub o: Seq<Seq<Scalar>>,
    pub eps: Scalar,
    pub M: int,
}

pub struct RawBatchInvarianceFree {
    pub b: int,
}


pub uninterp spec fn raw_o_cell(before: RawSide, _i0: int, _i1: int) -> Scalar;

pub open spec fn raw_o_after(before: RawSide)
    -> Seq<Seq<Scalar>>
{
    Seq::new(before.o.len(), |_i0: int| Seq::new(before.o[_i0].len(), |_i1: int| raw_o_cell(before, _i0, _i1)))
}

pub open spec fn raw_execute(before: RawSide) -> RawSide {
    RawSide {
        x: before.x,
        w: before.w,
        o: raw_o_after(before),
        eps: before.eps,
        M: before.M,
    }
}

pub open spec fn raw_batch_invariance_raw_pre(
    left: RawSide,
    right: RawSide,
    free: RawBatchInvarianceFree,
) -> bool {
    &&& 0 <= left.M
    &&& 0 <= (16 * 128)
    &&& left.x.len() as int == left.M
    &&& forall|_s0: int| 0 <= _s0 < left.x.len() as int ==> (#[trigger] left.x[_s0]).len() as int == (16 * 128)
    &&& 0 <= 128
    &&& left.w.len() as int == 128
    &&& left.o.len() as int == left.M
    &&& forall|_s0: int| 0 <= _s0 < left.o.len() as int ==> (#[trigger] left.o[_s0]).len() as int == (16 * 128)
    &&& 0 <= right.M
    &&& right.x.len() as int == right.M
    &&& forall|_s0: int| 0 <= _s0 < right.x.len() as int ==> (#[trigger] right.x[_s0]).len() as int == (16 * 128)
    &&& right.w.len() as int == 128
    &&& right.o.len() as int == right.M
    &&& forall|_s0: int| 0 <= _s0 < right.o.len() as int ==> (#[trigger] right.o[_s0]).len() as int == (16 * 128)
    &&& left.eps == right.eps
    &&& right.M == 1
    &&& free.b >= 0
    &&& free.b < left.M
    &&& (0 <= free.b && free.b <= (free.b + 1) && (free.b + 1) <= left.M && 0 <= 0 && 0 <= 1 && 1 <= right.M && ((free.b + 1) - free.b) == (1 - 0) && 0 <= 0 && 0 <= (16 * 128) && (16 * 128) <= (16 * 128) && 0 <= 0 && 0 <= (16 * 128) && (16 * 128) <= (16 * 128) && ((16 * 128) - 0) == ((16 * 128) - 0) && forall|_r0: int, _r1: int| 0 <= _r0 < ((free.b + 1) - free.b) && 0 <= _r1 < ((16 * 128) - 0) ==> #[trigger] left.x[free.b + _r0][0 + _r1] == right.x[0 + _r0][0 + _r1])
    &&& (0 <= 0 && 0 <= 128 && 128 <= 128 && 0 <= 0 && 0 <= 128 && 128 <= 128 && (128 - 0) == (128 - 0) && forall|_r0: int| 0 <= _r0 < (128 - 0) ==> #[trigger] left.w[0 + _r0] == right.w[0 + _r0])
}

pub open spec fn raw_batch_invariance_raw_post(
    left: RawSide,
    right: RawSide,
    free: RawBatchInvarianceFree,
) -> bool {
    &&& (0 <= free.b && free.b <= (free.b + 1) && (free.b + 1) <= left.M && 0 <= 0 && 0 <= 1 && 1 <= right.M && ((free.b + 1) - free.b) == (1 - 0) && 0 <= 0 && 0 <= (16 * 128) && (16 * 128) <= (16 * 128) && 0 <= 0 && 0 <= (16 * 128) && (16 * 128) <= (16 * 128) && ((16 * 128) - 0) == ((16 * 128) - 0) && forall|_r0: int, _r1: int| 0 <= _r0 < ((free.b + 1) - free.b) && 0 <= _r1 < ((16 * 128) - 0) ==> #[trigger] left.o[free.b + _r0][0 + _r1] == right.o[0 + _r0][0 + _r1])
}

// Trusted import of the relational theorem proved for the source and
// specialization named above.  The generated execute function preserves
// launch metadata and allocation shape; only written output cells are opaque.
#[verifier::external_body]
pub proof fn raw_batch_invariance_certificate(
    left: RawSide,
    right: RawSide,
    free: RawBatchInvarianceFree,
)
    requires raw_batch_invariance_raw_pre(left, right, free),
    ensures raw_batch_invariance_raw_post(
        raw_execute(left), raw_execute(right), free,
    ),
{
    unreachable!()
}

// BEGIN CHECKED RECTANGULAR ADAPTER

// Canonical framework values for the raw launch semantics.  Each pre-launch
// output is a generated rectangular allocation with the exact declared shape;
// the generated execute function replaces every logical output cell.
pub open spec fn row_projection_o_allocation(
    rows: nat,
    cols: nat,
) -> Tensor2D {
    Seq::new(rows, |_row: int| Seq::new(cols, |_col: int|
        generated_kernel_allocation_cell()))
}

pub open spec fn row_projection_repr(
    input_x: Tensor2D,
    input_w: Tensor1D,
    input_eps: Scalar,
) -> Tensor2D {
    raw_o_after(RawSide {
        x: input_x,
        w: input_w,
        eps: input_eps,
        o: row_projection_o_allocation(input_x.len(), (16 * 128)),
        M: input_x.len() as int,
    })
}

pub open spec fn row_projection_mapped_repr(
    input_x: Tensor2D,
    input_w: Tensor1D,
    input_eps: Scalar,
) -> Tensor2D {
    Seq::new(input_x.len(), |_row: int|
        row_projection_repr(seq![input_x[_row]], input_w, input_eps)[0])
}

// Exact source-annotation domain at the chosen projection. No domain
// policy table weakens or interprets the source predicate.
pub open spec fn row_projection_domain(
    input_x: Tensor2D,
    input_w: Tensor1D,
    input_eps: Scalar,
    rows: nat,
    i: nat,
) -> bool {
    let left = RawSide { x: input_x,
        w: input_w,
        eps: input_eps,
        o: row_projection_o_allocation(rows, (16 * 128)),
        M: rows as int };
    let right = RawSide { x: seq![input_x[i as int]],
        w: input_w,
        eps: input_eps,
        o: row_projection_o_allocation(1, (16 * 128)),
        M: 1 };
    let free = RawBatchInvarianceFree { b: i as int };
    raw_batch_invariance_raw_pre(left, right, free)
}


// Checked rectangular instantiation of the generated raw ContractIR theorem.
pub proof fn row_projection_certificate(
    input_x: Tensor2D,
    input_w: Tensor1D,
    input_eps: Scalar,
    rows: nat,
    i: nat,
)
    requires
        TS::tensor2d_shape(input_x, rows, (16 * 128)),
        input_w.len() == 128,
        row_projection_domain(input_x, input_w, input_eps, rows, i),
        i < rows,
    ensures
        row_projection_repr(seq![input_x[i as int]], input_w, input_eps)
            == seq![row_projection_repr(input_x, input_w, input_eps)[i as int]],
{
    reveal(row_projection_domain);

    let left = RawSide {
        x: input_x,
        w: input_w,
        eps: input_eps,
        o: row_projection_o_allocation(rows, (16 * 128)),
        M: rows as int,
    };
    let right = RawSide {
        x: seq![input_x[i as int]],
        w: input_w,
        eps: input_eps,
        o: row_projection_o_allocation(1, (16 * 128)),
        M: 1,
    };
    let free = RawBatchInvarianceFree { b: i as int };
    assert(raw_batch_invariance_raw_pre(left, right, free)) by {
        reveal(row_projection_o_allocation);
        assert forall|r: int| 0 <= r < rows implies
            (#[trigger] input_x[r]).len() == (16 * 128) by {};
        assert forall|r0: int, r1: int|
            0 <= r0 < 1 && 0 <= r1 < (16 * 128) implies
            #[trigger] left.x[i as int + r0][r1]
                == right.x[r0][r1] by {
            assert(r0 == 0);
        };
    }
    raw_batch_invariance_certificate(left, right, free);
    let left_after = raw_execute(left);
    let right_after = raw_execute(right);
    assert(raw_batch_invariance_raw_post(left_after, right_after, free));
    reveal(raw_batch_invariance_raw_post);
    reveal(raw_execute);
    assert(left_after.M == rows as int);
    assert(right_after.M == 1);

    assert(0 <= i as int && i as int + 1 <= left_after.M);
    assert forall|c: int| 0 <= c < (16 * 128) implies
        (#[trigger] left_after.o[i as int][c])
            == right_after.o[0][c] by {
        assert(0 <= 0 < ((free.b + 1) - free.b));
        assert(0 <= c < (16 * 128));
        assert(left_after.o[free.b + 0][0 + c]
            == right_after.o[0 as int][0 + c]);
    };
    assert(left_after.o[i as int]
        =~= right_after.o[0]);
    reveal(row_projection_repr);
    assert(row_projection_repr(input_x, input_w, input_eps)[i as int]
        == left_after.o[i as int]);
    assert(row_projection_repr(seq![input_x[i as int]], input_w, input_eps)[0]
        == right_after.o[0]);
    assert(row_projection_repr(seq![input_x[i as int]], input_w, input_eps)
        =~= seq![row_projection_repr(input_x, input_w, input_eps)[i as int]]);
}

// The engine may use the mapped representation as its total row-local
// semantics.  For every valid rectangular launch, this checked theorem shows
// that it is exactly the generated raw whole-launch representation.
pub proof fn row_projection_launch_equivalence(
    input_x: Tensor2D,
    input_w: Tensor1D,
    input_eps: Scalar,
    rows: nat,
)
    requires
        TS::tensor2d_shape(input_x, rows, (16 * 128)),
        input_w.len() == 128,
        forall|row: nat| row < rows ==>
            #[trigger] row_projection_domain(input_x, input_w, input_eps, rows, row),
    ensures
        row_projection_repr(input_x, input_w, input_eps)
            == row_projection_mapped_repr(input_x, input_w, input_eps),
{
    assert forall|_row: int| 0 <= _row < rows implies
        (#[trigger] row_projection_repr(input_x, input_w, input_eps)[_row])
            == row_projection_mapped_repr(input_x, input_w, input_eps)[_row] by {
        row_projection_certificate(input_x, input_w, input_eps, rows,  _row as nat);
        reveal(row_projection_mapped_repr);
        assert(row_projection_repr(seq![input_x[_row]], input_w, input_eps)[0]
            == row_projection_repr(input_x, input_w, input_eps)[_row]);
    };
    assert(row_projection_repr(input_x, input_w, input_eps)
        =~= row_projection_mapped_repr(input_x, input_w, input_eps));
}

} // verus!
}

pub mod geometry_D_128_H_32 {
use super::*;
verus! {
// Abstract interface for ONE fixed, separately qualified deployment.
// Alternative implementations prove this same theory; their outputs
// are not equated. See the separate implementation proof records.
// Raw ContractIR lowering for gemma_head_rms_norm_kernel

pub open spec fn raw_batch_invariance_cdiv(numerator: int, denominator: int) -> int {
    (numerator + denominator - 1) / denominator
}

pub struct RawSide {
    pub x: Seq<Seq<Scalar>>,
    pub w: Seq<Scalar>,
    pub o: Seq<Seq<Scalar>>,
    pub eps: Scalar,
    pub M: int,
}

pub struct RawBatchInvarianceFree {
    pub b: int,
}


pub uninterp spec fn raw_o_cell(before: RawSide, _i0: int, _i1: int) -> Scalar;

pub open spec fn raw_o_after(before: RawSide)
    -> Seq<Seq<Scalar>>
{
    Seq::new(before.o.len(), |_i0: int| Seq::new(before.o[_i0].len(), |_i1: int| raw_o_cell(before, _i0, _i1)))
}

pub open spec fn raw_execute(before: RawSide) -> RawSide {
    RawSide {
        x: before.x,
        w: before.w,
        o: raw_o_after(before),
        eps: before.eps,
        M: before.M,
    }
}

pub open spec fn raw_batch_invariance_raw_pre(
    left: RawSide,
    right: RawSide,
    free: RawBatchInvarianceFree,
) -> bool {
    &&& 0 <= left.M
    &&& 0 <= (32 * 128)
    &&& left.x.len() as int == left.M
    &&& forall|_s0: int| 0 <= _s0 < left.x.len() as int ==> (#[trigger] left.x[_s0]).len() as int == (32 * 128)
    &&& 0 <= 128
    &&& left.w.len() as int == 128
    &&& left.o.len() as int == left.M
    &&& forall|_s0: int| 0 <= _s0 < left.o.len() as int ==> (#[trigger] left.o[_s0]).len() as int == (32 * 128)
    &&& 0 <= right.M
    &&& right.x.len() as int == right.M
    &&& forall|_s0: int| 0 <= _s0 < right.x.len() as int ==> (#[trigger] right.x[_s0]).len() as int == (32 * 128)
    &&& right.w.len() as int == 128
    &&& right.o.len() as int == right.M
    &&& forall|_s0: int| 0 <= _s0 < right.o.len() as int ==> (#[trigger] right.o[_s0]).len() as int == (32 * 128)
    &&& left.eps == right.eps
    &&& right.M == 1
    &&& free.b >= 0
    &&& free.b < left.M
    &&& (0 <= free.b && free.b <= (free.b + 1) && (free.b + 1) <= left.M && 0 <= 0 && 0 <= 1 && 1 <= right.M && ((free.b + 1) - free.b) == (1 - 0) && 0 <= 0 && 0 <= (32 * 128) && (32 * 128) <= (32 * 128) && 0 <= 0 && 0 <= (32 * 128) && (32 * 128) <= (32 * 128) && ((32 * 128) - 0) == ((32 * 128) - 0) && forall|_r0: int, _r1: int| 0 <= _r0 < ((free.b + 1) - free.b) && 0 <= _r1 < ((32 * 128) - 0) ==> #[trigger] left.x[free.b + _r0][0 + _r1] == right.x[0 + _r0][0 + _r1])
    &&& (0 <= 0 && 0 <= 128 && 128 <= 128 && 0 <= 0 && 0 <= 128 && 128 <= 128 && (128 - 0) == (128 - 0) && forall|_r0: int| 0 <= _r0 < (128 - 0) ==> #[trigger] left.w[0 + _r0] == right.w[0 + _r0])
}

pub open spec fn raw_batch_invariance_raw_post(
    left: RawSide,
    right: RawSide,
    free: RawBatchInvarianceFree,
) -> bool {
    &&& (0 <= free.b && free.b <= (free.b + 1) && (free.b + 1) <= left.M && 0 <= 0 && 0 <= 1 && 1 <= right.M && ((free.b + 1) - free.b) == (1 - 0) && 0 <= 0 && 0 <= (32 * 128) && (32 * 128) <= (32 * 128) && 0 <= 0 && 0 <= (32 * 128) && (32 * 128) <= (32 * 128) && ((32 * 128) - 0) == ((32 * 128) - 0) && forall|_r0: int, _r1: int| 0 <= _r0 < ((free.b + 1) - free.b) && 0 <= _r1 < ((32 * 128) - 0) ==> #[trigger] left.o[free.b + _r0][0 + _r1] == right.o[0 + _r0][0 + _r1])
}

// Trusted import of the relational theorem proved for the source and
// specialization named above.  The generated execute function preserves
// launch metadata and allocation shape; only written output cells are opaque.
#[verifier::external_body]
pub proof fn raw_batch_invariance_certificate(
    left: RawSide,
    right: RawSide,
    free: RawBatchInvarianceFree,
)
    requires raw_batch_invariance_raw_pre(left, right, free),
    ensures raw_batch_invariance_raw_post(
        raw_execute(left), raw_execute(right), free,
    ),
{
    unreachable!()
}

// BEGIN CHECKED RECTANGULAR ADAPTER

// Canonical framework values for the raw launch semantics.  Each pre-launch
// output is a generated rectangular allocation with the exact declared shape;
// the generated execute function replaces every logical output cell.
pub open spec fn row_projection_o_allocation(
    rows: nat,
    cols: nat,
) -> Tensor2D {
    Seq::new(rows, |_row: int| Seq::new(cols, |_col: int|
        generated_kernel_allocation_cell()))
}

pub open spec fn row_projection_repr(
    input_x: Tensor2D,
    input_w: Tensor1D,
    input_eps: Scalar,
) -> Tensor2D {
    raw_o_after(RawSide {
        x: input_x,
        w: input_w,
        eps: input_eps,
        o: row_projection_o_allocation(input_x.len(), (32 * 128)),
        M: input_x.len() as int,
    })
}

pub open spec fn row_projection_mapped_repr(
    input_x: Tensor2D,
    input_w: Tensor1D,
    input_eps: Scalar,
) -> Tensor2D {
    Seq::new(input_x.len(), |_row: int|
        row_projection_repr(seq![input_x[_row]], input_w, input_eps)[0])
}

// Exact source-annotation domain at the chosen projection. No domain
// policy table weakens or interprets the source predicate.
pub open spec fn row_projection_domain(
    input_x: Tensor2D,
    input_w: Tensor1D,
    input_eps: Scalar,
    rows: nat,
    i: nat,
) -> bool {
    let left = RawSide { x: input_x,
        w: input_w,
        eps: input_eps,
        o: row_projection_o_allocation(rows, (32 * 128)),
        M: rows as int };
    let right = RawSide { x: seq![input_x[i as int]],
        w: input_w,
        eps: input_eps,
        o: row_projection_o_allocation(1, (32 * 128)),
        M: 1 };
    let free = RawBatchInvarianceFree { b: i as int };
    raw_batch_invariance_raw_pre(left, right, free)
}


// Checked rectangular instantiation of the generated raw ContractIR theorem.
pub proof fn row_projection_certificate(
    input_x: Tensor2D,
    input_w: Tensor1D,
    input_eps: Scalar,
    rows: nat,
    i: nat,
)
    requires
        TS::tensor2d_shape(input_x, rows, (32 * 128)),
        input_w.len() == 128,
        row_projection_domain(input_x, input_w, input_eps, rows, i),
        i < rows,
    ensures
        row_projection_repr(seq![input_x[i as int]], input_w, input_eps)
            == seq![row_projection_repr(input_x, input_w, input_eps)[i as int]],
{
    reveal(row_projection_domain);

    let left = RawSide {
        x: input_x,
        w: input_w,
        eps: input_eps,
        o: row_projection_o_allocation(rows, (32 * 128)),
        M: rows as int,
    };
    let right = RawSide {
        x: seq![input_x[i as int]],
        w: input_w,
        eps: input_eps,
        o: row_projection_o_allocation(1, (32 * 128)),
        M: 1,
    };
    let free = RawBatchInvarianceFree { b: i as int };
    assert(raw_batch_invariance_raw_pre(left, right, free)) by {
        reveal(row_projection_o_allocation);
        assert forall|r: int| 0 <= r < rows implies
            (#[trigger] input_x[r]).len() == (32 * 128) by {};
        assert forall|r0: int, r1: int|
            0 <= r0 < 1 && 0 <= r1 < (32 * 128) implies
            #[trigger] left.x[i as int + r0][r1]
                == right.x[r0][r1] by {
            assert(r0 == 0);
        };
    }
    raw_batch_invariance_certificate(left, right, free);
    let left_after = raw_execute(left);
    let right_after = raw_execute(right);
    assert(raw_batch_invariance_raw_post(left_after, right_after, free));
    reveal(raw_batch_invariance_raw_post);
    reveal(raw_execute);
    assert(left_after.M == rows as int);
    assert(right_after.M == 1);

    assert(0 <= i as int && i as int + 1 <= left_after.M);
    assert forall|c: int| 0 <= c < (32 * 128) implies
        (#[trigger] left_after.o[i as int][c])
            == right_after.o[0][c] by {
        assert(0 <= 0 < ((free.b + 1) - free.b));
        assert(0 <= c < (32 * 128));
        assert(left_after.o[free.b + 0][0 + c]
            == right_after.o[0 as int][0 + c]);
    };
    assert(left_after.o[i as int]
        =~= right_after.o[0]);
    reveal(row_projection_repr);
    assert(row_projection_repr(input_x, input_w, input_eps)[i as int]
        == left_after.o[i as int]);
    assert(row_projection_repr(seq![input_x[i as int]], input_w, input_eps)[0]
        == right_after.o[0]);
    assert(row_projection_repr(seq![input_x[i as int]], input_w, input_eps)
        =~= seq![row_projection_repr(input_x, input_w, input_eps)[i as int]]);
}

// The engine may use the mapped representation as its total row-local
// semantics.  For every valid rectangular launch, this checked theorem shows
// that it is exactly the generated raw whole-launch representation.
pub proof fn row_projection_launch_equivalence(
    input_x: Tensor2D,
    input_w: Tensor1D,
    input_eps: Scalar,
    rows: nat,
)
    requires
        TS::tensor2d_shape(input_x, rows, (32 * 128)),
        input_w.len() == 128,
        forall|row: nat| row < rows ==>
            #[trigger] row_projection_domain(input_x, input_w, input_eps, rows, row),
    ensures
        row_projection_repr(input_x, input_w, input_eps)
            == row_projection_mapped_repr(input_x, input_w, input_eps),
{
    assert forall|_row: int| 0 <= _row < rows implies
        (#[trigger] row_projection_repr(input_x, input_w, input_eps)[_row])
            == row_projection_mapped_repr(input_x, input_w, input_eps)[_row] by {
        row_projection_certificate(input_x, input_w, input_eps, rows,  _row as nat);
        reveal(row_projection_mapped_repr);
        assert(row_projection_repr(seq![input_x[_row]], input_w, input_eps)[0]
            == row_projection_repr(input_x, input_w, input_eps)[_row]);
    };
    assert(row_projection_repr(input_x, input_w, input_eps)
        =~= row_projection_mapped_repr(input_x, input_w, input_eps));
}

} // verus!
}

pub mod geometry_D_256_H_4 {
use super::*;
verus! {
// Abstract interface for ONE fixed, separately qualified deployment.
// Alternative implementations prove this same theory; their outputs
// are not equated. See the separate implementation proof records.
// Raw ContractIR lowering for gemma_head_rms_norm_kernel

pub open spec fn raw_batch_invariance_cdiv(numerator: int, denominator: int) -> int {
    (numerator + denominator - 1) / denominator
}

pub struct RawSide {
    pub x: Seq<Seq<Scalar>>,
    pub w: Seq<Scalar>,
    pub o: Seq<Seq<Scalar>>,
    pub eps: Scalar,
    pub M: int,
}

pub struct RawBatchInvarianceFree {
    pub b: int,
}


pub uninterp spec fn raw_o_cell(before: RawSide, _i0: int, _i1: int) -> Scalar;

pub open spec fn raw_o_after(before: RawSide)
    -> Seq<Seq<Scalar>>
{
    Seq::new(before.o.len(), |_i0: int| Seq::new(before.o[_i0].len(), |_i1: int| raw_o_cell(before, _i0, _i1)))
}

pub open spec fn raw_execute(before: RawSide) -> RawSide {
    RawSide {
        x: before.x,
        w: before.w,
        o: raw_o_after(before),
        eps: before.eps,
        M: before.M,
    }
}

pub open spec fn raw_batch_invariance_raw_pre(
    left: RawSide,
    right: RawSide,
    free: RawBatchInvarianceFree,
) -> bool {
    &&& 0 <= left.M
    &&& 0 <= (4 * 256)
    &&& left.x.len() as int == left.M
    &&& forall|_s0: int| 0 <= _s0 < left.x.len() as int ==> (#[trigger] left.x[_s0]).len() as int == (4 * 256)
    &&& 0 <= 256
    &&& left.w.len() as int == 256
    &&& left.o.len() as int == left.M
    &&& forall|_s0: int| 0 <= _s0 < left.o.len() as int ==> (#[trigger] left.o[_s0]).len() as int == (4 * 256)
    &&& 0 <= right.M
    &&& right.x.len() as int == right.M
    &&& forall|_s0: int| 0 <= _s0 < right.x.len() as int ==> (#[trigger] right.x[_s0]).len() as int == (4 * 256)
    &&& right.w.len() as int == 256
    &&& right.o.len() as int == right.M
    &&& forall|_s0: int| 0 <= _s0 < right.o.len() as int ==> (#[trigger] right.o[_s0]).len() as int == (4 * 256)
    &&& left.eps == right.eps
    &&& right.M == 1
    &&& free.b >= 0
    &&& free.b < left.M
    &&& (0 <= free.b && free.b <= (free.b + 1) && (free.b + 1) <= left.M && 0 <= 0 && 0 <= 1 && 1 <= right.M && ((free.b + 1) - free.b) == (1 - 0) && 0 <= 0 && 0 <= (4 * 256) && (4 * 256) <= (4 * 256) && 0 <= 0 && 0 <= (4 * 256) && (4 * 256) <= (4 * 256) && ((4 * 256) - 0) == ((4 * 256) - 0) && forall|_r0: int, _r1: int| 0 <= _r0 < ((free.b + 1) - free.b) && 0 <= _r1 < ((4 * 256) - 0) ==> #[trigger] left.x[free.b + _r0][0 + _r1] == right.x[0 + _r0][0 + _r1])
    &&& (0 <= 0 && 0 <= 256 && 256 <= 256 && 0 <= 0 && 0 <= 256 && 256 <= 256 && (256 - 0) == (256 - 0) && forall|_r0: int| 0 <= _r0 < (256 - 0) ==> #[trigger] left.w[0 + _r0] == right.w[0 + _r0])
}

pub open spec fn raw_batch_invariance_raw_post(
    left: RawSide,
    right: RawSide,
    free: RawBatchInvarianceFree,
) -> bool {
    &&& (0 <= free.b && free.b <= (free.b + 1) && (free.b + 1) <= left.M && 0 <= 0 && 0 <= 1 && 1 <= right.M && ((free.b + 1) - free.b) == (1 - 0) && 0 <= 0 && 0 <= (4 * 256) && (4 * 256) <= (4 * 256) && 0 <= 0 && 0 <= (4 * 256) && (4 * 256) <= (4 * 256) && ((4 * 256) - 0) == ((4 * 256) - 0) && forall|_r0: int, _r1: int| 0 <= _r0 < ((free.b + 1) - free.b) && 0 <= _r1 < ((4 * 256) - 0) ==> #[trigger] left.o[free.b + _r0][0 + _r1] == right.o[0 + _r0][0 + _r1])
}

// Trusted import of the relational theorem proved for the source and
// specialization named above.  The generated execute function preserves
// launch metadata and allocation shape; only written output cells are opaque.
#[verifier::external_body]
pub proof fn raw_batch_invariance_certificate(
    left: RawSide,
    right: RawSide,
    free: RawBatchInvarianceFree,
)
    requires raw_batch_invariance_raw_pre(left, right, free),
    ensures raw_batch_invariance_raw_post(
        raw_execute(left), raw_execute(right), free,
    ),
{
    unreachable!()
}

// BEGIN CHECKED RECTANGULAR ADAPTER

// Canonical framework values for the raw launch semantics.  Each pre-launch
// output is a generated rectangular allocation with the exact declared shape;
// the generated execute function replaces every logical output cell.
pub open spec fn row_projection_o_allocation(
    rows: nat,
    cols: nat,
) -> Tensor2D {
    Seq::new(rows, |_row: int| Seq::new(cols, |_col: int|
        generated_kernel_allocation_cell()))
}

pub open spec fn row_projection_repr(
    input_x: Tensor2D,
    input_w: Tensor1D,
    input_eps: Scalar,
) -> Tensor2D {
    raw_o_after(RawSide {
        x: input_x,
        w: input_w,
        eps: input_eps,
        o: row_projection_o_allocation(input_x.len(), (4 * 256)),
        M: input_x.len() as int,
    })
}

pub open spec fn row_projection_mapped_repr(
    input_x: Tensor2D,
    input_w: Tensor1D,
    input_eps: Scalar,
) -> Tensor2D {
    Seq::new(input_x.len(), |_row: int|
        row_projection_repr(seq![input_x[_row]], input_w, input_eps)[0])
}

// Exact source-annotation domain at the chosen projection. No domain
// policy table weakens or interprets the source predicate.
pub open spec fn row_projection_domain(
    input_x: Tensor2D,
    input_w: Tensor1D,
    input_eps: Scalar,
    rows: nat,
    i: nat,
) -> bool {
    let left = RawSide { x: input_x,
        w: input_w,
        eps: input_eps,
        o: row_projection_o_allocation(rows, (4 * 256)),
        M: rows as int };
    let right = RawSide { x: seq![input_x[i as int]],
        w: input_w,
        eps: input_eps,
        o: row_projection_o_allocation(1, (4 * 256)),
        M: 1 };
    let free = RawBatchInvarianceFree { b: i as int };
    raw_batch_invariance_raw_pre(left, right, free)
}


// Checked rectangular instantiation of the generated raw ContractIR theorem.
pub proof fn row_projection_certificate(
    input_x: Tensor2D,
    input_w: Tensor1D,
    input_eps: Scalar,
    rows: nat,
    i: nat,
)
    requires
        TS::tensor2d_shape(input_x, rows, (4 * 256)),
        input_w.len() == 256,
        row_projection_domain(input_x, input_w, input_eps, rows, i),
        i < rows,
    ensures
        row_projection_repr(seq![input_x[i as int]], input_w, input_eps)
            == seq![row_projection_repr(input_x, input_w, input_eps)[i as int]],
{
    reveal(row_projection_domain);

    let left = RawSide {
        x: input_x,
        w: input_w,
        eps: input_eps,
        o: row_projection_o_allocation(rows, (4 * 256)),
        M: rows as int,
    };
    let right = RawSide {
        x: seq![input_x[i as int]],
        w: input_w,
        eps: input_eps,
        o: row_projection_o_allocation(1, (4 * 256)),
        M: 1,
    };
    let free = RawBatchInvarianceFree { b: i as int };
    assert(raw_batch_invariance_raw_pre(left, right, free)) by {
        reveal(row_projection_o_allocation);
        assert forall|r: int| 0 <= r < rows implies
            (#[trigger] input_x[r]).len() == (4 * 256) by {};
        assert forall|r0: int, r1: int|
            0 <= r0 < 1 && 0 <= r1 < (4 * 256) implies
            #[trigger] left.x[i as int + r0][r1]
                == right.x[r0][r1] by {
            assert(r0 == 0);
        };
    }
    raw_batch_invariance_certificate(left, right, free);
    let left_after = raw_execute(left);
    let right_after = raw_execute(right);
    assert(raw_batch_invariance_raw_post(left_after, right_after, free));
    reveal(raw_batch_invariance_raw_post);
    reveal(raw_execute);
    assert(left_after.M == rows as int);
    assert(right_after.M == 1);

    assert(0 <= i as int && i as int + 1 <= left_after.M);
    assert forall|c: int| 0 <= c < (4 * 256) implies
        (#[trigger] left_after.o[i as int][c])
            == right_after.o[0][c] by {
        assert(0 <= 0 < ((free.b + 1) - free.b));
        assert(0 <= c < (4 * 256));
        assert(left_after.o[free.b + 0][0 + c]
            == right_after.o[0 as int][0 + c]);
    };
    assert(left_after.o[i as int]
        =~= right_after.o[0]);
    reveal(row_projection_repr);
    assert(row_projection_repr(input_x, input_w, input_eps)[i as int]
        == left_after.o[i as int]);
    assert(row_projection_repr(seq![input_x[i as int]], input_w, input_eps)[0]
        == right_after.o[0]);
    assert(row_projection_repr(seq![input_x[i as int]], input_w, input_eps)
        =~= seq![row_projection_repr(input_x, input_w, input_eps)[i as int]]);
}

// The engine may use the mapped representation as its total row-local
// semantics.  For every valid rectangular launch, this checked theorem shows
// that it is exactly the generated raw whole-launch representation.
pub proof fn row_projection_launch_equivalence(
    input_x: Tensor2D,
    input_w: Tensor1D,
    input_eps: Scalar,
    rows: nat,
)
    requires
        TS::tensor2d_shape(input_x, rows, (4 * 256)),
        input_w.len() == 256,
        forall|row: nat| row < rows ==>
            #[trigger] row_projection_domain(input_x, input_w, input_eps, rows, row),
    ensures
        row_projection_repr(input_x, input_w, input_eps)
            == row_projection_mapped_repr(input_x, input_w, input_eps),
{
    assert forall|_row: int| 0 <= _row < rows implies
        (#[trigger] row_projection_repr(input_x, input_w, input_eps)[_row])
            == row_projection_mapped_repr(input_x, input_w, input_eps)[_row] by {
        row_projection_certificate(input_x, input_w, input_eps, rows,  _row as nat);
        reveal(row_projection_mapped_repr);
        assert(row_projection_repr(seq![input_x[_row]], input_w, input_eps)[0]
            == row_projection_repr(input_x, input_w, input_eps)[_row]);
    };
    assert(row_projection_repr(input_x, input_w, input_eps)
        =~= row_projection_mapped_repr(input_x, input_w, input_eps));
}

} // verus!
}

pub mod geometry_D_256_H_8 {
use super::*;
verus! {
// Abstract interface for ONE fixed, separately qualified deployment.
// Alternative implementations prove this same theory; their outputs
// are not equated. See the separate implementation proof records.
// Raw ContractIR lowering for gemma_head_rms_norm_kernel

pub open spec fn raw_batch_invariance_cdiv(numerator: int, denominator: int) -> int {
    (numerator + denominator - 1) / denominator
}

pub struct RawSide {
    pub x: Seq<Seq<Scalar>>,
    pub w: Seq<Scalar>,
    pub o: Seq<Seq<Scalar>>,
    pub eps: Scalar,
    pub M: int,
}

pub struct RawBatchInvarianceFree {
    pub b: int,
}


pub uninterp spec fn raw_o_cell(before: RawSide, _i0: int, _i1: int) -> Scalar;

pub open spec fn raw_o_after(before: RawSide)
    -> Seq<Seq<Scalar>>
{
    Seq::new(before.o.len(), |_i0: int| Seq::new(before.o[_i0].len(), |_i1: int| raw_o_cell(before, _i0, _i1)))
}

pub open spec fn raw_execute(before: RawSide) -> RawSide {
    RawSide {
        x: before.x,
        w: before.w,
        o: raw_o_after(before),
        eps: before.eps,
        M: before.M,
    }
}

pub open spec fn raw_batch_invariance_raw_pre(
    left: RawSide,
    right: RawSide,
    free: RawBatchInvarianceFree,
) -> bool {
    &&& 0 <= left.M
    &&& 0 <= (8 * 256)
    &&& left.x.len() as int == left.M
    &&& forall|_s0: int| 0 <= _s0 < left.x.len() as int ==> (#[trigger] left.x[_s0]).len() as int == (8 * 256)
    &&& 0 <= 256
    &&& left.w.len() as int == 256
    &&& left.o.len() as int == left.M
    &&& forall|_s0: int| 0 <= _s0 < left.o.len() as int ==> (#[trigger] left.o[_s0]).len() as int == (8 * 256)
    &&& 0 <= right.M
    &&& right.x.len() as int == right.M
    &&& forall|_s0: int| 0 <= _s0 < right.x.len() as int ==> (#[trigger] right.x[_s0]).len() as int == (8 * 256)
    &&& right.w.len() as int == 256
    &&& right.o.len() as int == right.M
    &&& forall|_s0: int| 0 <= _s0 < right.o.len() as int ==> (#[trigger] right.o[_s0]).len() as int == (8 * 256)
    &&& left.eps == right.eps
    &&& right.M == 1
    &&& free.b >= 0
    &&& free.b < left.M
    &&& (0 <= free.b && free.b <= (free.b + 1) && (free.b + 1) <= left.M && 0 <= 0 && 0 <= 1 && 1 <= right.M && ((free.b + 1) - free.b) == (1 - 0) && 0 <= 0 && 0 <= (8 * 256) && (8 * 256) <= (8 * 256) && 0 <= 0 && 0 <= (8 * 256) && (8 * 256) <= (8 * 256) && ((8 * 256) - 0) == ((8 * 256) - 0) && forall|_r0: int, _r1: int| 0 <= _r0 < ((free.b + 1) - free.b) && 0 <= _r1 < ((8 * 256) - 0) ==> #[trigger] left.x[free.b + _r0][0 + _r1] == right.x[0 + _r0][0 + _r1])
    &&& (0 <= 0 && 0 <= 256 && 256 <= 256 && 0 <= 0 && 0 <= 256 && 256 <= 256 && (256 - 0) == (256 - 0) && forall|_r0: int| 0 <= _r0 < (256 - 0) ==> #[trigger] left.w[0 + _r0] == right.w[0 + _r0])
}

pub open spec fn raw_batch_invariance_raw_post(
    left: RawSide,
    right: RawSide,
    free: RawBatchInvarianceFree,
) -> bool {
    &&& (0 <= free.b && free.b <= (free.b + 1) && (free.b + 1) <= left.M && 0 <= 0 && 0 <= 1 && 1 <= right.M && ((free.b + 1) - free.b) == (1 - 0) && 0 <= 0 && 0 <= (8 * 256) && (8 * 256) <= (8 * 256) && 0 <= 0 && 0 <= (8 * 256) && (8 * 256) <= (8 * 256) && ((8 * 256) - 0) == ((8 * 256) - 0) && forall|_r0: int, _r1: int| 0 <= _r0 < ((free.b + 1) - free.b) && 0 <= _r1 < ((8 * 256) - 0) ==> #[trigger] left.o[free.b + _r0][0 + _r1] == right.o[0 + _r0][0 + _r1])
}

// Trusted import of the relational theorem proved for the source and
// specialization named above.  The generated execute function preserves
// launch metadata and allocation shape; only written output cells are opaque.
#[verifier::external_body]
pub proof fn raw_batch_invariance_certificate(
    left: RawSide,
    right: RawSide,
    free: RawBatchInvarianceFree,
)
    requires raw_batch_invariance_raw_pre(left, right, free),
    ensures raw_batch_invariance_raw_post(
        raw_execute(left), raw_execute(right), free,
    ),
{
    unreachable!()
}

// BEGIN CHECKED RECTANGULAR ADAPTER

// Canonical framework values for the raw launch semantics.  Each pre-launch
// output is a generated rectangular allocation with the exact declared shape;
// the generated execute function replaces every logical output cell.
pub open spec fn row_projection_o_allocation(
    rows: nat,
    cols: nat,
) -> Tensor2D {
    Seq::new(rows, |_row: int| Seq::new(cols, |_col: int|
        generated_kernel_allocation_cell()))
}

pub open spec fn row_projection_repr(
    input_x: Tensor2D,
    input_w: Tensor1D,
    input_eps: Scalar,
) -> Tensor2D {
    raw_o_after(RawSide {
        x: input_x,
        w: input_w,
        eps: input_eps,
        o: row_projection_o_allocation(input_x.len(), (8 * 256)),
        M: input_x.len() as int,
    })
}

pub open spec fn row_projection_mapped_repr(
    input_x: Tensor2D,
    input_w: Tensor1D,
    input_eps: Scalar,
) -> Tensor2D {
    Seq::new(input_x.len(), |_row: int|
        row_projection_repr(seq![input_x[_row]], input_w, input_eps)[0])
}

// Exact source-annotation domain at the chosen projection. No domain
// policy table weakens or interprets the source predicate.
pub open spec fn row_projection_domain(
    input_x: Tensor2D,
    input_w: Tensor1D,
    input_eps: Scalar,
    rows: nat,
    i: nat,
) -> bool {
    let left = RawSide { x: input_x,
        w: input_w,
        eps: input_eps,
        o: row_projection_o_allocation(rows, (8 * 256)),
        M: rows as int };
    let right = RawSide { x: seq![input_x[i as int]],
        w: input_w,
        eps: input_eps,
        o: row_projection_o_allocation(1, (8 * 256)),
        M: 1 };
    let free = RawBatchInvarianceFree { b: i as int };
    raw_batch_invariance_raw_pre(left, right, free)
}


// Checked rectangular instantiation of the generated raw ContractIR theorem.
pub proof fn row_projection_certificate(
    input_x: Tensor2D,
    input_w: Tensor1D,
    input_eps: Scalar,
    rows: nat,
    i: nat,
)
    requires
        TS::tensor2d_shape(input_x, rows, (8 * 256)),
        input_w.len() == 256,
        row_projection_domain(input_x, input_w, input_eps, rows, i),
        i < rows,
    ensures
        row_projection_repr(seq![input_x[i as int]], input_w, input_eps)
            == seq![row_projection_repr(input_x, input_w, input_eps)[i as int]],
{
    reveal(row_projection_domain);

    let left = RawSide {
        x: input_x,
        w: input_w,
        eps: input_eps,
        o: row_projection_o_allocation(rows, (8 * 256)),
        M: rows as int,
    };
    let right = RawSide {
        x: seq![input_x[i as int]],
        w: input_w,
        eps: input_eps,
        o: row_projection_o_allocation(1, (8 * 256)),
        M: 1,
    };
    let free = RawBatchInvarianceFree { b: i as int };
    assert(raw_batch_invariance_raw_pre(left, right, free)) by {
        reveal(row_projection_o_allocation);
        assert forall|r: int| 0 <= r < rows implies
            (#[trigger] input_x[r]).len() == (8 * 256) by {};
        assert forall|r0: int, r1: int|
            0 <= r0 < 1 && 0 <= r1 < (8 * 256) implies
            #[trigger] left.x[i as int + r0][r1]
                == right.x[r0][r1] by {
            assert(r0 == 0);
        };
    }
    raw_batch_invariance_certificate(left, right, free);
    let left_after = raw_execute(left);
    let right_after = raw_execute(right);
    assert(raw_batch_invariance_raw_post(left_after, right_after, free));
    reveal(raw_batch_invariance_raw_post);
    reveal(raw_execute);
    assert(left_after.M == rows as int);
    assert(right_after.M == 1);

    assert(0 <= i as int && i as int + 1 <= left_after.M);
    assert forall|c: int| 0 <= c < (8 * 256) implies
        (#[trigger] left_after.o[i as int][c])
            == right_after.o[0][c] by {
        assert(0 <= 0 < ((free.b + 1) - free.b));
        assert(0 <= c < (8 * 256));
        assert(left_after.o[free.b + 0][0 + c]
            == right_after.o[0 as int][0 + c]);
    };
    assert(left_after.o[i as int]
        =~= right_after.o[0]);
    reveal(row_projection_repr);
    assert(row_projection_repr(input_x, input_w, input_eps)[i as int]
        == left_after.o[i as int]);
    assert(row_projection_repr(seq![input_x[i as int]], input_w, input_eps)[0]
        == right_after.o[0]);
    assert(row_projection_repr(seq![input_x[i as int]], input_w, input_eps)
        =~= seq![row_projection_repr(input_x, input_w, input_eps)[i as int]]);
}

// The engine may use the mapped representation as its total row-local
// semantics.  For every valid rectangular launch, this checked theorem shows
// that it is exactly the generated raw whole-launch representation.
pub proof fn row_projection_launch_equivalence(
    input_x: Tensor2D,
    input_w: Tensor1D,
    input_eps: Scalar,
    rows: nat,
)
    requires
        TS::tensor2d_shape(input_x, rows, (8 * 256)),
        input_w.len() == 256,
        forall|row: nat| row < rows ==>
            #[trigger] row_projection_domain(input_x, input_w, input_eps, rows, row),
    ensures
        row_projection_repr(input_x, input_w, input_eps)
            == row_projection_mapped_repr(input_x, input_w, input_eps),
{
    assert forall|_row: int| 0 <= _row < rows implies
        (#[trigger] row_projection_repr(input_x, input_w, input_eps)[_row])
            == row_projection_mapped_repr(input_x, input_w, input_eps)[_row] by {
        row_projection_certificate(input_x, input_w, input_eps, rows,  _row as nat);
        reveal(row_projection_mapped_repr);
        assert(row_projection_repr(seq![input_x[_row]], input_w, input_eps)[0]
            == row_projection_repr(input_x, input_w, input_eps)[_row]);
    };
    assert(row_projection_repr(input_x, input_w, input_eps)
        =~= row_projection_mapped_repr(input_x, input_w, input_eps));
}

} // verus!
}

pub mod geometry_D_256_H_16 {
use super::*;
verus! {
// Abstract interface for ONE fixed, separately qualified deployment.
// Alternative implementations prove this same theory; their outputs
// are not equated. See the separate implementation proof records.
// Raw ContractIR lowering for gemma_head_rms_norm_kernel

pub open spec fn raw_batch_invariance_cdiv(numerator: int, denominator: int) -> int {
    (numerator + denominator - 1) / denominator
}

pub struct RawSide {
    pub x: Seq<Seq<Scalar>>,
    pub w: Seq<Scalar>,
    pub o: Seq<Seq<Scalar>>,
    pub eps: Scalar,
    pub M: int,
}

pub struct RawBatchInvarianceFree {
    pub b: int,
}


pub uninterp spec fn raw_o_cell(before: RawSide, _i0: int, _i1: int) -> Scalar;

pub open spec fn raw_o_after(before: RawSide)
    -> Seq<Seq<Scalar>>
{
    Seq::new(before.o.len(), |_i0: int| Seq::new(before.o[_i0].len(), |_i1: int| raw_o_cell(before, _i0, _i1)))
}

pub open spec fn raw_execute(before: RawSide) -> RawSide {
    RawSide {
        x: before.x,
        w: before.w,
        o: raw_o_after(before),
        eps: before.eps,
        M: before.M,
    }
}

pub open spec fn raw_batch_invariance_raw_pre(
    left: RawSide,
    right: RawSide,
    free: RawBatchInvarianceFree,
) -> bool {
    &&& 0 <= left.M
    &&& 0 <= (16 * 256)
    &&& left.x.len() as int == left.M
    &&& forall|_s0: int| 0 <= _s0 < left.x.len() as int ==> (#[trigger] left.x[_s0]).len() as int == (16 * 256)
    &&& 0 <= 256
    &&& left.w.len() as int == 256
    &&& left.o.len() as int == left.M
    &&& forall|_s0: int| 0 <= _s0 < left.o.len() as int ==> (#[trigger] left.o[_s0]).len() as int == (16 * 256)
    &&& 0 <= right.M
    &&& right.x.len() as int == right.M
    &&& forall|_s0: int| 0 <= _s0 < right.x.len() as int ==> (#[trigger] right.x[_s0]).len() as int == (16 * 256)
    &&& right.w.len() as int == 256
    &&& right.o.len() as int == right.M
    &&& forall|_s0: int| 0 <= _s0 < right.o.len() as int ==> (#[trigger] right.o[_s0]).len() as int == (16 * 256)
    &&& left.eps == right.eps
    &&& right.M == 1
    &&& free.b >= 0
    &&& free.b < left.M
    &&& (0 <= free.b && free.b <= (free.b + 1) && (free.b + 1) <= left.M && 0 <= 0 && 0 <= 1 && 1 <= right.M && ((free.b + 1) - free.b) == (1 - 0) && 0 <= 0 && 0 <= (16 * 256) && (16 * 256) <= (16 * 256) && 0 <= 0 && 0 <= (16 * 256) && (16 * 256) <= (16 * 256) && ((16 * 256) - 0) == ((16 * 256) - 0) && forall|_r0: int, _r1: int| 0 <= _r0 < ((free.b + 1) - free.b) && 0 <= _r1 < ((16 * 256) - 0) ==> #[trigger] left.x[free.b + _r0][0 + _r1] == right.x[0 + _r0][0 + _r1])
    &&& (0 <= 0 && 0 <= 256 && 256 <= 256 && 0 <= 0 && 0 <= 256 && 256 <= 256 && (256 - 0) == (256 - 0) && forall|_r0: int| 0 <= _r0 < (256 - 0) ==> #[trigger] left.w[0 + _r0] == right.w[0 + _r0])
}

pub open spec fn raw_batch_invariance_raw_post(
    left: RawSide,
    right: RawSide,
    free: RawBatchInvarianceFree,
) -> bool {
    &&& (0 <= free.b && free.b <= (free.b + 1) && (free.b + 1) <= left.M && 0 <= 0 && 0 <= 1 && 1 <= right.M && ((free.b + 1) - free.b) == (1 - 0) && 0 <= 0 && 0 <= (16 * 256) && (16 * 256) <= (16 * 256) && 0 <= 0 && 0 <= (16 * 256) && (16 * 256) <= (16 * 256) && ((16 * 256) - 0) == ((16 * 256) - 0) && forall|_r0: int, _r1: int| 0 <= _r0 < ((free.b + 1) - free.b) && 0 <= _r1 < ((16 * 256) - 0) ==> #[trigger] left.o[free.b + _r0][0 + _r1] == right.o[0 + _r0][0 + _r1])
}

// Trusted import of the relational theorem proved for the source and
// specialization named above.  The generated execute function preserves
// launch metadata and allocation shape; only written output cells are opaque.
#[verifier::external_body]
pub proof fn raw_batch_invariance_certificate(
    left: RawSide,
    right: RawSide,
    free: RawBatchInvarianceFree,
)
    requires raw_batch_invariance_raw_pre(left, right, free),
    ensures raw_batch_invariance_raw_post(
        raw_execute(left), raw_execute(right), free,
    ),
{
    unreachable!()
}

// BEGIN CHECKED RECTANGULAR ADAPTER

// Canonical framework values for the raw launch semantics.  Each pre-launch
// output is a generated rectangular allocation with the exact declared shape;
// the generated execute function replaces every logical output cell.
pub open spec fn row_projection_o_allocation(
    rows: nat,
    cols: nat,
) -> Tensor2D {
    Seq::new(rows, |_row: int| Seq::new(cols, |_col: int|
        generated_kernel_allocation_cell()))
}

pub open spec fn row_projection_repr(
    input_x: Tensor2D,
    input_w: Tensor1D,
    input_eps: Scalar,
) -> Tensor2D {
    raw_o_after(RawSide {
        x: input_x,
        w: input_w,
        eps: input_eps,
        o: row_projection_o_allocation(input_x.len(), (16 * 256)),
        M: input_x.len() as int,
    })
}

pub open spec fn row_projection_mapped_repr(
    input_x: Tensor2D,
    input_w: Tensor1D,
    input_eps: Scalar,
) -> Tensor2D {
    Seq::new(input_x.len(), |_row: int|
        row_projection_repr(seq![input_x[_row]], input_w, input_eps)[0])
}

// Exact source-annotation domain at the chosen projection. No domain
// policy table weakens or interprets the source predicate.
pub open spec fn row_projection_domain(
    input_x: Tensor2D,
    input_w: Tensor1D,
    input_eps: Scalar,
    rows: nat,
    i: nat,
) -> bool {
    let left = RawSide { x: input_x,
        w: input_w,
        eps: input_eps,
        o: row_projection_o_allocation(rows, (16 * 256)),
        M: rows as int };
    let right = RawSide { x: seq![input_x[i as int]],
        w: input_w,
        eps: input_eps,
        o: row_projection_o_allocation(1, (16 * 256)),
        M: 1 };
    let free = RawBatchInvarianceFree { b: i as int };
    raw_batch_invariance_raw_pre(left, right, free)
}


// Checked rectangular instantiation of the generated raw ContractIR theorem.
pub proof fn row_projection_certificate(
    input_x: Tensor2D,
    input_w: Tensor1D,
    input_eps: Scalar,
    rows: nat,
    i: nat,
)
    requires
        TS::tensor2d_shape(input_x, rows, (16 * 256)),
        input_w.len() == 256,
        row_projection_domain(input_x, input_w, input_eps, rows, i),
        i < rows,
    ensures
        row_projection_repr(seq![input_x[i as int]], input_w, input_eps)
            == seq![row_projection_repr(input_x, input_w, input_eps)[i as int]],
{
    reveal(row_projection_domain);

    let left = RawSide {
        x: input_x,
        w: input_w,
        eps: input_eps,
        o: row_projection_o_allocation(rows, (16 * 256)),
        M: rows as int,
    };
    let right = RawSide {
        x: seq![input_x[i as int]],
        w: input_w,
        eps: input_eps,
        o: row_projection_o_allocation(1, (16 * 256)),
        M: 1,
    };
    let free = RawBatchInvarianceFree { b: i as int };
    assert(raw_batch_invariance_raw_pre(left, right, free)) by {
        reveal(row_projection_o_allocation);
        assert forall|r: int| 0 <= r < rows implies
            (#[trigger] input_x[r]).len() == (16 * 256) by {};
        assert forall|r0: int, r1: int|
            0 <= r0 < 1 && 0 <= r1 < (16 * 256) implies
            #[trigger] left.x[i as int + r0][r1]
                == right.x[r0][r1] by {
            assert(r0 == 0);
        };
    }
    raw_batch_invariance_certificate(left, right, free);
    let left_after = raw_execute(left);
    let right_after = raw_execute(right);
    assert(raw_batch_invariance_raw_post(left_after, right_after, free));
    reveal(raw_batch_invariance_raw_post);
    reveal(raw_execute);
    assert(left_after.M == rows as int);
    assert(right_after.M == 1);

    assert(0 <= i as int && i as int + 1 <= left_after.M);
    assert forall|c: int| 0 <= c < (16 * 256) implies
        (#[trigger] left_after.o[i as int][c])
            == right_after.o[0][c] by {
        assert(0 <= 0 < ((free.b + 1) - free.b));
        assert(0 <= c < (16 * 256));
        assert(left_after.o[free.b + 0][0 + c]
            == right_after.o[0 as int][0 + c]);
    };
    assert(left_after.o[i as int]
        =~= right_after.o[0]);
    reveal(row_projection_repr);
    assert(row_projection_repr(input_x, input_w, input_eps)[i as int]
        == left_after.o[i as int]);
    assert(row_projection_repr(seq![input_x[i as int]], input_w, input_eps)[0]
        == right_after.o[0]);
    assert(row_projection_repr(seq![input_x[i as int]], input_w, input_eps)
        =~= seq![row_projection_repr(input_x, input_w, input_eps)[i as int]]);
}

// The engine may use the mapped representation as its total row-local
// semantics.  For every valid rectangular launch, this checked theorem shows
// that it is exactly the generated raw whole-launch representation.
pub proof fn row_projection_launch_equivalence(
    input_x: Tensor2D,
    input_w: Tensor1D,
    input_eps: Scalar,
    rows: nat,
)
    requires
        TS::tensor2d_shape(input_x, rows, (16 * 256)),
        input_w.len() == 256,
        forall|row: nat| row < rows ==>
            #[trigger] row_projection_domain(input_x, input_w, input_eps, rows, row),
    ensures
        row_projection_repr(input_x, input_w, input_eps)
            == row_projection_mapped_repr(input_x, input_w, input_eps),
{
    assert forall|_row: int| 0 <= _row < rows implies
        (#[trigger] row_projection_repr(input_x, input_w, input_eps)[_row])
            == row_projection_mapped_repr(input_x, input_w, input_eps)[_row] by {
        row_projection_certificate(input_x, input_w, input_eps, rows,  _row as nat);
        reveal(row_projection_mapped_repr);
        assert(row_projection_repr(seq![input_x[_row]], input_w, input_eps)[0]
            == row_projection_repr(input_x, input_w, input_eps)[_row]);
    };
    assert(row_projection_repr(input_x, input_w, input_eps)
        =~= row_projection_mapped_repr(input_x, input_w, input_eps));
}

} // verus!
}

// BEGIN CHECKED GEOMETRY DISPATCH
verus! {
pub open spec fn geometry_valid(D: nat, H: nat) -> bool {
    if D == 128 && H == 16 {
        true
    } else if D == 128 && H == 32 {
        true
    } else if D == 256 && H == 4 {
        true
    } else if D == 256 && H == 8 {
        true
    } else if D == 256 && H == 16 {
        true
    } else { false }
}

pub open spec fn launch_valid(input_x: Tensor2D, input_w: Tensor1D, input_eps: Scalar, D: nat, H: nat) -> bool {
    if D == 128 && H == 16 {
        (TS::tensor2d_shape(input_x, input_x.len(), (16 * 128)))
        && (input_w.len() == 128)
        && (forall|row: nat| row < input_x.len() ==>
            #[trigger] geometry_D_128_H_16::row_projection_domain(input_x, input_w, input_eps, input_x.len(), row))
    } else if D == 128 && H == 32 {
        (TS::tensor2d_shape(input_x, input_x.len(), (32 * 128)))
        && (input_w.len() == 128)
        && (forall|row: nat| row < input_x.len() ==>
            #[trigger] geometry_D_128_H_32::row_projection_domain(input_x, input_w, input_eps, input_x.len(), row))
    } else if D == 256 && H == 4 {
        (TS::tensor2d_shape(input_x, input_x.len(), (4 * 256)))
        && (input_w.len() == 256)
        && (forall|row: nat| row < input_x.len() ==>
            #[trigger] geometry_D_256_H_4::row_projection_domain(input_x, input_w, input_eps, input_x.len(), row))
    } else if D == 256 && H == 8 {
        (TS::tensor2d_shape(input_x, input_x.len(), (8 * 256)))
        && (input_w.len() == 256)
        && (forall|row: nat| row < input_x.len() ==>
            #[trigger] geometry_D_256_H_8::row_projection_domain(input_x, input_w, input_eps, input_x.len(), row))
    } else if D == 256 && H == 16 {
        (TS::tensor2d_shape(input_x, input_x.len(), (16 * 256)))
        && (input_w.len() == 256)
        && (forall|row: nat| row < input_x.len() ==>
            #[trigger] geometry_D_256_H_16::row_projection_domain(input_x, input_w, input_eps, input_x.len(), row))
    } else { false }
}

pub open spec fn raw_output(input_x: Tensor2D, input_w: Tensor1D, input_eps: Scalar, D: nat, H: nat) -> Option<Tensor2D> {
    if D == 128 && H == 16 {
        Some(geometry_D_128_H_16::row_projection_repr(input_x, input_w, input_eps))
    } else if D == 128 && H == 32 {
        Some(geometry_D_128_H_32::row_projection_repr(input_x, input_w, input_eps))
    } else if D == 256 && H == 4 {
        Some(geometry_D_256_H_4::row_projection_repr(input_x, input_w, input_eps))
    } else if D == 256 && H == 8 {
        Some(geometry_D_256_H_8::row_projection_repr(input_x, input_w, input_eps))
    } else if D == 256 && H == 16 {
        Some(geometry_D_256_H_16::row_projection_repr(input_x, input_w, input_eps))
    } else { None }
}

pub open spec fn mapped_output(input_x: Tensor2D, input_w: Tensor1D, input_eps: Scalar, D: nat, H: nat) -> Option<Tensor2D> {
    if D == 128 && H == 16 {
        Some(geometry_D_128_H_16::row_projection_mapped_repr(input_x, input_w, input_eps))
    } else if D == 128 && H == 32 {
        Some(geometry_D_128_H_32::row_projection_mapped_repr(input_x, input_w, input_eps))
    } else if D == 256 && H == 4 {
        Some(geometry_D_256_H_4::row_projection_mapped_repr(input_x, input_w, input_eps))
    } else if D == 256 && H == 8 {
        Some(geometry_D_256_H_8::row_projection_mapped_repr(input_x, input_w, input_eps))
    } else if D == 256 && H == 16 {
        Some(geometry_D_256_H_16::row_projection_mapped_repr(input_x, input_w, input_eps))
    } else { None }
}

// A public row map independent of the generated geometry module names.
pub open spec fn row_mapped_output(input_x: Tensor2D, input_w: Tensor1D, input_eps: Scalar, D: nat, H: nat) -> Option<Tensor2D> {
    if geometry_valid(D, H) { Some(Seq::new(input_x.len(), |row: int| raw_output(seq![input_x[row]], input_w, input_eps, D, H).unwrap()[0])) } else { None }
}

pub proof fn checked_row_map(input_x: Tensor2D, input_w: Tensor1D, input_eps: Scalar, D: nat, H: nat)
    ensures mapped_output(input_x, input_w, input_eps, D, H) == row_mapped_output(input_x, input_w, input_eps, D, H),
{
    let mapped = mapped_output(input_x, input_w, input_eps, D, H).unwrap();
    let row_map = row_mapped_output(input_x, input_w, input_eps, D, H).unwrap();
    if D == 128 && H == 16 {
        assert(mapped =~= row_map);
    } else if D == 128 && H == 32 {
        assert(mapped =~= row_map);
    } else if D == 256 && H == 4 {
        assert(mapped =~= row_map);
    } else if D == 256 && H == 8 {
        assert(mapped =~= row_map);
    } else if D == 256 && H == 16 {
        assert(mapped =~= row_map);
    } else {  }
}

pub proof fn checked_launch_equivalence(input_x: Tensor2D, input_w: Tensor1D, input_eps: Scalar, D: nat, H: nat)
    requires launch_valid(input_x, input_w, input_eps, D, H),
    ensures geometry_valid(D, H),
        raw_output(input_x, input_w, input_eps, D, H).is_some(),
        raw_output(input_x, input_w, input_eps, D, H) == mapped_output(input_x, input_w, input_eps, D, H),
        raw_output(input_x, input_w, input_eps, D, H) == row_mapped_output(input_x, input_w, input_eps, D, H),
{
    checked_row_map(input_x, input_w, input_eps, D, H);
    if D == 128 && H == 16 {
        geometry_D_128_H_16::row_projection_launch_equivalence(input_x, input_w, input_eps, input_x.len());
    } else if D == 128 && H == 32 {
        geometry_D_128_H_32::row_projection_launch_equivalence(input_x, input_w, input_eps, input_x.len());
    } else if D == 256 && H == 4 {
        geometry_D_256_H_4::row_projection_launch_equivalence(input_x, input_w, input_eps, input_x.len());
    } else if D == 256 && H == 8 {
        geometry_D_256_H_8::row_projection_launch_equivalence(input_x, input_w, input_eps, input_x.len());
    } else if D == 256 && H == 16 {
        geometry_D_256_H_16::row_projection_launch_equivalence(input_x, input_w, input_eps, input_x.len());
    } else { assert(false); }
}
} // verus!
