// @generated by scripts/verification/verify_rectangular_interfaces.py; DO NOT EDIT.
#![allow(non_snake_case)]
use vstd::prelude::*;
use crate::{boundary::scalar::{Scalar}, proof::tensor::types::{Tensor1D, Tensor2D, IntTensor1D}};
use crate::proof::tensor::shape as TS;
#[cfg(verus_only)]
use crate::boundary::backend_certificates::support::generated_kernel_allocation_cell;

verus! {
// Abstract interface for ONE fixed, separately qualified deployment.
// Alternative implementations prove this same theory; their outputs
// are not equated. See the separate implementation proof records.
// Raw ContractIR lowering for qkv_matmul_kernel

pub open spec fn raw_batch_invariance_cdiv(numerator: int, denominator: int) -> int {
    (numerator + denominator - 1) / denominator
}

pub struct RawSide {
    pub a: Seq<Seq<Scalar>>,
    pub wq: Seq<Seq<Scalar>>,
    pub wk: Seq<Seq<Scalar>>,
    pub wv: Seq<Seq<Scalar>>,
    pub oq: Seq<Seq<Scalar>>,
    pub ok: Seq<Seq<Scalar>>,
    pub ov: Seq<Seq<Scalar>>,
    pub K: int,
    pub KVN: int,
    pub M: int,
    pub QN: int,
}

pub struct RawBatchInvarianceFree {
    pub x: int,
}


pub uninterp spec fn raw_oq_cell(before: RawSide, _i0: int, _i1: int) -> Scalar;

pub open spec fn raw_oq_after(before: RawSide)
    -> Seq<Seq<Scalar>>
{
    Seq::new(before.oq.len(), |_i0: int| Seq::new(before.oq[_i0].len(), |_i1: int| raw_oq_cell(before, _i0, _i1)))
}

pub uninterp spec fn raw_ok_cell(before: RawSide, _i0: int, _i1: int) -> Scalar;

pub open spec fn raw_ok_after(before: RawSide)
    -> Seq<Seq<Scalar>>
{
    Seq::new(before.ok.len(), |_i0: int| Seq::new(before.ok[_i0].len(), |_i1: int| raw_ok_cell(before, _i0, _i1)))
}

pub uninterp spec fn raw_ov_cell(before: RawSide, _i0: int, _i1: int) -> Scalar;

pub open spec fn raw_ov_after(before: RawSide)
    -> Seq<Seq<Scalar>>
{
    Seq::new(before.ov.len(), |_i0: int| Seq::new(before.ov[_i0].len(), |_i1: int| raw_ov_cell(before, _i0, _i1)))
}

pub open spec fn raw_execute(before: RawSide) -> RawSide {
    RawSide {
        a: before.a,
        wq: before.wq,
        wk: before.wk,
        wv: before.wv,
        oq: raw_oq_after(before),
        ok: raw_ok_after(before),
        ov: raw_ov_after(before),
        K: before.K,
        KVN: before.KVN,
        M: before.M,
        QN: before.QN,
    }
}

pub open spec fn raw_batch_invariance_raw_pre(
    left: RawSide,
    right: RawSide,
    free: RawBatchInvarianceFree,
) -> bool {
    &&& 0 <= left.M
    &&& 0 <= left.K
    &&& left.a.len() as int == left.M
    &&& forall|_s0: int| 0 <= _s0 < left.a.len() as int ==> (#[trigger] left.a[_s0]).len() as int == left.K
    &&& 0 <= left.QN
    &&& left.wq.len() as int == left.K
    &&& forall|_s0: int| 0 <= _s0 < left.wq.len() as int ==> (#[trigger] left.wq[_s0]).len() as int == left.QN
    &&& 0 <= left.KVN
    &&& left.wk.len() as int == left.K
    &&& forall|_s0: int| 0 <= _s0 < left.wk.len() as int ==> (#[trigger] left.wk[_s0]).len() as int == left.KVN
    &&& left.wv.len() as int == left.K
    &&& forall|_s0: int| 0 <= _s0 < left.wv.len() as int ==> (#[trigger] left.wv[_s0]).len() as int == left.KVN
    &&& left.oq.len() as int == left.M
    &&& forall|_s0: int| 0 <= _s0 < left.oq.len() as int ==> (#[trigger] left.oq[_s0]).len() as int == left.QN
    &&& left.ok.len() as int == left.M
    &&& forall|_s0: int| 0 <= _s0 < left.ok.len() as int ==> (#[trigger] left.ok[_s0]).len() as int == left.KVN
    &&& left.ov.len() as int == left.M
    &&& forall|_s0: int| 0 <= _s0 < left.ov.len() as int ==> (#[trigger] left.ov[_s0]).len() as int == left.KVN
    &&& 0 <= right.M
    &&& 0 <= right.K
    &&& right.a.len() as int == right.M
    &&& forall|_s0: int| 0 <= _s0 < right.a.len() as int ==> (#[trigger] right.a[_s0]).len() as int == right.K
    &&& 0 <= right.QN
    &&& right.wq.len() as int == right.K
    &&& forall|_s0: int| 0 <= _s0 < right.wq.len() as int ==> (#[trigger] right.wq[_s0]).len() as int == right.QN
    &&& 0 <= right.KVN
    &&& right.wk.len() as int == right.K
    &&& forall|_s0: int| 0 <= _s0 < right.wk.len() as int ==> (#[trigger] right.wk[_s0]).len() as int == right.KVN
    &&& right.wv.len() as int == right.K
    &&& forall|_s0: int| 0 <= _s0 < right.wv.len() as int ==> (#[trigger] right.wv[_s0]).len() as int == right.KVN
    &&& right.oq.len() as int == right.M
    &&& forall|_s0: int| 0 <= _s0 < right.oq.len() as int ==> (#[trigger] right.oq[_s0]).len() as int == right.QN
    &&& right.ok.len() as int == right.M
    &&& forall|_s0: int| 0 <= _s0 < right.ok.len() as int ==> (#[trigger] right.ok[_s0]).len() as int == right.KVN
    &&& right.ov.len() as int == right.M
    &&& forall|_s0: int| 0 <= _s0 < right.ov.len() as int ==> (#[trigger] right.ov[_s0]).len() as int == right.KVN
    &&& left.K == right.K
    &&& left.KVN == right.KVN
    &&& left.QN == right.QN
    &&& right.M == 1
    &&& left.QN >= left.KVN
    &&& left.KVN > 0
    &&& left.K > 0
    &&& free.x >= 0
    &&& free.x < left.M
    &&& (0 <= free.x && free.x <= (free.x + 1) && (free.x + 1) <= left.M && 0 <= 0 && 0 <= 1 && 1 <= right.M && ((free.x + 1) - free.x) == (1 - 0) && 0 <= 0 && 0 <= left.K && left.K <= left.K && 0 <= 0 && 0 <= left.K && left.K <= right.K && (left.K - 0) == (left.K - 0) && forall|_r0: int, _r1: int| 0 <= _r0 < ((free.x + 1) - free.x) && 0 <= _r1 < (left.K - 0) ==> #[trigger] left.a[free.x + _r0][0 + _r1] == right.a[0 + _r0][0 + _r1])
    &&& (0 <= 0 && 0 <= left.K && left.K <= left.K && 0 <= 0 && 0 <= left.K && left.K <= right.K && (left.K - 0) == (left.K - 0) && 0 <= 0 && 0 <= left.QN && left.QN <= left.QN && 0 <= 0 && 0 <= left.QN && left.QN <= right.QN && (left.QN - 0) == (left.QN - 0) && forall|_r0: int, _r1: int| 0 <= _r0 < (left.K - 0) && 0 <= _r1 < (left.QN - 0) ==> #[trigger] left.wq[0 + _r0][0 + _r1] == right.wq[0 + _r0][0 + _r1])
    &&& (0 <= 0 && 0 <= left.K && left.K <= left.K && 0 <= 0 && 0 <= left.K && left.K <= right.K && (left.K - 0) == (left.K - 0) && 0 <= 0 && 0 <= left.KVN && left.KVN <= left.KVN && 0 <= 0 && 0 <= left.KVN && left.KVN <= right.KVN && (left.KVN - 0) == (left.KVN - 0) && forall|_r0: int, _r1: int| 0 <= _r0 < (left.K - 0) && 0 <= _r1 < (left.KVN - 0) ==> #[trigger] left.wk[0 + _r0][0 + _r1] == right.wk[0 + _r0][0 + _r1])
    &&& (0 <= 0 && 0 <= left.K && left.K <= left.K && 0 <= 0 && 0 <= left.K && left.K <= right.K && (left.K - 0) == (left.K - 0) && 0 <= 0 && 0 <= left.KVN && left.KVN <= left.KVN && 0 <= 0 && 0 <= left.KVN && left.KVN <= right.KVN && (left.KVN - 0) == (left.KVN - 0) && forall|_r0: int, _r1: int| 0 <= _r0 < (left.K - 0) && 0 <= _r1 < (left.KVN - 0) ==> #[trigger] left.wv[0 + _r0][0 + _r1] == right.wv[0 + _r0][0 + _r1])
}

pub open spec fn raw_batch_invariance_raw_post(
    left: RawSide,
    right: RawSide,
    free: RawBatchInvarianceFree,
) -> bool {
    &&& (0 <= free.x && free.x <= (free.x + 1) && (free.x + 1) <= left.M && 0 <= 0 && 0 <= 1 && 1 <= right.M && ((free.x + 1) - free.x) == (1 - 0) && 0 <= 0 && 0 <= left.QN && left.QN <= left.QN && 0 <= 0 && 0 <= left.QN && left.QN <= right.QN && (left.QN - 0) == (left.QN - 0) && forall|_r0: int, _r1: int| 0 <= _r0 < ((free.x + 1) - free.x) && 0 <= _r1 < (left.QN - 0) ==> #[trigger] left.oq[free.x + _r0][0 + _r1] == right.oq[0 + _r0][0 + _r1])
    &&& (0 <= free.x && free.x <= (free.x + 1) && (free.x + 1) <= left.M && 0 <= 0 && 0 <= 1 && 1 <= right.M && ((free.x + 1) - free.x) == (1 - 0) && 0 <= 0 && 0 <= left.KVN && left.KVN <= left.KVN && 0 <= 0 && 0 <= left.KVN && left.KVN <= right.KVN && (left.KVN - 0) == (left.KVN - 0) && forall|_r0: int, _r1: int| 0 <= _r0 < ((free.x + 1) - free.x) && 0 <= _r1 < (left.KVN - 0) ==> #[trigger] left.ok[free.x + _r0][0 + _r1] == right.ok[0 + _r0][0 + _r1])
    &&& (0 <= free.x && free.x <= (free.x + 1) && (free.x + 1) <= left.M && 0 <= 0 && 0 <= 1 && 1 <= right.M && ((free.x + 1) - free.x) == (1 - 0) && 0 <= 0 && 0 <= left.KVN && left.KVN <= left.KVN && 0 <= 0 && 0 <= left.KVN && left.KVN <= right.KVN && (left.KVN - 0) == (left.KVN - 0) && forall|_r0: int, _r1: int| 0 <= _r0 < ((free.x + 1) - free.x) && 0 <= _r1 < (left.KVN - 0) ==> #[trigger] left.ov[free.x + _r0][0 + _r1] == right.ov[0 + _r0][0 + _r1])
}

// Trusted import of the relational theorem proved for the source and
// specialization named above.  The generated execute function preserves
// launch metadata and allocation shape; only written output cells are opaque.
#[verifier::external_body]
pub proof fn raw_batch_invariance_certificate(
    left: RawSide,
    right: RawSide,
    free: RawBatchInvarianceFree,
)
    requires raw_batch_invariance_raw_pre(left, right, free),
    ensures raw_batch_invariance_raw_post(
        raw_execute(left), raw_execute(right), free,
    ),
{
    unreachable!()
}

// BEGIN CHECKED RECTANGULAR ADAPTER

// Canonical framework values for the raw launch semantics.  Each pre-launch
// output is a generated rectangular allocation with the exact declared shape;
// the generated execute function replaces every logical output cell.
pub open spec fn row_projection_oq_allocation(
    rows: nat,
    cols: nat,
) -> Tensor2D {
    Seq::new(rows, |_row: int| Seq::new(cols, |_col: int|
        generated_kernel_allocation_cell()))
}

pub open spec fn row_projection_ok_allocation(
    rows: nat,
    cols: nat,
) -> Tensor2D {
    Seq::new(rows, |_row: int| Seq::new(cols, |_col: int|
        generated_kernel_allocation_cell()))
}

pub open spec fn row_projection_ov_allocation(
    rows: nat,
    cols: nat,
) -> Tensor2D {
    Seq::new(rows, |_row: int| Seq::new(cols, |_col: int|
        generated_kernel_allocation_cell()))
}

pub open spec fn row_projection_oq_repr(
    input_a: Tensor2D,
    input_wk: Tensor2D,
    input_wq: Tensor2D,
    input_wv: Tensor2D,
    K: nat,
    KVN: nat,
    QN: nat,
) -> Tensor2D {
    raw_oq_after(RawSide {
        a: input_a,
        wk: input_wk,
        wq: input_wq,
        wv: input_wv,
        oq: row_projection_oq_allocation(input_a.len(), QN),
        ok: row_projection_ok_allocation(input_a.len(), KVN),
        ov: row_projection_ov_allocation(input_a.len(), KVN),
        M: input_a.len() as int,
        K: K as int,
        KVN: KVN as int,
        QN: QN as int,
    })
}

pub open spec fn row_projection_oq_mapped_repr(
    input_a: Tensor2D,
    input_wk: Tensor2D,
    input_wq: Tensor2D,
    input_wv: Tensor2D,
    K: nat,
    KVN: nat,
    QN: nat,
) -> Tensor2D {
    Seq::new(input_a.len(), |_row: int|
        row_projection_oq_repr(seq![input_a[_row]], input_wk, input_wq, input_wv, K, KVN, QN)[0])
}

pub open spec fn row_projection_ok_repr(
    input_a: Tensor2D,
    input_wk: Tensor2D,
    input_wq: Tensor2D,
    input_wv: Tensor2D,
    K: nat,
    KVN: nat,
    QN: nat,
) -> Tensor2D {
    raw_ok_after(RawSide {
        a: input_a,
        wk: input_wk,
        wq: input_wq,
        wv: input_wv,
        oq: row_projection_oq_allocation(input_a.len(), QN),
        ok: row_projection_ok_allocation(input_a.len(), KVN),
        ov: row_projection_ov_allocation(input_a.len(), KVN),
        M: input_a.len() as int,
        K: K as int,
        KVN: KVN as int,
        QN: QN as int,
    })
}

pub open spec fn row_projection_ok_mapped_repr(
    input_a: Tensor2D,
    input_wk: Tensor2D,
    input_wq: Tensor2D,
    input_wv: Tensor2D,
    K: nat,
    KVN: nat,
    QN: nat,
) -> Tensor2D {
    Seq::new(input_a.len(), |_row: int|
        row_projection_ok_repr(seq![input_a[_row]], input_wk, input_wq, input_wv, K, KVN, QN)[0])
}

pub open spec fn row_projection_ov_repr(
    input_a: Tensor2D,
    input_wk: Tensor2D,
    input_wq: Tensor2D,
    input_wv: Tensor2D,
    K: nat,
    KVN: nat,
    QN: nat,
) -> Tensor2D {
    raw_ov_after(RawSide {
        a: input_a,
        wk: input_wk,
        wq: input_wq,
        wv: input_wv,
        oq: row_projection_oq_allocation(input_a.len(), QN),
        ok: row_projection_ok_allocation(input_a.len(), KVN),
        ov: row_projection_ov_allocation(input_a.len(), KVN),
        M: input_a.len() as int,
        K: K as int,
        KVN: KVN as int,
        QN: QN as int,
    })
}

pub open spec fn row_projection_ov_mapped_repr(
    input_a: Tensor2D,
    input_wk: Tensor2D,
    input_wq: Tensor2D,
    input_wv: Tensor2D,
    K: nat,
    KVN: nat,
    QN: nat,
) -> Tensor2D {
    Seq::new(input_a.len(), |_row: int|
        row_projection_ov_repr(seq![input_a[_row]], input_wk, input_wq, input_wv, K, KVN, QN)[0])
}

// Exact source-annotation domain at the chosen projection. No domain
// policy table weakens or interprets the source predicate.
pub open spec fn row_projection_domain(
    input_a: Tensor2D,
    input_wk: Tensor2D,
    input_wq: Tensor2D,
    input_wv: Tensor2D,
    rows: nat,
    K: nat,
    KVN: nat,
    QN: nat,
    i: nat,
) -> bool {
    let left = RawSide { a: input_a,
        wk: input_wk,
        wq: input_wq,
        wv: input_wv,
        oq: row_projection_oq_allocation(rows, QN),
        ok: row_projection_ok_allocation(rows, KVN),
        ov: row_projection_ov_allocation(rows, KVN),
        M: rows as int,
        K: K as int,
        KVN: KVN as int,
        QN: QN as int };
    let right = RawSide { a: seq![input_a[i as int]],
        wk: input_wk,
        wq: input_wq,
        wv: input_wv,
        oq: row_projection_oq_allocation(1, QN),
        ok: row_projection_ok_allocation(1, KVN),
        ov: row_projection_ov_allocation(1, KVN),
        M: 1,
        K: K as int,
        KVN: KVN as int,
        QN: QN as int };
    let free = RawBatchInvarianceFree { x: i as int };
    raw_batch_invariance_raw_pre(left, right, free)
}


// Checked rectangular instantiation of the generated raw ContractIR theorem.
pub proof fn row_projection_certificate(
    input_a: Tensor2D,
    input_wk: Tensor2D,
    input_wq: Tensor2D,
    input_wv: Tensor2D,
    rows: nat,
    K: nat,
    KVN: nat,
    QN: nat,
    i: nat,
)
    requires
        TS::tensor2d_shape(input_a, rows, K),
        TS::tensor2d_shape(input_wk, K, KVN),
        TS::tensor2d_shape(input_wq, K, QN),
        TS::tensor2d_shape(input_wv, K, KVN),
        row_projection_domain(input_a, input_wk, input_wq, input_wv, rows, K, KVN, QN, i),
        i < rows,
    ensures
        row_projection_oq_repr(seq![input_a[i as int]], input_wk, input_wq, input_wv, K, KVN, QN)
            == seq![row_projection_oq_repr(input_a, input_wk, input_wq, input_wv, K, KVN, QN)[i as int]],
        row_projection_ok_repr(seq![input_a[i as int]], input_wk, input_wq, input_wv, K, KVN, QN)
            == seq![row_projection_ok_repr(input_a, input_wk, input_wq, input_wv, K, KVN, QN)[i as int]],
        row_projection_ov_repr(seq![input_a[i as int]], input_wk, input_wq, input_wv, K, KVN, QN)
            == seq![row_projection_ov_repr(input_a, input_wk, input_wq, input_wv, K, KVN, QN)[i as int]],
{
    reveal(row_projection_domain);

    let left = RawSide {
        a: input_a,
        wk: input_wk,
        wq: input_wq,
        wv: input_wv,
        oq: row_projection_oq_allocation(rows, QN),
        ok: row_projection_ok_allocation(rows, KVN),
        ov: row_projection_ov_allocation(rows, KVN),
        M: rows as int,
        K: K as int,
        KVN: KVN as int,
        QN: QN as int,
    };
    let right = RawSide {
        a: seq![input_a[i as int]],
        wk: input_wk,
        wq: input_wq,
        wv: input_wv,
        oq: row_projection_oq_allocation(1, QN),
        ok: row_projection_ok_allocation(1, KVN),
        ov: row_projection_ov_allocation(1, KVN),
        M: 1,
        K: K as int,
        KVN: KVN as int,
        QN: QN as int,
    };
    let free = RawBatchInvarianceFree { x: i as int };
    assert(raw_batch_invariance_raw_pre(left, right, free)) by {
        reveal(row_projection_oq_allocation);
        reveal(row_projection_ok_allocation);
        reveal(row_projection_ov_allocation);
        assert forall|r: int| 0 <= r < rows implies
            (#[trigger] input_a[r]).len() == K by {};
        assert forall|r0: int, r1: int|
            0 <= r0 < 1 && 0 <= r1 < K implies
            #[trigger] left.a[i as int + r0][r1]
                == right.a[r0][r1] by {
            assert(r0 == 0);
        };
    }
    raw_batch_invariance_certificate(left, right, free);
    let left_after = raw_execute(left);
    let right_after = raw_execute(right);
    assert(raw_batch_invariance_raw_post(left_after, right_after, free));
    reveal(raw_batch_invariance_raw_post);
    reveal(raw_execute);
    assert(left_after.M == rows as int);
    assert(right_after.M == 1);
    assert(left_after.K == K as int);
    assert(right_after.K == K as int);
    assert(left_after.KVN == KVN as int);
    assert(right_after.KVN == KVN as int);
    assert(left_after.QN == QN as int);
    assert(right_after.QN == QN as int);
    assert(0 <= i as int && i as int + 1 <= left_after.M);
    assert forall|c: int| 0 <= c < QN implies
        (#[trigger] left_after.oq[i as int][c])
            == right_after.oq[0][c] by {
        assert(0 <= 0 < ((free.x + 1) - free.x));
        assert(0 <= c < QN);
        assert(left_after.oq[free.x + 0][0 + c]
            == right_after.oq[0 as int][0 + c]);
    };
    assert(left_after.oq[i as int]
        =~= right_after.oq[0]);
    assert forall|c: int| 0 <= c < KVN implies
        (#[trigger] left_after.ok[i as int][c])
            == right_after.ok[0][c] by {
        assert(0 <= 0 < ((free.x + 1) - free.x));
        assert(0 <= c < KVN);
        assert(left_after.ok[free.x + 0][0 + c]
            == right_after.ok[0 as int][0 + c]);
    };
    assert(left_after.ok[i as int]
        =~= right_after.ok[0]);
    assert forall|c: int| 0 <= c < KVN implies
        (#[trigger] left_after.ov[i as int][c])
            == right_after.ov[0][c] by {
        assert(0 <= 0 < ((free.x + 1) - free.x));
        assert(0 <= c < KVN);
        assert(left_after.ov[free.x + 0][0 + c]
            == right_after.ov[0 as int][0 + c]);
    };
    assert(left_after.ov[i as int]
        =~= right_after.ov[0]);
    reveal(row_projection_oq_repr);
    assert(row_projection_oq_repr(input_a, input_wk, input_wq, input_wv, K, KVN, QN)[i as int]
        == left_after.oq[i as int]);
    assert(row_projection_oq_repr(seq![input_a[i as int]], input_wk, input_wq, input_wv, K, KVN, QN)[0]
        == right_after.oq[0]);
    assert(row_projection_oq_repr(seq![input_a[i as int]], input_wk, input_wq, input_wv, K, KVN, QN)
        =~= seq![row_projection_oq_repr(input_a, input_wk, input_wq, input_wv, K, KVN, QN)[i as int]]);
    reveal(row_projection_ok_repr);
    assert(row_projection_ok_repr(input_a, input_wk, input_wq, input_wv, K, KVN, QN)[i as int]
        == left_after.ok[i as int]);
    assert(row_projection_ok_repr(seq![input_a[i as int]], input_wk, input_wq, input_wv, K, KVN, QN)[0]
        == right_after.ok[0]);
    assert(row_projection_ok_repr(seq![input_a[i as int]], input_wk, input_wq, input_wv, K, KVN, QN)
        =~= seq![row_projection_ok_repr(input_a, input_wk, input_wq, input_wv, K, KVN, QN)[i as int]]);
    reveal(row_projection_ov_repr);
    assert(row_projection_ov_repr(input_a, input_wk, input_wq, input_wv, K, KVN, QN)[i as int]
        == left_after.ov[i as int]);
    assert(row_projection_ov_repr(seq![input_a[i as int]], input_wk, input_wq, input_wv, K, KVN, QN)[0]
        == right_after.ov[0]);
    assert(row_projection_ov_repr(seq![input_a[i as int]], input_wk, input_wq, input_wv, K, KVN, QN)
        =~= seq![row_projection_ov_repr(input_a, input_wk, input_wq, input_wv, K, KVN, QN)[i as int]]);
}

// The engine may use the mapped representation as its total row-local
// semantics.  For every valid rectangular launch, this checked theorem shows
// that it is exactly the generated raw whole-launch representation.
pub proof fn row_projection_launch_equivalence(
    input_a: Tensor2D,
    input_wk: Tensor2D,
    input_wq: Tensor2D,
    input_wv: Tensor2D,
    rows: nat,
    K: nat,
    KVN: nat,
    QN: nat,
)
    requires
        TS::tensor2d_shape(input_a, rows, K),
        TS::tensor2d_shape(input_wk, K, KVN),
        TS::tensor2d_shape(input_wq, K, QN),
        TS::tensor2d_shape(input_wv, K, KVN),
        forall|row: nat| row < rows ==>
            #[trigger] row_projection_domain(input_a, input_wk, input_wq, input_wv, rows, K, KVN, QN, row),
    ensures
        row_projection_oq_repr(input_a, input_wk, input_wq, input_wv, K, KVN, QN)
            == row_projection_oq_mapped_repr(input_a, input_wk, input_wq, input_wv, K, KVN, QN),
        row_projection_ok_repr(input_a, input_wk, input_wq, input_wv, K, KVN, QN)
            == row_projection_ok_mapped_repr(input_a, input_wk, input_wq, input_wv, K, KVN, QN),
        row_projection_ov_repr(input_a, input_wk, input_wq, input_wv, K, KVN, QN)
            == row_projection_ov_mapped_repr(input_a, input_wk, input_wq, input_wv, K, KVN, QN),
{
    assert forall|_row: int| 0 <= _row < rows implies
        (#[trigger] row_projection_oq_repr(input_a, input_wk, input_wq, input_wv, K, KVN, QN)[_row])
            == row_projection_oq_mapped_repr(input_a, input_wk, input_wq, input_wv, K, KVN, QN)[_row] by {
        row_projection_certificate(input_a, input_wk, input_wq, input_wv, rows, K, KVN, QN, _row as nat);
        reveal(row_projection_oq_mapped_repr);
        assert(row_projection_oq_repr(seq![input_a[_row]], input_wk, input_wq, input_wv, K, KVN, QN)[0]
            == row_projection_oq_repr(input_a, input_wk, input_wq, input_wv, K, KVN, QN)[_row]);
    };
    assert(row_projection_oq_repr(input_a, input_wk, input_wq, input_wv, K, KVN, QN)
        =~= row_projection_oq_mapped_repr(input_a, input_wk, input_wq, input_wv, K, KVN, QN));
    assert forall|_row: int| 0 <= _row < rows implies
        (#[trigger] row_projection_ok_repr(input_a, input_wk, input_wq, input_wv, K, KVN, QN)[_row])
            == row_projection_ok_mapped_repr(input_a, input_wk, input_wq, input_wv, K, KVN, QN)[_row] by {
        row_projection_certificate(input_a, input_wk, input_wq, input_wv, rows, K, KVN, QN, _row as nat);
        reveal(row_projection_ok_mapped_repr);
        assert(row_projection_ok_repr(seq![input_a[_row]], input_wk, input_wq, input_wv, K, KVN, QN)[0]
            == row_projection_ok_repr(input_a, input_wk, input_wq, input_wv, K, KVN, QN)[_row]);
    };
    assert(row_projection_ok_repr(input_a, input_wk, input_wq, input_wv, K, KVN, QN)
        =~= row_projection_ok_mapped_repr(input_a, input_wk, input_wq, input_wv, K, KVN, QN));
    assert forall|_row: int| 0 <= _row < rows implies
        (#[trigger] row_projection_ov_repr(input_a, input_wk, input_wq, input_wv, K, KVN, QN)[_row])
            == row_projection_ov_mapped_repr(input_a, input_wk, input_wq, input_wv, K, KVN, QN)[_row] by {
        row_projection_certificate(input_a, input_wk, input_wq, input_wv, rows, K, KVN, QN, _row as nat);
        reveal(row_projection_ov_mapped_repr);
        assert(row_projection_ov_repr(seq![input_a[_row]], input_wk, input_wq, input_wv, K, KVN, QN)[0]
            == row_projection_ov_repr(input_a, input_wk, input_wq, input_wv, K, KVN, QN)[_row]);
    };
    assert(row_projection_ov_repr(input_a, input_wk, input_wq, input_wv, K, KVN, QN)
        =~= row_projection_ov_mapped_repr(input_a, input_wk, input_wq, input_wv, K, KVN, QN));
}

} // verus!
