// @generated by scripts/verification/verify_rectangular_interfaces.py; DO NOT EDIT.
#![allow(non_snake_case)]
use vstd::prelude::*;
use crate::{boundary::scalar::{Scalar}, proof::tensor::types::{Tensor1D, Tensor2D, IntTensor1D}};
use crate::proof::tensor::shape as TS;
#[cfg(verus_only)]
use crate::boundary::backend_certificates::support::generated_kernel_allocation_cell;

verus! {
// Abstract interface for ONE fixed, separately qualified deployment.
// Alternative implementations prove this same theory; their outputs
// are not equated. See the separate implementation proof records.
// Raw ContractIR lowering for rmsnorm_residual_kernel

pub open spec fn raw_batch_invariance_cdiv(numerator: int, denominator: int) -> int {
    (numerator + denominator - 1) / denominator
}

pub struct RawSide {
    pub x: Seq<Seq<Scalar>>,
    pub residual: Seq<Seq<Scalar>>,
    pub w: Seq<Scalar>,
    pub o: Seq<Seq<Scalar>>,
    pub residual_out: Seq<Seq<Scalar>>,
    pub eps: Scalar,
    pub M: int,
    pub N: int,
}

pub struct RawBatchInvarianceFree {
    pub b: int,
}


pub uninterp spec fn raw_o_cell(before: RawSide, _i0: int, _i1: int) -> Scalar;

pub open spec fn raw_o_after(before: RawSide)
    -> Seq<Seq<Scalar>>
{
    Seq::new(before.o.len(), |_i0: int| Seq::new(before.o[_i0].len(), |_i1: int| raw_o_cell(before, _i0, _i1)))
}

pub uninterp spec fn raw_residual_out_cell(before: RawSide, _i0: int, _i1: int) -> Scalar;

pub open spec fn raw_residual_out_after(before: RawSide)
    -> Seq<Seq<Scalar>>
{
    Seq::new(before.residual_out.len(), |_i0: int| Seq::new(before.residual_out[_i0].len(), |_i1: int| raw_residual_out_cell(before, _i0, _i1)))
}

pub open spec fn raw_execute(before: RawSide) -> RawSide {
    RawSide {
        x: before.x,
        residual: before.residual,
        w: before.w,
        o: raw_o_after(before),
        residual_out: raw_residual_out_after(before),
        eps: before.eps,
        M: before.M,
        N: before.N,
    }
}

pub open spec fn raw_batch_invariance_raw_pre(
    left: RawSide,
    right: RawSide,
    free: RawBatchInvarianceFree,
) -> bool {
    &&& 0 <= left.M
    &&& 0 <= left.N
    &&& left.x.len() as int == left.M
    &&& forall|_s0: int| 0 <= _s0 < left.x.len() as int ==> (#[trigger] left.x[_s0]).len() as int == left.N
    &&& left.residual.len() as int == left.M
    &&& forall|_s0: int| 0 <= _s0 < left.residual.len() as int ==> (#[trigger] left.residual[_s0]).len() as int == left.N
    &&& left.w.len() as int == left.N
    &&& left.o.len() as int == left.M
    &&& forall|_s0: int| 0 <= _s0 < left.o.len() as int ==> (#[trigger] left.o[_s0]).len() as int == left.N
    &&& left.residual_out.len() as int == left.M
    &&& forall|_s0: int| 0 <= _s0 < left.residual_out.len() as int ==> (#[trigger] left.residual_out[_s0]).len() as int == left.N
    &&& 0 <= right.M
    &&& 0 <= right.N
    &&& right.x.len() as int == right.M
    &&& forall|_s0: int| 0 <= _s0 < right.x.len() as int ==> (#[trigger] right.x[_s0]).len() as int == right.N
    &&& right.residual.len() as int == right.M
    &&& forall|_s0: int| 0 <= _s0 < right.residual.len() as int ==> (#[trigger] right.residual[_s0]).len() as int == right.N
    &&& right.w.len() as int == right.N
    &&& right.o.len() as int == right.M
    &&& forall|_s0: int| 0 <= _s0 < right.o.len() as int ==> (#[trigger] right.o[_s0]).len() as int == right.N
    &&& right.residual_out.len() as int == right.M
    &&& forall|_s0: int| 0 <= _s0 < right.residual_out.len() as int ==> (#[trigger] right.residual_out[_s0]).len() as int == right.N
    &&& left.N == right.N
    &&& left.eps == right.eps
    &&& right.M == 1
    &&& free.b >= 0
    &&& free.b < left.M
    &&& (0 <= free.b && free.b <= (free.b + 1) && (free.b + 1) <= left.M && 0 <= 0 && 0 <= 1 && 1 <= right.M && ((free.b + 1) - free.b) == (1 - 0) && 0 <= 0 && 0 <= left.N && left.N <= left.N && 0 <= 0 && 0 <= left.N && left.N <= right.N && (left.N - 0) == (left.N - 0) && forall|_r0: int, _r1: int| 0 <= _r0 < ((free.b + 1) - free.b) && 0 <= _r1 < (left.N - 0) ==> #[trigger] left.x[free.b + _r0][0 + _r1] == right.x[0 + _r0][0 + _r1])
    &&& (0 <= free.b && free.b <= (free.b + 1) && (free.b + 1) <= left.M && 0 <= 0 && 0 <= 1 && 1 <= right.M && ((free.b + 1) - free.b) == (1 - 0) && 0 <= 0 && 0 <= left.N && left.N <= left.N && 0 <= 0 && 0 <= left.N && left.N <= right.N && (left.N - 0) == (left.N - 0) && forall|_r0: int, _r1: int| 0 <= _r0 < ((free.b + 1) - free.b) && 0 <= _r1 < (left.N - 0) ==> #[trigger] left.residual[free.b + _r0][0 + _r1] == right.residual[0 + _r0][0 + _r1])
    &&& (0 <= 0 && 0 <= left.N && left.N <= left.N && 0 <= 0 && 0 <= left.N && left.N <= right.N && (left.N - 0) == (left.N - 0) && forall|_r0: int| 0 <= _r0 < (left.N - 0) ==> #[trigger] left.w[0 + _r0] == right.w[0 + _r0])
}

pub open spec fn raw_batch_invariance_raw_post(
    left: RawSide,
    right: RawSide,
    free: RawBatchInvarianceFree,
) -> bool {
    &&& (0 <= free.b && free.b <= (free.b + 1) && (free.b + 1) <= left.M && 0 <= 0 && 0 <= 1 && 1 <= right.M && ((free.b + 1) - free.b) == (1 - 0) && 0 <= 0 && 0 <= left.N && left.N <= left.N && 0 <= 0 && 0 <= left.N && left.N <= right.N && (left.N - 0) == (left.N - 0) && forall|_r0: int, _r1: int| 0 <= _r0 < ((free.b + 1) - free.b) && 0 <= _r1 < (left.N - 0) ==> #[trigger] left.o[free.b + _r0][0 + _r1] == right.o[0 + _r0][0 + _r1])
    &&& (0 <= free.b && free.b <= (free.b + 1) && (free.b + 1) <= left.M && 0 <= 0 && 0 <= 1 && 1 <= right.M && ((free.b + 1) - free.b) == (1 - 0) && 0 <= 0 && 0 <= left.N && left.N <= left.N && 0 <= 0 && 0 <= left.N && left.N <= right.N && (left.N - 0) == (left.N - 0) && forall|_r0: int, _r1: int| 0 <= _r0 < ((free.b + 1) - free.b) && 0 <= _r1 < (left.N - 0) ==> #[trigger] left.residual_out[free.b + _r0][0 + _r1] == right.residual_out[0 + _r0][0 + _r1])
}

// Trusted import of the relational theorem proved for the source and
// specialization named above.  The generated execute function preserves
// launch metadata and allocation shape; only written output cells are opaque.
#[verifier::external_body]
pub proof fn raw_batch_invariance_certificate(
    left: RawSide,
    right: RawSide,
    free: RawBatchInvarianceFree,
)
    requires raw_batch_invariance_raw_pre(left, right, free),
    ensures raw_batch_invariance_raw_post(
        raw_execute(left), raw_execute(right), free,
    ),
{
    unreachable!()
}

// BEGIN CHECKED RECTANGULAR ADAPTER

// Canonical framework values for the raw launch semantics.  Each pre-launch
// output is a generated rectangular allocation with the exact declared shape;
// the generated execute function replaces every logical output cell.
pub open spec fn row_projection_o_allocation(
    rows: nat,
    cols: nat,
) -> Tensor2D {
    Seq::new(rows, |_row: int| Seq::new(cols, |_col: int|
        generated_kernel_allocation_cell()))
}

pub open spec fn row_projection_residual_out_allocation(
    rows: nat,
    cols: nat,
) -> Tensor2D {
    Seq::new(rows, |_row: int| Seq::new(cols, |_col: int|
        generated_kernel_allocation_cell()))
}

pub open spec fn row_projection_o_repr(
    input_residual: Tensor2D,
    input_x: Tensor2D,
    input_w: Tensor1D,
    input_eps: Scalar,
    N: nat,
) -> Tensor2D {
    raw_o_after(RawSide {
        residual: input_residual,
        x: input_x,
        w: input_w,
        eps: input_eps,
        o: row_projection_o_allocation(input_residual.len(), N),
        residual_out: row_projection_residual_out_allocation(input_residual.len(), N),
        M: input_residual.len() as int,
        N: N as int,
    })
}

pub open spec fn row_projection_o_mapped_repr(
    input_residual: Tensor2D,
    input_x: Tensor2D,
    input_w: Tensor1D,
    input_eps: Scalar,
    N: nat,
) -> Tensor2D {
    Seq::new(input_residual.len(), |_row: int|
        row_projection_o_repr(seq![input_residual[_row]], seq![input_x[_row]], input_w, input_eps, N)[0])
}

pub open spec fn row_projection_residual_out_repr(
    input_residual: Tensor2D,
    input_x: Tensor2D,
    input_w: Tensor1D,
    input_eps: Scalar,
    N: nat,
) -> Tensor2D {
    raw_residual_out_after(RawSide {
        residual: input_residual,
        x: input_x,
        w: input_w,
        eps: input_eps,
        o: row_projection_o_allocation(input_residual.len(), N),
        residual_out: row_projection_residual_out_allocation(input_residual.len(), N),
        M: input_residual.len() as int,
        N: N as int,
    })
}

pub open spec fn row_projection_residual_out_mapped_repr(
    input_residual: Tensor2D,
    input_x: Tensor2D,
    input_w: Tensor1D,
    input_eps: Scalar,
    N: nat,
) -> Tensor2D {
    Seq::new(input_residual.len(), |_row: int|
        row_projection_residual_out_repr(seq![input_residual[_row]], seq![input_x[_row]], input_w, input_eps, N)[0])
}

// Exact source-annotation domain at the chosen projection. No domain
// policy table weakens or interprets the source predicate.
pub open spec fn row_projection_domain(
    input_residual: Tensor2D,
    input_x: Tensor2D,
    input_w: Tensor1D,
    input_eps: Scalar,
    rows: nat,
    N: nat,
    i: nat,
) -> bool {
    let left = RawSide { residual: input_residual,
        x: input_x,
        w: input_w,
        eps: input_eps,
        o: row_projection_o_allocation(rows, N),
        residual_out: row_projection_residual_out_allocation(rows, N),
        M: rows as int,
        N: N as int };
    let right = RawSide { residual: seq![input_residual[i as int]],
        x: seq![input_x[i as int]],
        w: input_w,
        eps: input_eps,
        o: row_projection_o_allocation(1, N),
        residual_out: row_projection_residual_out_allocation(1, N),
        M: 1,
        N: N as int };
    let free = RawBatchInvarianceFree { b: i as int };
    raw_batch_invariance_raw_pre(left, right, free)
}


// Checked rectangular instantiation of the generated raw ContractIR theorem.
pub proof fn row_projection_certificate(
    input_residual: Tensor2D,
    input_x: Tensor2D,
    input_w: Tensor1D,
    input_eps: Scalar,
    rows: nat,
    N: nat,
    i: nat,
)
    requires
        TS::tensor2d_shape(input_residual, rows, N),
        TS::tensor2d_shape(input_x, rows, N),
        input_w.len() == N,
        row_projection_domain(input_residual, input_x, input_w, input_eps, rows, N, i),
        i < rows,
    ensures
        row_projection_o_repr(seq![input_residual[i as int]], seq![input_x[i as int]], input_w, input_eps, N)
            == seq![row_projection_o_repr(input_residual, input_x, input_w, input_eps, N)[i as int]],
        row_projection_residual_out_repr(seq![input_residual[i as int]], seq![input_x[i as int]], input_w, input_eps, N)
            == seq![row_projection_residual_out_repr(input_residual, input_x, input_w, input_eps, N)[i as int]],
{
    reveal(row_projection_domain);

    let left = RawSide {
        residual: input_residual,
        x: input_x,
        w: input_w,
        eps: input_eps,
        o: row_projection_o_allocation(rows, N),
        residual_out: row_projection_residual_out_allocation(rows, N),
        M: rows as int,
        N: N as int,
    };
    let right = RawSide {
        residual: seq![input_residual[i as int]],
        x: seq![input_x[i as int]],
        w: input_w,
        eps: input_eps,
        o: row_projection_o_allocation(1, N),
        residual_out: row_projection_residual_out_allocation(1, N),
        M: 1,
        N: N as int,
    };
    let free = RawBatchInvarianceFree { b: i as int };
    assert(raw_batch_invariance_raw_pre(left, right, free)) by {
        reveal(row_projection_o_allocation);
        reveal(row_projection_residual_out_allocation);
        assert forall|r: int| 0 <= r < rows implies
            (#[trigger] input_residual[r]).len() == N by {};
        assert forall|r: int| 0 <= r < rows implies
            (#[trigger] input_x[r]).len() == N by {};
        assert forall|r0: int, r1: int|
            0 <= r0 < 1 && 0 <= r1 < N implies
            #[trigger] left.residual[i as int + r0][r1]
                == right.residual[r0][r1] by {
            assert(r0 == 0);
        };
        assert forall|r0: int, r1: int|
            0 <= r0 < 1 && 0 <= r1 < N implies
            #[trigger] left.x[i as int + r0][r1]
                == right.x[r0][r1] by {
            assert(r0 == 0);
        };
    }
    raw_batch_invariance_certificate(left, right, free);
    let left_after = raw_execute(left);
    let right_after = raw_execute(right);
    assert(raw_batch_invariance_raw_post(left_after, right_after, free));
    reveal(raw_batch_invariance_raw_post);
    reveal(raw_execute);
    assert(left_after.M == rows as int);
    assert(right_after.M == 1);
    assert(left_after.N == N as int);
    assert(right_after.N == N as int);
    assert(0 <= i as int && i as int + 1 <= left_after.M);
    assert forall|c: int| 0 <= c < N implies
        (#[trigger] left_after.o[i as int][c])
            == right_after.o[0][c] by {
        assert(0 <= 0 < ((free.b + 1) - free.b));
        assert(0 <= c < N);
        assert(left_after.o[free.b + 0][0 + c]
            == right_after.o[0 as int][0 + c]);
    };
    assert(left_after.o[i as int]
        =~= right_after.o[0]);
    assert forall|c: int| 0 <= c < N implies
        (#[trigger] left_after.residual_out[i as int][c])
            == right_after.residual_out[0][c] by {
        assert(0 <= 0 < ((free.b + 1) - free.b));
        assert(0 <= c < N);
        assert(left_after.residual_out[free.b + 0][0 + c]
            == right_after.residual_out[0 as int][0 + c]);
    };
    assert(left_after.residual_out[i as int]
        =~= right_after.residual_out[0]);
    reveal(row_projection_o_repr);
    assert(row_projection_o_repr(input_residual, input_x, input_w, input_eps, N)[i as int]
        == left_after.o[i as int]);
    assert(row_projection_o_repr(seq![input_residual[i as int]], seq![input_x[i as int]], input_w, input_eps, N)[0]
        == right_after.o[0]);
    assert(row_projection_o_repr(seq![input_residual[i as int]], seq![input_x[i as int]], input_w, input_eps, N)
        =~= seq![row_projection_o_repr(input_residual, input_x, input_w, input_eps, N)[i as int]]);
    reveal(row_projection_residual_out_repr);
    assert(row_projection_residual_out_repr(input_residual, input_x, input_w, input_eps, N)[i as int]
        == left_after.residual_out[i as int]);
    assert(row_projection_residual_out_repr(seq![input_residual[i as int]], seq![input_x[i as int]], input_w, input_eps, N)[0]
        == right_after.residual_out[0]);
    assert(row_projection_residual_out_repr(seq![input_residual[i as int]], seq![input_x[i as int]], input_w, input_eps, N)
        =~= seq![row_projection_residual_out_repr(input_residual, input_x, input_w, input_eps, N)[i as int]]);
}

// The engine may use the mapped representation as its total row-local
// semantics.  For every valid rectangular launch, this checked theorem shows
// that it is exactly the generated raw whole-launch representation.
pub proof fn row_projection_launch_equivalence(
    input_residual: Tensor2D,
    input_x: Tensor2D,
    input_w: Tensor1D,
    input_eps: Scalar,
    rows: nat,
    N: nat,
)
    requires
        TS::tensor2d_shape(input_residual, rows, N),
        TS::tensor2d_shape(input_x, rows, N),
        input_w.len() == N,
        forall|row: nat| row < rows ==>
            #[trigger] row_projection_domain(input_residual, input_x, input_w, input_eps, rows, N, row),
    ensures
        row_projection_o_repr(input_residual, input_x, input_w, input_eps, N)
            == row_projection_o_mapped_repr(input_residual, input_x, input_w, input_eps, N),
        row_projection_residual_out_repr(input_residual, input_x, input_w, input_eps, N)
            == row_projection_residual_out_mapped_repr(input_residual, input_x, input_w, input_eps, N),
{
    assert forall|_row: int| 0 <= _row < rows implies
        (#[trigger] row_projection_o_repr(input_residual, input_x, input_w, input_eps, N)[_row])
            == row_projection_o_mapped_repr(input_residual, input_x, input_w, input_eps, N)[_row] by {
        row_projection_certificate(input_residual, input_x, input_w, input_eps, rows, N, _row as nat);
        reveal(row_projection_o_mapped_repr);
        assert(row_projection_o_repr(seq![input_residual[_row]], seq![input_x[_row]], input_w, input_eps, N)[0]
            == row_projection_o_repr(input_residual, input_x, input_w, input_eps, N)[_row]);
    };
    assert(row_projection_o_repr(input_residual, input_x, input_w, input_eps, N)
        =~= row_projection_o_mapped_repr(input_residual, input_x, input_w, input_eps, N));
    assert forall|_row: int| 0 <= _row < rows implies
        (#[trigger] row_projection_residual_out_repr(input_residual, input_x, input_w, input_eps, N)[_row])
            == row_projection_residual_out_mapped_repr(input_residual, input_x, input_w, input_eps, N)[_row] by {
        row_projection_certificate(input_residual, input_x, input_w, input_eps, rows, N, _row as nat);
        reveal(row_projection_residual_out_mapped_repr);
        assert(row_projection_residual_out_repr(seq![input_residual[_row]], seq![input_x[_row]], input_w, input_eps, N)[0]
            == row_projection_residual_out_repr(input_residual, input_x, input_w, input_eps, N)[_row]);
    };
    assert(row_projection_residual_out_repr(input_residual, input_x, input_w, input_eps, N)
        =~= row_projection_residual_out_mapped_repr(input_residual, input_x, input_w, input_eps, N));
}

} // verus!
