// @generated by scripts/verification/rectangular_interface_catalog.py; DO NOT EDIT.
#![allow(non_snake_case)]
use vstd::prelude::*;
use crate::{boundary::scalar::{Scalar}, proof::tensor::types::{Tensor1D, Tensor2D, IntTensor1D}};
use crate::proof::tensor::shape as TS;
#[cfg(verus_only)]
use crate::boundary::backend_certificates::support::generated_kernel_allocation_cell;

pub mod geometry_D_128_HD_64 {
use super::*;
verus! {
// Abstract interface for ONE fixed, separately qualified deployment.
// Alternative implementations prove this same theory; their outputs
// are not equated. See the separate implementation proof records.
// Raw ContractIR lowering for rope_kernel

pub open spec fn raw_batch_invariance_cdiv(numerator: int, denominator: int) -> int {
    (numerator + denominator - 1) / denominator
}

pub struct RawSide {
    pub x: Seq<Seq<Scalar>>,
    pub cos_table: Seq<Seq<Scalar>>,
    pub sin_table: Seq<Seq<Scalar>>,
    pub o: Seq<Seq<Scalar>>,
    pub M: int,
}

pub struct RawBatchInvarianceFree {
    pub b: int,
}


pub uninterp spec fn raw_o_cell(before: RawSide, _i0: int, _i1: int) -> Scalar;

pub open spec fn raw_o_after(before: RawSide)
    -> Seq<Seq<Scalar>>
{
    Seq::new(before.o.len(), |_i0: int| Seq::new(before.o[_i0].len(), |_i1: int| raw_o_cell(before, _i0, _i1)))
}

pub open spec fn raw_execute(before: RawSide) -> RawSide {
    RawSide {
        x: before.x,
        cos_table: before.cos_table,
        sin_table: before.sin_table,
        o: raw_o_after(before),
        M: before.M,
    }
}

pub open spec fn raw_batch_invariance_raw_pre(
    left: RawSide,
    right: RawSide,
    free: RawBatchInvarianceFree,
) -> bool {
    &&& 0 <= left.M
    &&& 0 <= 128
    &&& left.x.len() as int == left.M
    &&& forall|_s0: int| 0 <= _s0 < left.x.len() as int ==> (#[trigger] left.x[_s0]).len() as int == 128
    &&& 0 <= 64
    &&& left.cos_table.len() as int == left.M
    &&& forall|_s0: int| 0 <= _s0 < left.cos_table.len() as int ==> (#[trigger] left.cos_table[_s0]).len() as int == 64
    &&& left.sin_table.len() as int == left.M
    &&& forall|_s0: int| 0 <= _s0 < left.sin_table.len() as int ==> (#[trigger] left.sin_table[_s0]).len() as int == 64
    &&& left.o.len() as int == left.M
    &&& forall|_s0: int| 0 <= _s0 < left.o.len() as int ==> (#[trigger] left.o[_s0]).len() as int == 128
    &&& 0 <= right.M
    &&& right.x.len() as int == right.M
    &&& forall|_s0: int| 0 <= _s0 < right.x.len() as int ==> (#[trigger] right.x[_s0]).len() as int == 128
    &&& right.cos_table.len() as int == right.M
    &&& forall|_s0: int| 0 <= _s0 < right.cos_table.len() as int ==> (#[trigger] right.cos_table[_s0]).len() as int == 64
    &&& right.sin_table.len() as int == right.M
    &&& forall|_s0: int| 0 <= _s0 < right.sin_table.len() as int ==> (#[trigger] right.sin_table[_s0]).len() as int == 64
    &&& right.o.len() as int == right.M
    &&& forall|_s0: int| 0 <= _s0 < right.o.len() as int ==> (#[trigger] right.o[_s0]).len() as int == 128
    &&& right.M == 1
    &&& free.b >= 0
    &&& free.b < left.M
    &&& (0 <= free.b && free.b <= (free.b + 1) && (free.b + 1) <= left.M && 0 <= 0 && 0 <= 1 && 1 <= right.M && ((free.b + 1) - free.b) == (1 - 0) && 0 <= 0 && 0 <= 128 && 128 <= 128 && 0 <= 0 && 0 <= 128 && 128 <= 128 && (128 - 0) == (128 - 0) && forall|_r0: int, _r1: int| 0 <= _r0 < ((free.b + 1) - free.b) && 0 <= _r1 < (128 - 0) ==> #[trigger] left.x[free.b + _r0][0 + _r1] == right.x[0 + _r0][0 + _r1])
    &&& (0 <= free.b && free.b <= (free.b + 1) && (free.b + 1) <= left.M && 0 <= 0 && 0 <= 1 && 1 <= right.M && ((free.b + 1) - free.b) == (1 - 0) && 0 <= 0 && 0 <= 64 && 64 <= 64 && 0 <= 0 && 0 <= 64 && 64 <= 64 && (64 - 0) == (64 - 0) && forall|_r0: int, _r1: int| 0 <= _r0 < ((free.b + 1) - free.b) && 0 <= _r1 < (64 - 0) ==> #[trigger] left.cos_table[free.b + _r0][0 + _r1] == right.cos_table[0 + _r0][0 + _r1])
    &&& (0 <= free.b && free.b <= (free.b + 1) && (free.b + 1) <= left.M && 0 <= 0 && 0 <= 1 && 1 <= right.M && ((free.b + 1) - free.b) == (1 - 0) && 0 <= 0 && 0 <= 64 && 64 <= 64 && 0 <= 0 && 0 <= 64 && 64 <= 64 && (64 - 0) == (64 - 0) && forall|_r0: int, _r1: int| 0 <= _r0 < ((free.b + 1) - free.b) && 0 <= _r1 < (64 - 0) ==> #[trigger] left.sin_table[free.b + _r0][0 + _r1] == right.sin_table[0 + _r0][0 + _r1])
}

pub open spec fn raw_batch_invariance_raw_post(
    left: RawSide,
    right: RawSide,
    free: RawBatchInvarianceFree,
) -> bool {
    &&& (0 <= free.b && free.b <= (free.b + 1) && (free.b + 1) <= left.M && 0 <= 0 && 0 <= 1 && 1 <= right.M && ((free.b + 1) - free.b) == (1 - 0) && 0 <= 0 && 0 <= 128 && 128 <= 128 && 0 <= 0 && 0 <= 128 && 128 <= 128 && (128 - 0) == (128 - 0) && forall|_r0: int, _r1: int| 0 <= _r0 < ((free.b + 1) - free.b) && 0 <= _r1 < (128 - 0) ==> #[trigger] left.o[free.b + _r0][0 + _r1] == right.o[0 + _r0][0 + _r1])
}

// Trusted import of the relational theorem proved for the source and
// specialization named above.  The generated execute function preserves
// launch metadata and allocation shape; only written output cells are opaque.
#[verifier::external_body]
pub proof fn raw_batch_invariance_certificate(
    left: RawSide,
    right: RawSide,
    free: RawBatchInvarianceFree,
)
    requires raw_batch_invariance_raw_pre(left, right, free),
    ensures raw_batch_invariance_raw_post(
        raw_execute(left), raw_execute(right), free,
    ),
{
    unreachable!()
}

// BEGIN CHECKED RECTANGULAR ADAPTER

// Canonical framework values for the raw launch semantics.  Each pre-launch
// output is a generated rectangular allocation with the exact declared shape;
// the generated execute function replaces every logical output cell.
pub open spec fn row_projection_o_allocation(
    rows: nat,
    cols: nat,
) -> Tensor2D {
    Seq::new(rows, |_row: int| Seq::new(cols, |_col: int|
        generated_kernel_allocation_cell()))
}

pub open spec fn row_projection_repr(
    input_cos_table: Tensor2D,
    input_sin_table: Tensor2D,
    input_x: Tensor2D,
) -> Tensor2D {
    raw_o_after(RawSide {
        cos_table: input_cos_table,
        sin_table: input_sin_table,
        x: input_x,
        o: row_projection_o_allocation(input_cos_table.len(), 128),
        M: input_cos_table.len() as int,
    })
}

pub open spec fn row_projection_mapped_repr(
    input_cos_table: Tensor2D,
    input_sin_table: Tensor2D,
    input_x: Tensor2D,
) -> Tensor2D {
    Seq::new(input_cos_table.len(), |_row: int|
        row_projection_repr(seq![input_cos_table[_row]], seq![input_sin_table[_row]], seq![input_x[_row]])[0])
}

// Exact source-annotation domain at the chosen projection. No domain
// policy table weakens or interprets the source predicate.
pub open spec fn row_projection_domain(
    input_cos_table: Tensor2D,
    input_sin_table: Tensor2D,
    input_x: Tensor2D,
    rows: nat,
    i: nat,
) -> bool {
    let left = RawSide { cos_table: input_cos_table,
        sin_table: input_sin_table,
        x: input_x,
        o: row_projection_o_allocation(rows, 128),
        M: rows as int };
    let right = RawSide { cos_table: seq![input_cos_table[i as int]],
        sin_table: seq![input_sin_table[i as int]],
        x: seq![input_x[i as int]],
        o: row_projection_o_allocation(1, 128),
        M: 1 };
    let free = RawBatchInvarianceFree { b: i as int };
    raw_batch_invariance_raw_pre(left, right, free)
}


// Checked rectangular instantiation of the generated raw ContractIR theorem.
pub proof fn row_projection_certificate(
    input_cos_table: Tensor2D,
    input_sin_table: Tensor2D,
    input_x: Tensor2D,
    rows: nat,
    i: nat,
)
    requires
        TS::tensor2d_shape(input_cos_table, rows, 64),
        TS::tensor2d_shape(input_sin_table, rows, 64),
        TS::tensor2d_shape(input_x, rows, 128),
        row_projection_domain(input_cos_table, input_sin_table, input_x, rows, i),
        i < rows,
    ensures
        row_projection_repr(seq![input_cos_table[i as int]], seq![input_sin_table[i as int]], seq![input_x[i as int]])
            == seq![row_projection_repr(input_cos_table, input_sin_table, input_x)[i as int]],
{
    reveal(row_projection_domain);

    let left = RawSide {
        cos_table: input_cos_table,
        sin_table: input_sin_table,
        x: input_x,
        o: row_projection_o_allocation(rows, 128),
        M: rows as int,
    };
    let right = RawSide {
        cos_table: seq![input_cos_table[i as int]],
        sin_table: seq![input_sin_table[i as int]],
        x: seq![input_x[i as int]],
        o: row_projection_o_allocation(1, 128),
        M: 1,
    };
    let free = RawBatchInvarianceFree { b: i as int };
    assert(raw_batch_invariance_raw_pre(left, right, free)) by {
        reveal(row_projection_o_allocation);
        assert forall|r: int| 0 <= r < rows implies
            (#[trigger] input_cos_table[r]).len() == 64 by {};
        assert forall|r: int| 0 <= r < rows implies
            (#[trigger] input_sin_table[r]).len() == 64 by {};
        assert forall|r: int| 0 <= r < rows implies
            (#[trigger] input_x[r]).len() == 128 by {};
        assert forall|r0: int, r1: int|
            0 <= r0 < 1 && 0 <= r1 < 64 implies
            #[trigger] left.cos_table[i as int + r0][r1]
                == right.cos_table[r0][r1] by {
            assert(r0 == 0);
        };
        assert forall|r0: int, r1: int|
            0 <= r0 < 1 && 0 <= r1 < 64 implies
            #[trigger] left.sin_table[i as int + r0][r1]
                == right.sin_table[r0][r1] by {
            assert(r0 == 0);
        };
        assert forall|r0: int, r1: int|
            0 <= r0 < 1 && 0 <= r1 < 128 implies
            #[trigger] left.x[i as int + r0][r1]
                == right.x[r0][r1] by {
            assert(r0 == 0);
        };
    }
    raw_batch_invariance_certificate(left, right, free);
    let left_after = raw_execute(left);
    let right_after = raw_execute(right);
    assert(raw_batch_invariance_raw_post(left_after, right_after, free));
    reveal(raw_batch_invariance_raw_post);
    reveal(raw_execute);
    assert(left_after.M == rows as int);
    assert(right_after.M == 1);

    assert(0 <= i as int && i as int + 1 <= left_after.M);
    assert forall|c: int| 0 <= c < 128 implies
        (#[trigger] left_after.o[i as int][c])
            == right_after.o[0][c] by {
        assert(0 <= 0 < ((free.b + 1) - free.b));
        assert(0 <= c < 128);
        assert(left_after.o[free.b + 0][0 + c]
            == right_after.o[0 as int][0 + c]);
    };
    assert(left_after.o[i as int]
        =~= right_after.o[0]);
    reveal(row_projection_repr);
    assert(row_projection_repr(input_cos_table, input_sin_table, input_x)[i as int]
        == left_after.o[i as int]);
    assert(row_projection_repr(seq![input_cos_table[i as int]], seq![input_sin_table[i as int]], seq![input_x[i as int]])[0]
        == right_after.o[0]);
    assert(row_projection_repr(seq![input_cos_table[i as int]], seq![input_sin_table[i as int]], seq![input_x[i as int]])
        =~= seq![row_projection_repr(input_cos_table, input_sin_table, input_x)[i as int]]);
}

// The engine may use the mapped representation as its total row-local
// semantics.  For every valid rectangular launch, this checked theorem shows
// that it is exactly the generated raw whole-launch representation.
pub proof fn row_projection_launch_equivalence(
    input_cos_table: Tensor2D,
    input_sin_table: Tensor2D,
    input_x: Tensor2D,
    rows: nat,
)
    requires
        TS::tensor2d_shape(input_cos_table, rows, 64),
        TS::tensor2d_shape(input_sin_table, rows, 64),
        TS::tensor2d_shape(input_x, rows, 128),
        forall|row: nat| row < rows ==>
            #[trigger] row_projection_domain(input_cos_table, input_sin_table, input_x, rows, row),
    ensures
        row_projection_repr(input_cos_table, input_sin_table, input_x)
            == row_projection_mapped_repr(input_cos_table, input_sin_table, input_x),
{
    assert forall|_row: int| 0 <= _row < rows implies
        (#[trigger] row_projection_repr(input_cos_table, input_sin_table, input_x)[_row])
            == row_projection_mapped_repr(input_cos_table, input_sin_table, input_x)[_row] by {
        row_projection_certificate(input_cos_table, input_sin_table, input_x, rows,  _row as nat);
        reveal(row_projection_mapped_repr);
        assert(row_projection_repr(seq![input_cos_table[_row]], seq![input_sin_table[_row]], seq![input_x[_row]])[0]
            == row_projection_repr(input_cos_table, input_sin_table, input_x)[_row]);
    };
    assert(row_projection_repr(input_cos_table, input_sin_table, input_x)
        =~= row_projection_mapped_repr(input_cos_table, input_sin_table, input_x));
}

} // verus!
}

pub mod geometry_D_256_HD_128 {
use super::*;
verus! {
// Abstract interface for ONE fixed, separately qualified deployment.
// Alternative implementations prove this same theory; their outputs
// are not equated. See the separate implementation proof records.
// Raw ContractIR lowering for rope_kernel

pub open spec fn raw_batch_invariance_cdiv(numerator: int, denominator: int) -> int {
    (numerator + denominator - 1) / denominator
}

pub struct RawSide {
    pub x: Seq<Seq<Scalar>>,
    pub cos_table: Seq<Seq<Scalar>>,
    pub sin_table: Seq<Seq<Scalar>>,
    pub o: Seq<Seq<Scalar>>,
    pub M: int,
}

pub struct RawBatchInvarianceFree {
    pub b: int,
}


pub uninterp spec fn raw_o_cell(before: RawSide, _i0: int, _i1: int) -> Scalar;

pub open spec fn raw_o_after(before: RawSide)
    -> Seq<Seq<Scalar>>
{
    Seq::new(before.o.len(), |_i0: int| Seq::new(before.o[_i0].len(), |_i1: int| raw_o_cell(before, _i0, _i1)))
}

pub open spec fn raw_execute(before: RawSide) -> RawSide {
    RawSide {
        x: before.x,
        cos_table: before.cos_table,
        sin_table: before.sin_table,
        o: raw_o_after(before),
        M: before.M,
    }
}

pub open spec fn raw_batch_invariance_raw_pre(
    left: RawSide,
    right: RawSide,
    free: RawBatchInvarianceFree,
) -> bool {
    &&& 0 <= left.M
    &&& 0 <= 256
    &&& left.x.len() as int == left.M
    &&& forall|_s0: int| 0 <= _s0 < left.x.len() as int ==> (#[trigger] left.x[_s0]).len() as int == 256
    &&& 0 <= 128
    &&& left.cos_table.len() as int == left.M
    &&& forall|_s0: int| 0 <= _s0 < left.cos_table.len() as int ==> (#[trigger] left.cos_table[_s0]).len() as int == 128
    &&& left.sin_table.len() as int == left.M
    &&& forall|_s0: int| 0 <= _s0 < left.sin_table.len() as int ==> (#[trigger] left.sin_table[_s0]).len() as int == 128
    &&& left.o.len() as int == left.M
    &&& forall|_s0: int| 0 <= _s0 < left.o.len() as int ==> (#[trigger] left.o[_s0]).len() as int == 256
    &&& 0 <= right.M
    &&& right.x.len() as int == right.M
    &&& forall|_s0: int| 0 <= _s0 < right.x.len() as int ==> (#[trigger] right.x[_s0]).len() as int == 256
    &&& right.cos_table.len() as int == right.M
    &&& forall|_s0: int| 0 <= _s0 < right.cos_table.len() as int ==> (#[trigger] right.cos_table[_s0]).len() as int == 128
    &&& right.sin_table.len() as int == right.M
    &&& forall|_s0: int| 0 <= _s0 < right.sin_table.len() as int ==> (#[trigger] right.sin_table[_s0]).len() as int == 128
    &&& right.o.len() as int == right.M
    &&& forall|_s0: int| 0 <= _s0 < right.o.len() as int ==> (#[trigger] right.o[_s0]).len() as int == 256
    &&& right.M == 1
    &&& free.b >= 0
    &&& free.b < left.M
    &&& (0 <= free.b && free.b <= (free.b + 1) && (free.b + 1) <= left.M && 0 <= 0 && 0 <= 1 && 1 <= right.M && ((free.b + 1) - free.b) == (1 - 0) && 0 <= 0 && 0 <= 256 && 256 <= 256 && 0 <= 0 && 0 <= 256 && 256 <= 256 && (256 - 0) == (256 - 0) && forall|_r0: int, _r1: int| 0 <= _r0 < ((free.b + 1) - free.b) && 0 <= _r1 < (256 - 0) ==> #[trigger] left.x[free.b + _r0][0 + _r1] == right.x[0 + _r0][0 + _r1])
    &&& (0 <= free.b && free.b <= (free.b + 1) && (free.b + 1) <= left.M && 0 <= 0 && 0 <= 1 && 1 <= right.M && ((free.b + 1) - free.b) == (1 - 0) && 0 <= 0 && 0 <= 128 && 128 <= 128 && 0 <= 0 && 0 <= 128 && 128 <= 128 && (128 - 0) == (128 - 0) && forall|_r0: int, _r1: int| 0 <= _r0 < ((free.b + 1) - free.b) && 0 <= _r1 < (128 - 0) ==> #[trigger] left.cos_table[free.b + _r0][0 + _r1] == right.cos_table[0 + _r0][0 + _r1])
    &&& (0 <= free.b && free.b <= (free.b + 1) && (free.b + 1) <= left.M && 0 <= 0 && 0 <= 1 && 1 <= right.M && ((free.b + 1) - free.b) == (1 - 0) && 0 <= 0 && 0 <= 128 && 128 <= 128 && 0 <= 0 && 0 <= 128 && 128 <= 128 && (128 - 0) == (128 - 0) && forall|_r0: int, _r1: int| 0 <= _r0 < ((free.b + 1) - free.b) && 0 <= _r1 < (128 - 0) ==> #[trigger] left.sin_table[free.b + _r0][0 + _r1] == right.sin_table[0 + _r0][0 + _r1])
}

pub open spec fn raw_batch_invariance_raw_post(
    left: RawSide,
    right: RawSide,
    free: RawBatchInvarianceFree,
) -> bool {
    &&& (0 <= free.b && free.b <= (free.b + 1) && (free.b + 1) <= left.M && 0 <= 0 && 0 <= 1 && 1 <= right.M && ((free.b + 1) - free.b) == (1 - 0) && 0 <= 0 && 0 <= 256 && 256 <= 256 && 0 <= 0 && 0 <= 256 && 256 <= 256 && (256 - 0) == (256 - 0) && forall|_r0: int, _r1: int| 0 <= _r0 < ((free.b + 1) - free.b) && 0 <= _r1 < (256 - 0) ==> #[trigger] left.o[free.b + _r0][0 + _r1] == right.o[0 + _r0][0 + _r1])
}

// Trusted import of the relational theorem proved for the source and
// specialization named above.  The generated execute function preserves
// launch metadata and allocation shape; only written output cells are opaque.
#[verifier::external_body]
pub proof fn raw_batch_invariance_certificate(
    left: RawSide,
    right: RawSide,
    free: RawBatchInvarianceFree,
)
    requires raw_batch_invariance_raw_pre(left, right, free),
    ensures raw_batch_invariance_raw_post(
        raw_execute(left), raw_execute(right), free,
    ),
{
    unreachable!()
}

// BEGIN CHECKED RECTANGULAR ADAPTER

// Canonical framework values for the raw launch semantics.  Each pre-launch
// output is a generated rectangular allocation with the exact declared shape;
// the generated execute function replaces every logical output cell.
pub open spec fn row_projection_o_allocation(
    rows: nat,
    cols: nat,
) -> Tensor2D {
    Seq::new(rows, |_row: int| Seq::new(cols, |_col: int|
        generated_kernel_allocation_cell()))
}

pub open spec fn row_projection_repr(
    input_cos_table: Tensor2D,
    input_sin_table: Tensor2D,
    input_x: Tensor2D,
) -> Tensor2D {
    raw_o_after(RawSide {
        cos_table: input_cos_table,
        sin_table: input_sin_table,
        x: input_x,
        o: row_projection_o_allocation(input_cos_table.len(), 256),
        M: input_cos_table.len() as int,
    })
}

pub open spec fn row_projection_mapped_repr(
    input_cos_table: Tensor2D,
    input_sin_table: Tensor2D,
    input_x: Tensor2D,
) -> Tensor2D {
    Seq::new(input_cos_table.len(), |_row: int|
        row_projection_repr(seq![input_cos_table[_row]], seq![input_sin_table[_row]], seq![input_x[_row]])[0])
}

// Exact source-annotation domain at the chosen projection. No domain
// policy table weakens or interprets the source predicate.
pub open spec fn row_projection_domain(
    input_cos_table: Tensor2D,
    input_sin_table: Tensor2D,
    input_x: Tensor2D,
    rows: nat,
    i: nat,
) -> bool {
    let left = RawSide { cos_table: input_cos_table,
        sin_table: input_sin_table,
        x: input_x,
        o: row_projection_o_allocation(rows, 256),
        M: rows as int };
    let right = RawSide { cos_table: seq![input_cos_table[i as int]],
        sin_table: seq![input_sin_table[i as int]],
        x: seq![input_x[i as int]],
        o: row_projection_o_allocation(1, 256),
        M: 1 };
    let free = RawBatchInvarianceFree { b: i as int };
    raw_batch_invariance_raw_pre(left, right, free)
}


// Checked rectangular instantiation of the generated raw ContractIR theorem.
pub proof fn row_projection_certificate(
    input_cos_table: Tensor2D,
    input_sin_table: Tensor2D,
    input_x: Tensor2D,
    rows: nat,
    i: nat,
)
    requires
        TS::tensor2d_shape(input_cos_table, rows, 128),
        TS::tensor2d_shape(input_sin_table, rows, 128),
        TS::tensor2d_shape(input_x, rows, 256),
        row_projection_domain(input_cos_table, input_sin_table, input_x, rows, i),
        i < rows,
    ensures
        row_projection_repr(seq![input_cos_table[i as int]], seq![input_sin_table[i as int]], seq![input_x[i as int]])
            == seq![row_projection_repr(input_cos_table, input_sin_table, input_x)[i as int]],
{
    reveal(row_projection_domain);

    let left = RawSide {
        cos_table: input_cos_table,
        sin_table: input_sin_table,
        x: input_x,
        o: row_projection_o_allocation(rows, 256),
        M: rows as int,
    };
    let right = RawSide {
        cos_table: seq![input_cos_table[i as int]],
        sin_table: seq![input_sin_table[i as int]],
        x: seq![input_x[i as int]],
        o: row_projection_o_allocation(1, 256),
        M: 1,
    };
    let free = RawBatchInvarianceFree { b: i as int };
    assert(raw_batch_invariance_raw_pre(left, right, free)) by {
        reveal(row_projection_o_allocation);
        assert forall|r: int| 0 <= r < rows implies
            (#[trigger] input_cos_table[r]).len() == 128 by {};
        assert forall|r: int| 0 <= r < rows implies
            (#[trigger] input_sin_table[r]).len() == 128 by {};
        assert forall|r: int| 0 <= r < rows implies
            (#[trigger] input_x[r]).len() == 256 by {};
        assert forall|r0: int, r1: int|
            0 <= r0 < 1 && 0 <= r1 < 128 implies
            #[trigger] left.cos_table[i as int + r0][r1]
                == right.cos_table[r0][r1] by {
            assert(r0 == 0);
        };
        assert forall|r0: int, r1: int|
            0 <= r0 < 1 && 0 <= r1 < 128 implies
            #[trigger] left.sin_table[i as int + r0][r1]
                == right.sin_table[r0][r1] by {
            assert(r0 == 0);
        };
        assert forall|r0: int, r1: int|
            0 <= r0 < 1 && 0 <= r1 < 256 implies
            #[trigger] left.x[i as int + r0][r1]
                == right.x[r0][r1] by {
            assert(r0 == 0);
        };
    }
    raw_batch_invariance_certificate(left, right, free);
    let left_after = raw_execute(left);
    let right_after = raw_execute(right);
    assert(raw_batch_invariance_raw_post(left_after, right_after, free));
    reveal(raw_batch_invariance_raw_post);
    reveal(raw_execute);
    assert(left_after.M == rows as int);
    assert(right_after.M == 1);

    assert(0 <= i as int && i as int + 1 <= left_after.M);
    assert forall|c: int| 0 <= c < 256 implies
        (#[trigger] left_after.o[i as int][c])
            == right_after.o[0][c] by {
        assert(0 <= 0 < ((free.b + 1) - free.b));
        assert(0 <= c < 256);
        assert(left_after.o[free.b + 0][0 + c]
            == right_after.o[0 as int][0 + c]);
    };
    assert(left_after.o[i as int]
        =~= right_after.o[0]);
    reveal(row_projection_repr);
    assert(row_projection_repr(input_cos_table, input_sin_table, input_x)[i as int]
        == left_after.o[i as int]);
    assert(row_projection_repr(seq![input_cos_table[i as int]], seq![input_sin_table[i as int]], seq![input_x[i as int]])[0]
        == right_after.o[0]);
    assert(row_projection_repr(seq![input_cos_table[i as int]], seq![input_sin_table[i as int]], seq![input_x[i as int]])
        =~= seq![row_projection_repr(input_cos_table, input_sin_table, input_x)[i as int]]);
}

// The engine may use the mapped representation as its total row-local
// semantics.  For every valid rectangular launch, this checked theorem shows
// that it is exactly the generated raw whole-launch representation.
pub proof fn row_projection_launch_equivalence(
    input_cos_table: Tensor2D,
    input_sin_table: Tensor2D,
    input_x: Tensor2D,
    rows: nat,
)
    requires
        TS::tensor2d_shape(input_cos_table, rows, 128),
        TS::tensor2d_shape(input_sin_table, rows, 128),
        TS::tensor2d_shape(input_x, rows, 256),
        forall|row: nat| row < rows ==>
            #[trigger] row_projection_domain(input_cos_table, input_sin_table, input_x, rows, row),
    ensures
        row_projection_repr(input_cos_table, input_sin_table, input_x)
            == row_projection_mapped_repr(input_cos_table, input_sin_table, input_x),
{
    assert forall|_row: int| 0 <= _row < rows implies
        (#[trigger] row_projection_repr(input_cos_table, input_sin_table, input_x)[_row])
            == row_projection_mapped_repr(input_cos_table, input_sin_table, input_x)[_row] by {
        row_projection_certificate(input_cos_table, input_sin_table, input_x, rows,  _row as nat);
        reveal(row_projection_mapped_repr);
        assert(row_projection_repr(seq![input_cos_table[_row]], seq![input_sin_table[_row]], seq![input_x[_row]])[0]
            == row_projection_repr(input_cos_table, input_sin_table, input_x)[_row]);
    };
    assert(row_projection_repr(input_cos_table, input_sin_table, input_x)
        =~= row_projection_mapped_repr(input_cos_table, input_sin_table, input_x));
}

} // verus!
}

pub mod geometry_D_512_HD_256 {
use super::*;
verus! {
// Abstract interface for ONE fixed, separately qualified deployment.
// Alternative implementations prove this same theory; their outputs
// are not equated. See the separate implementation proof records.
// Raw ContractIR lowering for rope_kernel

pub open spec fn raw_batch_invariance_cdiv(numerator: int, denominator: int) -> int {
    (numerator + denominator - 1) / denominator
}

pub struct RawSide {
    pub x: Seq<Seq<Scalar>>,
    pub cos_table: Seq<Seq<Scalar>>,
    pub sin_table: Seq<Seq<Scalar>>,
    pub o: Seq<Seq<Scalar>>,
    pub M: int,
}

pub struct RawBatchInvarianceFree {
    pub b: int,
}


pub uninterp spec fn raw_o_cell(before: RawSide, _i0: int, _i1: int) -> Scalar;

pub open spec fn raw_o_after(before: RawSide)
    -> Seq<Seq<Scalar>>
{
    Seq::new(before.o.len(), |_i0: int| Seq::new(before.o[_i0].len(), |_i1: int| raw_o_cell(before, _i0, _i1)))
}

pub open spec fn raw_execute(before: RawSide) -> RawSide {
    RawSide {
        x: before.x,
        cos_table: before.cos_table,
        sin_table: before.sin_table,
        o: raw_o_after(before),
        M: before.M,
    }
}

pub open spec fn raw_batch_invariance_raw_pre(
    left: RawSide,
    right: RawSide,
    free: RawBatchInvarianceFree,
) -> bool {
    &&& 0 <= left.M
    &&& 0 <= 512
    &&& left.x.len() as int == left.M
    &&& forall|_s0: int| 0 <= _s0 < left.x.len() as int ==> (#[trigger] left.x[_s0]).len() as int == 512
    &&& 0 <= 256
    &&& left.cos_table.len() as int == left.M
    &&& forall|_s0: int| 0 <= _s0 < left.cos_table.len() as int ==> (#[trigger] left.cos_table[_s0]).len() as int == 256
    &&& left.sin_table.len() as int == left.M
    &&& forall|_s0: int| 0 <= _s0 < left.sin_table.len() as int ==> (#[trigger] left.sin_table[_s0]).len() as int == 256
    &&& left.o.len() as int == left.M
    &&& forall|_s0: int| 0 <= _s0 < left.o.len() as int ==> (#[trigger] left.o[_s0]).len() as int == 512
    &&& 0 <= right.M
    &&& right.x.len() as int == right.M
    &&& forall|_s0: int| 0 <= _s0 < right.x.len() as int ==> (#[trigger] right.x[_s0]).len() as int == 512
    &&& right.cos_table.len() as int == right.M
    &&& forall|_s0: int| 0 <= _s0 < right.cos_table.len() as int ==> (#[trigger] right.cos_table[_s0]).len() as int == 256
    &&& right.sin_table.len() as int == right.M
    &&& forall|_s0: int| 0 <= _s0 < right.sin_table.len() as int ==> (#[trigger] right.sin_table[_s0]).len() as int == 256
    &&& right.o.len() as int == right.M
    &&& forall|_s0: int| 0 <= _s0 < right.o.len() as int ==> (#[trigger] right.o[_s0]).len() as int == 512
    &&& right.M == 1
    &&& free.b >= 0
    &&& free.b < left.M
    &&& (0 <= free.b && free.b <= (free.b + 1) && (free.b + 1) <= left.M && 0 <= 0 && 0 <= 1 && 1 <= right.M && ((free.b + 1) - free.b) == (1 - 0) && 0 <= 0 && 0 <= 512 && 512 <= 512 && 0 <= 0 && 0 <= 512 && 512 <= 512 && (512 - 0) == (512 - 0) && forall|_r0: int, _r1: int| 0 <= _r0 < ((free.b + 1) - free.b) && 0 <= _r1 < (512 - 0) ==> #[trigger] left.x[free.b + _r0][0 + _r1] == right.x[0 + _r0][0 + _r1])
    &&& (0 <= free.b && free.b <= (free.b + 1) && (free.b + 1) <= left.M && 0 <= 0 && 0 <= 1 && 1 <= right.M && ((free.b + 1) - free.b) == (1 - 0) && 0 <= 0 && 0 <= 256 && 256 <= 256 && 0 <= 0 && 0 <= 256 && 256 <= 256 && (256 - 0) == (256 - 0) && forall|_r0: int, _r1: int| 0 <= _r0 < ((free.b + 1) - free.b) && 0 <= _r1 < (256 - 0) ==> #[trigger] left.cos_table[free.b + _r0][0 + _r1] == right.cos_table[0 + _r0][0 + _r1])
    &&& (0 <= free.b && free.b <= (free.b + 1) && (free.b + 1) <= left.M && 0 <= 0 && 0 <= 1 && 1 <= right.M && ((free.b + 1) - free.b) == (1 - 0) && 0 <= 0 && 0 <= 256 && 256 <= 256 && 0 <= 0 && 0 <= 256 && 256 <= 256 && (256 - 0) == (256 - 0) && forall|_r0: int, _r1: int| 0 <= _r0 < ((free.b + 1) - free.b) && 0 <= _r1 < (256 - 0) ==> #[trigger] left.sin_table[free.b + _r0][0 + _r1] == right.sin_table[0 + _r0][0 + _r1])
}

pub open spec fn raw_batch_invariance_raw_post(
    left: RawSide,
    right: RawSide,
    free: RawBatchInvarianceFree,
) -> bool {
    &&& (0 <= free.b && free.b <= (free.b + 1) && (free.b + 1) <= left.M && 0 <= 0 && 0 <= 1 && 1 <= right.M && ((free.b + 1) - free.b) == (1 - 0) && 0 <= 0 && 0 <= 512 && 512 <= 512 && 0 <= 0 && 0 <= 512 && 512 <= 512 && (512 - 0) == (512 - 0) && forall|_r0: int, _r1: int| 0 <= _r0 < ((free.b + 1) - free.b) && 0 <= _r1 < (512 - 0) ==> #[trigger] left.o[free.b + _r0][0 + _r1] == right.o[0 + _r0][0 + _r1])
}

// Trusted import of the relational theorem proved for the source and
// specialization named above.  The generated execute function preserves
// launch metadata and allocation shape; only written output cells are opaque.
#[verifier::external_body]
pub proof fn raw_batch_invariance_certificate(
    left: RawSide,
    right: RawSide,
    free: RawBatchInvarianceFree,
)
    requires raw_batch_invariance_raw_pre(left, right, free),
    ensures raw_batch_invariance_raw_post(
        raw_execute(left), raw_execute(right), free,
    ),
{
    unreachable!()
}

// BEGIN CHECKED RECTANGULAR ADAPTER

// Canonical framework values for the raw launch semantics.  Each pre-launch
// output is a generated rectangular allocation with the exact declared shape;
// the generated execute function replaces every logical output cell.
pub open spec fn row_projection_o_allocation(
    rows: nat,
    cols: nat,
) -> Tensor2D {
    Seq::new(rows, |_row: int| Seq::new(cols, |_col: int|
        generated_kernel_allocation_cell()))
}

pub open spec fn row_projection_repr(
    input_cos_table: Tensor2D,
    input_sin_table: Tensor2D,
    input_x: Tensor2D,
) -> Tensor2D {
    raw_o_after(RawSide {
        cos_table: input_cos_table,
        sin_table: input_sin_table,
        x: input_x,
        o: row_projection_o_allocation(input_cos_table.len(), 512),
        M: input_cos_table.len() as int,
    })
}

pub open spec fn row_projection_mapped_repr(
    input_cos_table: Tensor2D,
    input_sin_table: Tensor2D,
    input_x: Tensor2D,
) -> Tensor2D {
    Seq::new(input_cos_table.len(), |_row: int|
        row_projection_repr(seq![input_cos_table[_row]], seq![input_sin_table[_row]], seq![input_x[_row]])[0])
}

// Exact source-annotation domain at the chosen projection. No domain
// policy table weakens or interprets the source predicate.
pub open spec fn row_projection_domain(
    input_cos_table: Tensor2D,
    input_sin_table: Tensor2D,
    input_x: Tensor2D,
    rows: nat,
    i: nat,
) -> bool {
    let left = RawSide { cos_table: input_cos_table,
        sin_table: input_sin_table,
        x: input_x,
        o: row_projection_o_allocation(rows, 512),
        M: rows as int };
    let right = RawSide { cos_table: seq![input_cos_table[i as int]],
        sin_table: seq![input_sin_table[i as int]],
        x: seq![input_x[i as int]],
        o: row_projection_o_allocation(1, 512),
        M: 1 };
    let free = RawBatchInvarianceFree { b: i as int };
    raw_batch_invariance_raw_pre(left, right, free)
}


// Checked rectangular instantiation of the generated raw ContractIR theorem.
pub proof fn row_projection_certificate(
    input_cos_table: Tensor2D,
    input_sin_table: Tensor2D,
    input_x: Tensor2D,
    rows: nat,
    i: nat,
)
    requires
        TS::tensor2d_shape(input_cos_table, rows, 256),
        TS::tensor2d_shape(input_sin_table, rows, 256),
        TS::tensor2d_shape(input_x, rows, 512),
        row_projection_domain(input_cos_table, input_sin_table, input_x, rows, i),
        i < rows,
    ensures
        row_projection_repr(seq![input_cos_table[i as int]], seq![input_sin_table[i as int]], seq![input_x[i as int]])
            == seq![row_projection_repr(input_cos_table, input_sin_table, input_x)[i as int]],
{
    reveal(row_projection_domain);

    let left = RawSide {
        cos_table: input_cos_table,
        sin_table: input_sin_table,
        x: input_x,
        o: row_projection_o_allocation(rows, 512),
        M: rows as int,
    };
    let right = RawSide {
        cos_table: seq![input_cos_table[i as int]],
        sin_table: seq![input_sin_table[i as int]],
        x: seq![input_x[i as int]],
        o: row_projection_o_allocation(1, 512),
        M: 1,
    };
    let free = RawBatchInvarianceFree { b: i as int };
    assert(raw_batch_invariance_raw_pre(left, right, free)) by {
        reveal(row_projection_o_allocation);
        assert forall|r: int| 0 <= r < rows implies
            (#[trigger] input_cos_table[r]).len() == 256 by {};
        assert forall|r: int| 0 <= r < rows implies
            (#[trigger] input_sin_table[r]).len() == 256 by {};
        assert forall|r: int| 0 <= r < rows implies
            (#[trigger] input_x[r]).len() == 512 by {};
        assert forall|r0: int, r1: int|
            0 <= r0 < 1 && 0 <= r1 < 256 implies
            #[trigger] left.cos_table[i as int + r0][r1]
                == right.cos_table[r0][r1] by {
            assert(r0 == 0);
        };
        assert forall|r0: int, r1: int|
            0 <= r0 < 1 && 0 <= r1 < 256 implies
            #[trigger] left.sin_table[i as int + r0][r1]
                == right.sin_table[r0][r1] by {
            assert(r0 == 0);
        };
        assert forall|r0: int, r1: int|
            0 <= r0 < 1 && 0 <= r1 < 512 implies
            #[trigger] left.x[i as int + r0][r1]
                == right.x[r0][r1] by {
            assert(r0 == 0);
        };
    }
    raw_batch_invariance_certificate(left, right, free);
    let left_after = raw_execute(left);
    let right_after = raw_execute(right);
    assert(raw_batch_invariance_raw_post(left_after, right_after, free));
    reveal(raw_batch_invariance_raw_post);
    reveal(raw_execute);
    assert(left_after.M == rows as int);
    assert(right_after.M == 1);

    assert(0 <= i as int && i as int + 1 <= left_after.M);
    assert forall|c: int| 0 <= c < 512 implies
        (#[trigger] left_after.o[i as int][c])
            == right_after.o[0][c] by {
        assert(0 <= 0 < ((free.b + 1) - free.b));
        assert(0 <= c < 512);
        assert(left_after.o[free.b + 0][0 + c]
            == right_after.o[0 as int][0 + c]);
    };
    assert(left_after.o[i as int]
        =~= right_after.o[0]);
    reveal(row_projection_repr);
    assert(row_projection_repr(input_cos_table, input_sin_table, input_x)[i as int]
        == left_after.o[i as int]);
    assert(row_projection_repr(seq![input_cos_table[i as int]], seq![input_sin_table[i as int]], seq![input_x[i as int]])[0]
        == right_after.o[0]);
    assert(row_projection_repr(seq![input_cos_table[i as int]], seq![input_sin_table[i as int]], seq![input_x[i as int]])
        =~= seq![row_projection_repr(input_cos_table, input_sin_table, input_x)[i as int]]);
}

// The engine may use the mapped representation as its total row-local
// semantics.  For every valid rectangular launch, this checked theorem shows
// that it is exactly the generated raw whole-launch representation.
pub proof fn row_projection_launch_equivalence(
    input_cos_table: Tensor2D,
    input_sin_table: Tensor2D,
    input_x: Tensor2D,
    rows: nat,
)
    requires
        TS::tensor2d_shape(input_cos_table, rows, 256),
        TS::tensor2d_shape(input_sin_table, rows, 256),
        TS::tensor2d_shape(input_x, rows, 512),
        forall|row: nat| row < rows ==>
            #[trigger] row_projection_domain(input_cos_table, input_sin_table, input_x, rows, row),
    ensures
        row_projection_repr(input_cos_table, input_sin_table, input_x)
            == row_projection_mapped_repr(input_cos_table, input_sin_table, input_x),
{
    assert forall|_row: int| 0 <= _row < rows implies
        (#[trigger] row_projection_repr(input_cos_table, input_sin_table, input_x)[_row])
            == row_projection_mapped_repr(input_cos_table, input_sin_table, input_x)[_row] by {
        row_projection_certificate(input_cos_table, input_sin_table, input_x, rows,  _row as nat);
        reveal(row_projection_mapped_repr);
        assert(row_projection_repr(seq![input_cos_table[_row]], seq![input_sin_table[_row]], seq![input_x[_row]])[0]
            == row_projection_repr(input_cos_table, input_sin_table, input_x)[_row]);
    };
    assert(row_projection_repr(input_cos_table, input_sin_table, input_x)
        =~= row_projection_mapped_repr(input_cos_table, input_sin_table, input_x));
}

} // verus!
}

// BEGIN CHECKED GEOMETRY DISPATCH
verus! {
pub open spec fn geometry_valid(D: nat, HD: nat) -> bool {
    if D == 128 && HD == 64 {
        true
    } else if D == 256 && HD == 128 {
        true
    } else if D == 512 && HD == 256 {
        true
    } else { false }
}

pub open spec fn launch_valid(input_cos_table: Tensor2D, input_sin_table: Tensor2D, input_x: Tensor2D, D: nat, HD: nat) -> bool {
    if D == 128 && HD == 64 {
        (TS::tensor2d_shape(input_cos_table, input_cos_table.len(), 64))
        && (TS::tensor2d_shape(input_sin_table, input_cos_table.len(), 64))
        && (TS::tensor2d_shape(input_x, input_cos_table.len(), 128))
        && (forall|row: nat| row < input_cos_table.len() ==>
            #[trigger] geometry_D_128_HD_64::row_projection_domain(input_cos_table, input_sin_table, input_x, input_cos_table.len(), row))
    } else if D == 256 && HD == 128 {
        (TS::tensor2d_shape(input_cos_table, input_cos_table.len(), 128))
        && (TS::tensor2d_shape(input_sin_table, input_cos_table.len(), 128))
        && (TS::tensor2d_shape(input_x, input_cos_table.len(), 256))
        && (forall|row: nat| row < input_cos_table.len() ==>
            #[trigger] geometry_D_256_HD_128::row_projection_domain(input_cos_table, input_sin_table, input_x, input_cos_table.len(), row))
    } else if D == 512 && HD == 256 {
        (TS::tensor2d_shape(input_cos_table, input_cos_table.len(), 256))
        && (TS::tensor2d_shape(input_sin_table, input_cos_table.len(), 256))
        && (TS::tensor2d_shape(input_x, input_cos_table.len(), 512))
        && (forall|row: nat| row < input_cos_table.len() ==>
            #[trigger] geometry_D_512_HD_256::row_projection_domain(input_cos_table, input_sin_table, input_x, input_cos_table.len(), row))
    } else { false }
}

pub open spec fn raw_output(input_cos_table: Tensor2D, input_sin_table: Tensor2D, input_x: Tensor2D, D: nat, HD: nat) -> Option<Tensor2D> {
    if D == 128 && HD == 64 {
        Some(geometry_D_128_HD_64::row_projection_repr(input_cos_table, input_sin_table, input_x))
    } else if D == 256 && HD == 128 {
        Some(geometry_D_256_HD_128::row_projection_repr(input_cos_table, input_sin_table, input_x))
    } else if D == 512 && HD == 256 {
        Some(geometry_D_512_HD_256::row_projection_repr(input_cos_table, input_sin_table, input_x))
    } else { None }
}

pub open spec fn mapped_output(input_cos_table: Tensor2D, input_sin_table: Tensor2D, input_x: Tensor2D, D: nat, HD: nat) -> Option<Tensor2D> {
    if D == 128 && HD == 64 {
        Some(geometry_D_128_HD_64::row_projection_mapped_repr(input_cos_table, input_sin_table, input_x))
    } else if D == 256 && HD == 128 {
        Some(geometry_D_256_HD_128::row_projection_mapped_repr(input_cos_table, input_sin_table, input_x))
    } else if D == 512 && HD == 256 {
        Some(geometry_D_512_HD_256::row_projection_mapped_repr(input_cos_table, input_sin_table, input_x))
    } else { None }
}

// A public row map independent of the generated geometry module names.
pub open spec fn row_mapped_output(input_cos_table: Tensor2D, input_sin_table: Tensor2D, input_x: Tensor2D, D: nat, HD: nat) -> Option<Tensor2D> {
    if geometry_valid(D, HD) { Some(Seq::new(input_cos_table.len(), |row: int| raw_output(seq![input_cos_table[row]], seq![input_sin_table[row]], seq![input_x[row]], D, HD).unwrap()[0])) } else { None }
}

pub proof fn checked_row_map(input_cos_table: Tensor2D, input_sin_table: Tensor2D, input_x: Tensor2D, D: nat, HD: nat)
    ensures mapped_output(input_cos_table, input_sin_table, input_x, D, HD) == row_mapped_output(input_cos_table, input_sin_table, input_x, D, HD),
{
    let mapped = mapped_output(input_cos_table, input_sin_table, input_x, D, HD).unwrap();
    let row_map = row_mapped_output(input_cos_table, input_sin_table, input_x, D, HD).unwrap();
    if D == 128 && HD == 64 {
        assert(mapped =~= row_map);
    } else if D == 256 && HD == 128 {
        assert(mapped =~= row_map);
    } else if D == 512 && HD == 256 {
        assert(mapped =~= row_map);
    } else {  }
}

pub proof fn checked_launch_equivalence(input_cos_table: Tensor2D, input_sin_table: Tensor2D, input_x: Tensor2D, D: nat, HD: nat)
    requires launch_valid(input_cos_table, input_sin_table, input_x, D, HD),
    ensures geometry_valid(D, HD),
        raw_output(input_cos_table, input_sin_table, input_x, D, HD).is_some(),
        raw_output(input_cos_table, input_sin_table, input_x, D, HD) == mapped_output(input_cos_table, input_sin_table, input_x, D, HD),
        raw_output(input_cos_table, input_sin_table, input_x, D, HD) == row_mapped_output(input_cos_table, input_sin_table, input_x, D, HD),
{
    checked_row_map(input_cos_table, input_sin_table, input_x, D, HD);
    if D == 128 && HD == 64 {
        geometry_D_128_HD_64::row_projection_launch_equivalence(input_cos_table, input_sin_table, input_x, input_cos_table.len());
    } else if D == 256 && HD == 128 {
        geometry_D_256_HD_128::row_projection_launch_equivalence(input_cos_table, input_sin_table, input_x, input_cos_table.len());
    } else if D == 512 && HD == 256 {
        geometry_D_512_HD_256::row_projection_launch_equivalence(input_cos_table, input_sin_table, input_x, input_cos_table.len());
    } else { assert(false); }
}
} // verus!
