"""Compose qualified raw attention interfaces behind model-geometry dispatch.

The dispatch keys are inferred from the checked typed adapters, never from a
model-family name. Every branch has a checked raw-to-mapped binding. Missing
geometry is an explicit None, not an arbitrary fallback numerical operation.
"""

from dataclasses import dataclass
import hashlib
import json
from pathlib import Path
import re

from ir.relational_artifact import VerifiedDataflowContract
from scripts.verification.paged_attention_adapter_codegen import (
    PagedAttentionBinding, RenderedPagedAttentionInterface, render_checked_paged_attention_interface,
    paged_attention_geometry,
)


@dataclass(frozen=True)
class RenderedAttentionCatalog:
    body: str
    interfaces: tuple[tuple[bool, int, RenderedPagedAttentionInterface], ...]

    def manifest(self) -> str:
        return json.dumps({
            "schema_version": 1,
            "kind": "geometry_dispatched_attention_interfaces",
            "generated_body_sha256": hashlib.sha256(self.body.encode()).hexdigest(),
            "interfaces": [dict(sliding_window=swa, head_dim=dim,
                raw=json.loads(adapter.raw.manifest()),
                checked_adapter_sha256=hashlib.sha256(adapter.adapter_body.encode()).hexdigest())
                for swa, dim, adapter in self.interfaces],
        }, sort_keys=True, indent=2) + "\n"


def render_attention_catalog(
    implementations: tuple[tuple[tuple[VerifiedDataflowContract, ...], PagedAttentionBinding], ...],
) -> RenderedAttentionCatalog:
    if not implementations:
        raise ValueError("attention catalog has no qualified implementations")
    groups = {}
    for contracts, binding in implementations:
        if not contracts:
            raise ValueError("attention catalog has an empty implementation")
        geometry = paged_attention_geometry(contracts, binding)
        swa, dim = binding.window is not None, geometry.head_dim
        groups.setdefault((swa, dim), []).append((contracts, binding))
    interfaces = []
    modules = []
    branches = {name: [] for name in ("VALID", "OPERATION", "RAW", "NUMERIC", "PROOF")}
    for (swa, dim), alternatives in sorted(groups.items()):
        binding = alternatives[0][1]
        if any(other != binding for _, other in alternatives):
            raise ValueError("one attention geometry has inconsistent role bindings")
        adapter = render_checked_paged_attention_interface(tuple(c for c, _ in alternatives),
                                                           symbol_prefix="raw", binding=binding)
        interfaces.append((swa, dim, adapter))
        name = f'{"swa" if swa else "full"}_d{dim}'
        variant = "SlidingWindow" if swa else "Full"
        guard = f"kind == AttentionKind::{variant} && geometry.head_dim == {dim}"
        modules.append(f"pub mod {name} {{\nuse vstd::prelude::*;\n{adapter.body}\n}}\n")
        expressions = {
            "VALID": f"{name}::model_binding_valid(geometry, window)",
            "OPERATION": f"{name}::bound_row_operation(geometry, scale, window, fill)",
            "RAW": f"if {name}::model_binding_valid(geometry, window) {{\n"
                   f"            Some({name}::adapter_output(q, k, v, table, cu_q, cu_k, max_q,\n"
                   "                geometry.num_attention_heads, geometry.num_key_value_heads, scale, window, fill))\n"
                   "        } else { None }",
            "NUMERIC": f"{name}::launch_runtime_assumptions(q, k, v, table, cu_q, cu_k,\n"
                       "            geometry.num_attention_heads, geometry.num_key_value_heads, scale, window, fill)",
            "PROOF": f"{name}::checked_bound_launch_equivalence(q, k, v, table, cu_q, cu_k, max_q, max_k,\n"
                     "            geometry, scale, window, fill);",
        }
        for role, expression in expressions.items():
            branches[role].append(f"if {guard} {{\n        {expression}\n    }}")
    values = {role: " else ".join(items) + " else { " + (
        "false" if role in {"VALID", "NUMERIC"} else "assert(false);" if role == "PROOF" else "None"
    ) + " }" for role, items in branches.items()}
    template = (Path(__file__).parent / "templates/attention_interface_catalog.rs").read_text()
    dispatch = re.sub(r"__([A-Z_]+)__", lambda match: values[match[1]], template)
    if "external_body" in dispatch or "assume(" in dispatch:
        raise ValueError("attention dispatch must not add trusted proof bodies")
    body = ("// @generated by scripts/verification/attention_interface_catalog.py; DO NOT EDIT.\n"
            + "\n".join(modules) + dispatch)
    return RenderedAttentionCatalog(body, tuple(interfaces))
