"""Checked row-scatter adapter over annotation-generated temporal contracts.

The raw assumptions come exclusively from qualified artifacts. This project's
row-scatter port mapping and the normalized copy/frame conclusions below are
checked Verus code, not additional kernel axioms. Geometry is taken from the
declared tensor types, never a model-family or launch-tile table.
"""

import hashlib
import json
from dataclasses import dataclass, fields, is_dataclass

from ir import annotations as ann
from ir.exact_effect_artifact import VerifiedExactEffectContract
from scripts.verification.kernel_interface_codegen import render_kernel_interface


HEADER = """// @generated by scripts/verification/verify_mutation_interfaces.py; DO NOT EDIT.
#![allow(non_snake_case)]
use vstd::prelude::*;
use crate::{boundary::scalar::{Scalar}, proof::tensor::types::{Tensor2D, IntTensor1D}};

"""


def _require(condition, message):
    if not condition:
        raise ValueError("mutation interface: " + message)


@dataclass(frozen=True)
class ScatterBinding:
    """Representation roles inferred from a qualified row-scatter signature.

    This is naming/geometry data, not evidence of the copy/frame conclusions.
    Those conclusions are established by the generated checked adapter.
    """

    source: str
    destination: str
    indices: str
    row_count: str
    slot_count: str
    width_symbol: str
    width: int


def infer_scatter_binding(effect):
    _require(isinstance(effect, VerifiedExactEffectContract), "expected an exact-effect theorem")
    data = effect.to_data()
    execution = data["plan"]["execution"]
    params = {p["name"]: p for p in execution["parameters"]}
    written = data["plan"]["written_tensors"]
    _require(len(written) == 1 and len(params) == 3, "unsupported row-scatter ports")
    destination, = written

    def shape(name, kind, rank):
        typ = params[name]["declared_type"]
        _require(typ.get("kind") == "tensor" and typ.get("element") == {"kind": kind}
                 and len(typ["shape"]) == rank
                 and all(d.get("kind") == "var" for d in typ["shape"]),
                 "unsupported declared scatter geometry")
        return tuple(d["name"] for d in typ["shape"])

    # Destination is the sole write. Of the two remaining ports, types identify
    # the row values and integer indices uniquely; no identifier is inspected.
    remaining = set(params) - {destination}
    sources = [name for name in remaining
               if params[name]["declared_type"].get("element") == {"kind": "float"}]
    _require(len(sources) == 1, "ambiguous row-scatter source")
    source, = sources
    indices, = remaining - {source}
    rows, width_symbol = shape(source, "float", 2)
    slots, dest_width = shape(destination, "float", 2)
    _require(shape(indices, "int", 1) == (rows,) and dest_width == width_symbol
             and len({rows, slots, width_symbol}) == 3, "incompatible scatter extents")
    _require(rows not in execution["constants"] and slots not in execution["constants"],
             "scatter row and slot extents must remain dynamic")
    static = execution["constants"].get(width_symbol)
    _require(isinstance(static, dict) and static.get("kind") == "int"
             and type(static.get("value")) is int and static["value"] > 0, "missing positive row width")
    return ScatterBinding(source, destination, indices, rows, slots, width_symbol, static["value"])


def _geometry(contracts):
    effects = [c for c in contracts if isinstance(c, VerifiedExactEffectContract)]
    _require(len(effects) == 1, "one exact-effect theorem is required")
    effect, = effects
    execution = effect.to_data()["plan"]["execution"]
    return infer_scatter_binding(effect), (execution["kernel"], execution["source_sha256"]), effect


ADAPTER = '''
// BEGIN CHECKED MUTATION ADAPTER
// Canonical physical dtype identities for a fixed deployed float/int interface.
// Their physical interpretation is required by the raw correspondence premises.
pub uninterp spec fn float_dtype() -> @DTYPE@;
pub uninterp spec fn int_dtype() -> @DTYPE@;

pub open spec fn before(rows: Tensor2D, cache: Tensor2D, slots: IntTensor1D) -> @SIDE@ {
    @SIDE@ {
        @SOURCE@: rows, @DESTINATION@: cache, @INDICES@: slots,
        @ROWS@: rows.len() as int, @SLOTS@: cache.len() as int,
        __element_dtype_@SOURCE@: float_dtype(), __element_dtype_@DESTINATION@: float_dtype(),
        __element_dtype_@INDICES@: int_dtype(),
    }
}

pub open spec fn domain(rows: Tensor2D, cache: Tensor2D, slots: IntTensor1D) -> bool {
    @PRE@(before(rows, cache, slots), @FREE@ {})
}

pub open spec fn output(rows: Tensor2D, cache: Tensor2D, slots: IntTensor1D) -> Tensor2D {
    @EXEC@(before(rows, cache, slots)).@DESTINATION@
}

pub proof fn checked_copy(rows: Tensor2D, cache: Tensor2D, slots: IntTensor1D, i: int)
    requires domain(rows, cache, slots), 0 <= i < rows.len(), slots[i] >= 0,
    ensures 0 <= slots[i] < cache.len(), output(rows, cache, slots)[slots[i]] == rows[i],
{
    let launch = before(rows, cache, slots);
    let free = @FREE@ {};
    @CERT@(launch, free);
    let after = @EXEC@(launch);
    assert(@COPY_QUANTIFIER@(launch, after, free, i));
    assert forall|c: int| 0 <= c < @WIDTH@ implies
        #[trigger] after.@DESTINATION@[slots[i]][c] == rows[i][c] by {
        assert(@COPY_REGION@(launch, after, free, i, 0, c));
    }
    assert(after.@DESTINATION@[slots[i]] =~= rows[i]);
}

pub proof fn checked_frame(rows: Tensor2D, cache: Tensor2D, slots: IntTensor1D, s: int)
    requires domain(rows, cache, slots), 0 <= s < cache.len(),
        forall|i: int| 0 <= i < slots.len() ==> (#[trigger] slots[i]) != s,
    ensures output(rows, cache, slots)[s] == cache[s],
{
    let launch = before(rows, cache, slots);
    let free = @FREE@ {};
    @CERT@(launch, free);
    let after = @EXEC@(launch);
    assert forall|i: int| #[trigger] @FRAME_GUARD@(launch, after, free, s, i) by {}
    assert(@FRAME_QUANTIFIER@(launch, after, free, s));
    assert forall|c: int| 0 <= c < @WIDTH@ implies
        #[trigger] after.@DESTINATION@[s][c] == cache[s][c] by {
        assert(@FRAME_REGION@(launch, after, free, s, 0, c));
    }
    assert(after.@DESTINATION@[s] =~= cache[s]);
}
// END CHECKED MUTATION ADAPTER
'''


def _contains(tree, target):
    if tree == target:
        return True
    if isinstance(tree, (list, tuple)):
        return any(_contains(item, target) for item in tree)
    if is_dataclass(tree):
        return any(_contains(getattr(tree, field.name), target) for field in fields(tree))
    return False


def render_mutation_adapter(fragment, binding):
    """Bind transparent helpers by typed copy/frame structure, not numbering.

    This is the project's supported row-scatter representation adapter, not a
    proof of the selected facts. Verus checks the resulting copy/frame lemmas.
    Ambiguous or differently scoped propositions require a new checked adapter.
    """
    def unique(candidates):
        candidates = list(candidates)
        _require(len(candidates) == 1, "ambiguous or unsupported scatter proposition")
        return candidates[0]

    _require(isinstance(binding, ScatterBinding), "expected typed scatter binding")
    _require(fragment.output_parameters == (binding.destination,)
             and set(fragment.dtype_parameters) == {binding.source, binding.destination, binding.indices},
             "scatter binding differs from raw execution ports")
    names = dict(WIDTH=str(binding.width), SOURCE=binding.source, DESTINATION=binding.destination,
        INDICES=binding.indices, ROWS=binding.row_count, SLOTS=binding.slot_count,
        DTYPE=fragment.dtype_type, SIDE=fragment.side_type, FREE=fragment.free_type,
        PRE=fragment.pre_name, CERT=fragment.certificate_name, EXEC=fragment.execute_name)
    for role, source in (("COPY", binding.source), ("FRAME", binding.destination)):
        region = unique(h for h in fragment.helpers
            if isinstance(h.proposition, ann.RegionEquiv)
            and h.proposition.left.side == ann.After(binding.destination)
            and h.proposition.right.side == ann.Before(source))
        _require(len(region.binders) == 1 and len(region.proposition.left.slices) == 2,
                 "scatter region must be a single quantified row")
        quantified = unique(h for h in fragment.helpers
            if isinstance(h.proposition, ann.ForAllConstraint)
            and h.binders == region.binders and _contains(h.proposition, region.proposition))
        names[role + "_REGION"] = region.name
        names[role + "_QUANTIFIER"] = quantified.name
        if role == "FRAME":
            guard = unique(h for h in fragment.helpers
                if isinstance(h.proposition, ann.ForAllConstraint)
                and len(h.binders) == 2 and h.binders[:1] == region.binders
                and _contains(quantified.proposition, h.proposition))
            names["FRAME_GUARD"] = guard.name
    body = ADAPTER
    for name, value in names.items():
        body = body.replace("@" + name + "@", value)
    return body


def render_mutation_interface(cases):
    """Assemble qualified geometry modules and checked, config-free row facts."""
    cases = tuple(cases)
    groups = {}
    source = None
    contributions = []
    for contract, constants, families, qualified in cases:
        binding, identity, effect = _geometry(qualified.contracts)
        if source is None:
            source = identity
        _require(identity == source, "mixed scatter sources")
        # The engine consumes exact effects; batch qualification is retained in
        # the receipt, but importing its unused relational axiom is unnecessary.
        groups.setdefault((binding.width_symbol, binding.width), []).append((effect,))
        contributions.append(dict(source=contract["source"], kernel=contract["kernel"],
            constants=constants, families=sorted(families),
            execution_identity=effect.execution_identity,
            structural_contract_digest=qualified.receipt["structural_contract_digest"]))
    _require(bool(groups), "no qualified mutation cases")
    bodies, records = [], []
    branches = {name: [] for name in ("domain", "output", "copy", "frame", "shape")}
    for (width_symbol, width), implementations in sorted(groups.items()):
        raw = render_kernel_interface(tuple(implementations), symbol_prefix="raw")
        binding = infer_scatter_binding(implementations[0][0])
        adapter = render_mutation_adapter(raw.representative.contracts[0], binding)
        module = f"geometry_{width_symbol}_{width}"
        bodies.append(f"pub mod {module} {{\nuse super::*;\nverus! {{\n" + raw.body + adapter
                      + "\n} // verus!\n}\n")
        records.append(dict(module=module, geometry={width_symbol: width}, raw=json.loads(raw.manifest()),
                            checked_adapter_sha256=hashlib.sha256(
                                adapter.partition("\n// BEGIN CHECKED MUTATION ADAPTER\n")[2].encode()).hexdigest()))
        for name, expression in dict(
            domain=f"{module}::domain(rows, cache, slots)",
            output=f"{module}::output(rows, cache, slots)",
            copy=f"{module}::checked_copy(rows, cache, slots, i);",
            frame=f"{module}::checked_frame(rows, cache, slots, s);",
            shape="",
        ).items():
            branches[name].append(f"if width == {width} {{ {expression} }}")
    def expression(name, fallback=None):
        return " else ".join(branches[name]) + (f" else {{ {fallback} }}" if fallback is not None else "")
    dispatch = f'''verus! {{
pub open spec fn domain(rows: Tensor2D, cache: Tensor2D, slots: IntTensor1D, width: nat) -> bool {{
    {expression("domain", "false")}
}}
pub open spec fn output(rows: Tensor2D, cache: Tensor2D, slots: IntTensor1D, width: nat) -> Tensor2D {{
    {expression("output", "Seq::empty()")}
}}
pub proof fn checked_copy(rows: Tensor2D, cache: Tensor2D, slots: IntTensor1D, width: nat, i: int)
    requires domain(rows, cache, slots, width), 0 <= i < rows.len(), slots[i] >= 0,
    ensures 0 <= slots[i] < cache.len(), output(rows, cache, slots, width)[slots[i]] == rows[i],
{{
    {expression("copy")}
}}
pub proof fn checked_frame(rows: Tensor2D, cache: Tensor2D, slots: IntTensor1D, width: nat, s: int)
    requires domain(rows, cache, slots, width), 0 <= s < cache.len(),
        forall|i: int| 0 <= i < slots.len() ==> (#[trigger] slots[i]) != s,
    ensures output(rows, cache, slots, width)[s] == cache[s],
{{
    {expression("frame")}
}}
pub proof fn checked_shape(rows: Tensor2D, cache: Tensor2D, slots: IntTensor1D, width: nat)
    requires domain(rows, cache, slots, width),
    ensures output(rows, cache, slots, width).len() == cache.len(),
{{
    {expression("shape")}
}}
}} // verus!
'''
    body = HEADER + "\n".join(bodies) + "\n// BEGIN CHECKED GEOMETRY DISPATCH\n" + dispatch
    manifest = dict(schema_version=1, kind="geometry_dispatched_mutation_interface",
        generated_body_sha256=hashlib.sha256(body.encode()).hexdigest(),
        checked_dispatch_sha256=hashlib.sha256(dispatch.encode()).hexdigest(),
        dimensions=sorted({symbol for symbol, _ in groups}), interfaces=records, inventory_contributions=contributions)
    return body, json.dumps(manifest, indent=2, sort_keys=True) + "\n"
