#!/usr/bin/env python3
"""Qualify and assemble model-neutral rectangular kernel interfaces.

The operator table selects source entrypoints, not manual theorem bindings.
Types, domains and row semantics come from the qualified annotations.
"""

import argparse
import hashlib
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[2]
for path in (ROOT, ROOT / "python", ROOT / "kernels"):
    sys.path.insert(0, str(path))

from scripts.deployment.common import qualify_proof_case
from ir.verus_contract import render_verified_kernel_to_verus
from scripts.verification.kernel_qualification_inventory import selected_kernel_cases
from scripts.verification.kernel_interface_registry import load_registry
from scripts.verification.rectangular_interface_codegen import render_rectangular_interface
from scripts.verification.rectangular_interface_catalog import has_static_shape_geometry, render_rectangular_catalog
from vosti_kernels.kernel_interfaces import RECTANGULAR_KERNEL_INTERFACES


OPERATORS = {name: source for source, name in RECTANGULAR_KERNEL_INTERFACES.items()}
HEADER = """// @generated by scripts/verification/verify_rectangular_interfaces.py; DO NOT EDIT.
#![allow(non_snake_case)]
use vstd::prelude::*;
use crate::{boundary::scalar::{Scalar}, proof::tensor::types::{Tensor1D, Tensor2D, IntTensor1D}};
use crate::proof::tensor::shape as TS;
#[cfg(verus_only)]
use crate::boundary::backend_certificates::support::generated_kernel_allocation_cell;

verus! {
"""
MARKER = "\n// BEGIN CHECKED RECTANGULAR ADAPTER\n"
TRAILER = "\n} // verus!\n"


def selected_cases(name, families=None):
    source, kernel = OPERATORS[name]
    return [(contract, constants, contributors)
            for contract, constants, contributors in selected_kernel_cases(families)
            if (contract["source"], contract["kernel"]) == (source, kernel)]


def render_qualified_cases(cases):
    cases = tuple(cases)
    implementations = tuple(q.contracts for _, _, _, q in cases)
    if has_static_shape_geometry(implementations):
        catalog = render_rectangular_catalog(implementations)
        body, manifest = catalog.body, json.loads(catalog.manifest())
    else:
        interface = render_rectangular_interface(implementations)
        body = HEADER + interface.raw.body + MARKER + interface.adapter_body + TRAILER
        manifest = dict(schema_version=1, kind="rectangular_kernel_interface",
            generated_body_sha256=hashlib.sha256(body.encode()).hexdigest(),
            checked_adapter_sha256=hashlib.sha256(interface.adapter_body.encode()).hexdigest(),
            raw=json.loads(interface.raw.manifest()))
    contributions = []
    for contract, constants, families, qualified in cases:
        execution = render_verified_kernel_to_verus(qualified.contracts, symbol_prefix="raw")
        contributions.append(dict(source=contract["source"], kernel=contract["kernel"],
                                  constants=constants, families=sorted(families),
                                  execution_identity=execution.execution_identity))
    manifest["inventory_contributions"] = contributions
    return body, json.dumps(manifest, sort_keys=True, indent=2) + "\n"


def generate(name):
    cases = []
    for contract, constants, contributors in selected_cases(name):
        qualified = qualify_proof_case(contract, constants, ("bfloat16", "float32"))
        cases.append((contract, constants, contributors, qualified))
        print(f"[RAW PASS] {contract['kernel']} {constants}", flush=True)
    return render_qualified_cases(cases)


def check_or_write(name, body, manifest, *, write=False):
    if name not in OPERATORS:
        raise ValueError("unknown rectangular interface")
    paths = (ROOT / f"src/boundary/backend_certificates/{name}.rs",
             ROOT / f"audit/{name}_kernel_interface.json")
    _, interfaces = load_registry()
    entry = interfaces[name]
    if (entry["generated"] != paths[0].relative_to(ROOT).as_posix()
            or entry["manifest"] != paths[1].relative_to(ROOT).as_posix()
            or entry["generator"] != Path(__file__).relative_to(ROOT).as_posix()):
        raise ValueError("rectangular generator paths differ from reviewed registry")
    for path, text in zip(paths, (body, manifest)):
        if write:
            path.write_text(text)
        elif not path.is_file() or path.read_text() != text:
            raise ValueError(f"stale rectangular kernel interface: {path}")
    print(f"Rectangular interface {name} " + ("updated" if write else "matches qualified sources")
          + "; checked adapters additionally require Verus.")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--interface", choices=sorted(OPERATORS), default="linear")
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    check_or_write(args.interface, *generate(args.interface), write=args.write)


if __name__ == "__main__":
    main()
